# Load libraries

In [149]:
import pandas as pd 
import numpy as np
import re

# Load datasets

In [150]:
df1 = pd.read_csv("data/ALLARMI.csv")
df2 = pd.read_csv("data/TIPOLOGIA_VIAGGIATORE.csv")

In [151]:
df1

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5075,Nulla a procedere SDI,MXP,LTN,2023,01,2024-01-19 17:30:00,Malpensa,London Luton,Milano,Londra,...,2,5,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,5
5076,Voli disponibili in ingresso al Sistema,BLQ,RAK,2024,02,FEB 06 2024,Guglielmo Marconi,Menara,Bologna,Marrakech,...,8,1,TSC,NaN,NaN,Marocco,ITA,8,Italia,1
5077,Voli con Allarmi,FCO,DOH,2024,01,2024-01-12 15:35:00,Fiumicino,Hamad International,Roma,Doha,...,5,1,NSIS,NaN,NaN,Qatar,ITA,5,Italia,1
5078,"Voli solo visualizzati, ma NON investigati",LIN,LHR,2024,01,2024-01-13 11:50:00,Linate,London Heathrow,Milano,Londra,...,2,1,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,1
5079,Voli investigati (SDI/NSIS - INTERPOL - TSC),PSA,LGW,2024,02,2024-02-26 13:30:00,Galileo Galilei,London Gatwick,Pisa,Londra,...,8,1,TSC,NaN,NaN,Regno Unito,ITA,8,Italia,1

In [152]:
df2

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5090,ALB,BLQ,TIA,2024,02,15,2024-02-18 09:10:00,Guglielmo Marconi,Rinas Mother Teresa,Bologna,...,Ryanair DAC,FR8399,NaN,NaN,NaN,N.D.,0-17,ALB,Ryanair DAC,FR8399
5091,ALB,FCO,TIA,2024,01,10,2024-01-10 06:10:00,Fiumicino,Rinas Mother Teresa,Roma,...,Wizz Air Malta,W43857,NaN,NaN,NaN,Passaporto,46-60,ALB,Wizz Air Malta,W43857
5092,ALB,FCO,JED,2024,01,31,31/01/2024 22:15:00,Fiumicino,King Abdulaziz International,Roma,...,Wizz Air Malta,w48350,FERMATO,NaN,NaN,N.D.,31-45,ALB,Wizz Air Malta,w48350
5093,ALB,BGY,TIA,2024,01,1,2024-01-01 08:25:00,Orio al Serio,Rinas Mother Teresa,Bergamo,...,Ryanair DAC,FR8350,IN ATTESA,NaN,NaN,Carta d'identità,18-30,ALB,Ryanair DAC,FR8350
5094,ALB,FCO,MIA,2024,01,12,2024-01-12 19:50:00,Fiumicino,Miami International,Roma,...,ITA Airways,NaN,FERMATO,NaN,NaN,Carta d'identità,61+,ALB,ITA Airways,AZ0631

# Allarmi Dataset

First general look at the dataset (df1)

In [153]:
df1.shape

(5080, 24)

In [154]:
df1.head(5)

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2

In [155]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5080 entries, 0 to 5079
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   OCCORRENZE             5080 non-null   str
 1   AREOPORTO_ARRIVO       5080 non-null   str
 2   AREOPORTO_PARTENZA     5080 non-null   str
 3   ANNO_PARTENZA          5080 non-null   str
 4   MESE_PARTENZA          5080 non-null   str
 5   DATA_PARTENZA          5080 non-null   str
 6   DESCR_AEREOPORTO_ARR   5080 non-null   str
 7   DESCR_AEREOPORTO_PART  4971 non-null   str
 8   CITTA_ARR              5080 non-null   str
 9   CITTA_PARTENZA         4979 non-null   str
 10  CODICE_PAESE_ARR       5080 non-null   str
 11  CODICE_PAESE_PART      5026 non-null   str
 12  PAESE_ARR              5080 non-null   str
 13  PAESE_PART             5006 non-null   str
 14  ZONA                   5080 non-null   str
 15  TOT                    5080 non-null   str
 16  MOTIVO_ALLARME         3920 non-null   str
 17  note_operatore         77 non-null     str
 18  flag_rischio           51 non-null     str
 19  Paese Partenza         5080 non-null   str
 20  CODICE PAESE ARR       5080 non-null   str
 21  3zona                  5080 non-null   int64
 22  paese%arr              5080 non-null   str
 23  tot voli               5080 non-null   str
dtypes: int64(1), str(23)
memory usage: 952.6 KB

In [ ]:
# Normalizing the dataset, lowercasing and stripping useless cases
df1 = df1.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

# Checking for duplicates and dropping them 
print('Initial duplicates:')
print(df1.duplicated().sum())
df1 = df1.drop_duplicates()
print('Duplicates after cleaning:')
print(df1.duplicated().sum())

Initial duplicates:
50
Duplicates after cleaning:
0

### Occorrenze

In [158]:
print(f"Unique values: {df1['OCCORRENZE'].nunique()}")
print(f"Null values: {df1['OCCORRENZE'].isnull().sum()}")
print()
print(df1['OCCORRENZE'].value_counts(dropna=False).to_string())

Unique values: 30
Null values: 0

OCCORRENZE
viaggiatori entrati nel sistema                 618
voli disponibili in ingresso al sistema         583
voli solo visualizzati, ma non investigati      563
voli investigati (sdi/nsis - interpol - tsc)    540
viaggiatori investigati                         520
allarmi generati da sdi/nsis                    509
voli con allarmi                                505
viaggiatori con allarmi                         463
nulla a procedere sdi                           247
allarmi chiusi                                  243
allarmi rilevanti                               112
errata segnalazione sdi                          25
allarmi generati da bcs                          21
allarmi chiusi con azione (cc.xx)                14
notifica atti/provv                              10
allarmi generati da interpol                      8
allarmi non chiusi                                7
mancato aggiornamento sdi                         6
nulla a procedere nsis                            6
respinto/a                                        5
errata segnalazione bcs                           5
allarmi generati                                  5
inammissibilita schengen - art.24                 4
errata segnalazione nsis                          3
mancato aggiornamento schengen nsis               2
altro                                             2
nulla a procedere int                             1
???                                               1
n/c                                               1
allarmati                                         1

Grouping categories that are similar to each other

In [159]:
occorrenze_map = {
    'viaggiatori entrati nel sistema'              : 'viaggiatori entrati',
    'voli disponibili in ingresso al sistema'      : 'voli disponibili',
    'voli solo visualizzati, ma non investigati'   : 'voli solo visualizzati',
    'voli investigati (sdi/nsis - interpol - tsc)' : 'voli investigati',
    'viaggiatori investigati'                      : 'viaggiatori investigati',
    'voli con allarmi'                             : 'voli con allarmi',
    'viaggiatori con allarmi'                      : 'viaggiatori con allarmi',
    'allarmi generati da sdi/nsis'                 : 'allarmi generati',
    'allarmi generati da bcs'                      : 'allarmi generati',
    'allarmi generati da interpol'                 : 'allarmi generati',
    'allarmi generati'                             : 'allarmi generati',
    'allarmi chiusi'                               : 'allarmi chiusi',
    'allarmi chiusi con azione (cc.xx)'            : 'allarmi chiusi',
    'allarmi rilevanti'                            : 'allarmi rilevanti',
    'allarmi non chiusi'                           : 'allarmi non chiusi',
    'nulla a procedere sdi'                        : 'esito negativo',
    'nulla a procedere nsis'                       : 'esito negativo',
    'nulla a procedere int'                        : 'esito negativo',
    'errata segnalazione sdi'                      : 'esito negativo',
    'errata segnalazione nsis'                     : 'esito negativo',
    'errata segnalazione bcs'                      : 'esito negativo',
    'respinto/a'                                   : 'esito negativo',
    'mancato aggiornamento sdi'                    : 'mancato aggiornamento',
    'mancato aggiornamento schengen nsis'          : 'mancato aggiornamento',
    'notifica atti/provv'                          : 'altro',
    'inammissibilita schengen - art.24'            : 'altro',
    'altro'                                        : 'altro',
    '???'                                          : np.nan,
    'n/c'                                          : np.nan,
    'ali armatt'                                   : np.nan,
}

df1['OCCORRENZE'] = df1['OCCORRENZE'].map(occorrenze_map)

print(f"\nNull Values: {df1['OCCORRENZE'].isnull().sum()}")
print(f"\nDistribution:")
print(df1['OCCORRENZE'].value_counts(dropna=False).to_string())

Null Values: 3

Distribution:
OCCORRENZE
viaggiatori entrati        618
voli disponibili           583
voli solo visualizzati     563
allarmi generati           543
voli investigati           540
viaggiatori investigati    520
voli con allarmi           505
viaggiatori con allarmi    463
esito negativo             292
allarmi chiusi             257
allarmi rilevanti          112
altro                       16
mancato aggiornamento        8
allarmi non chiusi           7
NaN                          3

### Aeroporto Arrivo

In [160]:
print(f"Unique values: {df1['AREOPORTO_ARRIVO'].nunique()}")
print(f"Null values: {df1['AREOPORTO_ARRIVO'].isnull().sum()}")
print()
print(df1['AREOPORTO_ARRIVO'].value_counts(dropna=False).to_string())

Unique values: 31
Null values: 0

AREOPORTO_ARRIVO
fco    1272
mxp    1185
bgy     464
vce     356
blq     326
nap     202
lin     174
cia     163
trn     151
psa     139
cta     114
vrn     108
tsf      82
flr      68
bri      57
pmo      26
aoi      24
goa      20
peg      16
psr      15
trs      14
rmi      12
suf       9
pmf       7
cag       7
bds       6
cuf       6
ciy       3
bzo       2
olb       1
vbs       1

In [161]:
# ── df1 – AREOPORTO_PARTENZA ─────────────────────────────────────────────────
print(f"Valori unici: {df1['AREOPORTO_PARTENZA'].nunique()}")
print(f"Valori nulli: {df1['AREOPORTO_PARTENZA'].isnull().sum()}")
print()
print(df1['AREOPORTO_PARTENZA'].value_counts(dropna=False).to_string())

Valori unici: 112
Valori nulli: 0

AREOPORTO_PARTENZA
tia    612
stn    502
lgw    401
lhr    387
ist    300
dxb    153
cai    133
saw    132
cmn    130
man    129
doh    105
rak    105
jfk    104
ssh     95
tun     86
beg     81
auh     77
lcy     73
ewr     63
ltn     58
jed     52
gru     51
edi     50
brs     46
amm     46
add     46
tlv     45
rmo     43
bhx     41
pek     35
eze     31
evn     31
spx     30
pvg     30
icn     28
del     27
tpe     25
alg     25
kwi     23
sin     22
ruh     21
mct     20
ema     18
skp     17
mle     17
szx     17
gig     17
atl     16
mia     16
kiv     15
gyd     15
ncl     15
rmf     15
shj     15
wnz     13
bah     13
ika     12
dss     12
yul     12
kut     12
tgd     11
phl     11
mex     10
gla     10
hnd     10
fez      9
lrm      9
hrg      9
sid      9
mba      9
hkg      8
tng      8
dfw      8
prn      8
bqh      8
dwc      8
fab      7
bey      7
hgh      6
yyz      6
lpl      6
tbs      6
iad      6
adb      6
znz      5
nkg      5
cgo      4
atq      4
rba      4
mji      4
aga      4
dmm      4
tfu      4
ckg      3
bfs      3
bos      3
lxr      3
can      3
sll      3
mru      2
cun      2
lba      2
tas      2
mbj      2
oxf      1
ala      1
anu      1
isl      1
lyx      1
nht      1
oak      1
lax      1

### Anno Partenza

In [162]:
print(f"Unique values: {df1['ANNO_PARTENZA'].nunique()}")
print(f"Null values: {df1['ANNO_PARTENZA'].isnull().sum()}")
print()
print(df1['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 5
Null values: 0

ANNO_PARTENZA
2024         4631
2023          256
24             52
anno 2024      49
2024.          42

In [163]:
def normalizza_anno(val):
    if pd.isna(val): return np.nan
    val = str(val).strip()
    match = re.search(r'\b(20\d{2})\b', val)
    if match: return int(match.group(1))
    match = re.search(r'\b(\d{2})\b', val)
    if match: return int('20' + match.group(1))
    return np.nan

df1['ANNO_PARTENZA'] = df1['ANNO_PARTENZA'].apply(normalizza_anno)

print(df1['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

ANNO_PARTENZA
2024    4774
2023     256

### Mese Partenza

In [164]:
print(f"Unique values: {df1['MESE_PARTENZA'].nunique()}")
print(f"Null values: {df1['MESE_PARTENZA'].isnull().sum()}")
print()
print(df1['MESE_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 14
Null values: 0

MESE_PARTENZA
01     2425
02     2273
gen      80
feb      63
12       26
07       23
06       22
04       21
11       19
09       17
03       16
08       15
05       15
10       15

In [165]:
mesi_map = {"gen": "01", "feb": "02"}
df1["MESE_PARTENZA"] = df1["MESE_PARTENZA"].replace(mesi_map)

print(df1["MESE_PARTENZA"].value_counts(dropna=False).sort_index().to_string())

MESE_PARTENZA
01    2505
02    2336
03      16
04      21
05      15
06      22
07      23
08      15
09      17
10      15
11      19
12      26

### Data Partenza

In [166]:
print(f"Unique values: {df1['DATA_PARTENZA'].nunique()}")
print(f"Null values: {df1['DATA_PARTENZA'].isnull().sum()}")
print()
print(df1['DATA_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 3810
Null values: 0

DATA_PARTENZA
2024-02-04 06:10:00    6
2024-01-31 18:00:00    6
2024-01-19 08:55:00    5
2024-01-22 13:00:00    5
2024/02/26             5
2024-01-04 11:30:00    5
2024-01-06 08:00:00    5
2024-02-29 16:40:00    5
2024-02-18 06:50:00    5
2024-02-09 12:50:00    4
05.01.2024             4
gen 06 2024            4
feb 18 2024            4
2024-01-30 12:35:00    4
18.02.2024             4
2024-01-22 07:30:00    4
2024-02-19 09:00:00    4
2024-02-10 22:20:00    4
gen 14 2024            4
2024-02-08 10:00:00    4
17-01-24               4
2024-02-18 13:05:00    4
2024-01-01 08:00:00    4
2024-02-02 09:15:00    4
2024-01-05 19:05:00    4
2024-01-27 18:05:00    4
23-02-24               4
2024-01-24 08:00:00    4
2024-02-09 18:05:00    4
2024-01-21 17:50:00    4
2024-02-19 17:55:00    4
2024-01-07 18:00:00    4
2024-01-04 09:25:00    4
2024-02-13 17:55:00    4
2024-02-02 17:20:00    4
2024-02-02 12:50:00    4
2024-02-09 13:20:00    4
2024-02-19 20:30:00    4
2024-02-23 18:00:00    4
2024-02-19 18:20:00    4
2024-01-19 14:45:00    4
2024-02-19 15:45:00    4
2024-02-17 06:45:00    4
2024-01-10 08:55:00    4
2024-02-11 07:15:00    4
2024-02-21 08:55:00    4
2024-02-03 08:10:00    4
2024-01-02 08:25:00    4
2024-01-18 20:45:00    4
2024-02-09 07:55:00    4
2024-01-06 09:20:00    3
2024-01-27 06:40:00    3
2024-02-25 13:10:00    3
2024-02-04 07:45:00    3
2024-01-01 05:45:00    3
2024-01-01 10:30:00    3
2024-01-07 12:30:00    3
2024/02/25             3
09.01.2024             3
2024-02-22 21:50:00    3
2024-01-02 12:00:00    3
2024-01-05 13:40:00    3
2024-02-16 13:40:00    3
2024-02-18 11:45:00    3
2024/02/08             3
2024-01-02 06:55:00    3
2024-01-26 06:15:00    3
2024-01-27 15:35:00    3
2024-01-12 07:15:00    3
2024-01-24 06:10:00    3
2024-01-18 07:00:00    3
2024-01-14 09:35:00    3
2024-02-04 20:15:00    3
2024-01-11 14:05:00    3
2024/02/01             3
2024-02-16 17:35:00    3
2024-01-21 21:00:00    3
2024-01-26 18:00:00    3
2024-02-17 06:20:00    3
2024-02-11 09:35:00    3
2024-02-10 07:50:00    3
2024-01-07 17:00:00    3
2024-01-23 08:55:00    3
01.01.2024             3
2024-01-26 13:00:00    3
gen 27 2024            3
2024-01-13 12:50:00    3
2024-02-09 07:15:00    3
2024-01-18 12:35:00    3
2024-01-03 07:25:00    3
2024/01/18             3
2024-01-19 10:20:00    3
2024-01-12 15:35:00    3
2024-01-08 17:25:00    3
2024-02-16 17:30:00    3
2024-01-13 07:25:00    3
2024-01-04 14:20:00    3
2024-01-27 10:00:00    3
2024-02-13 09:15:00    3
2024-01-08 19:40:00    3
2024-02-07 18:00:00    3
2024-02-26 07:45:00    3
2024-02-09 20:40:00    3
2024-02-25 18:20:00    3
2024-01-29 07:30:00    3
2024-02-16 14:50:00    3
2024-01-22 18:00:00    3
2024-01-20 19:50:00    3
2024-02-05 18:00:00    3
2024-01-21 21:50:00    3
2024-02-17 06:05:00    3
2024-01-02 19:50:00    3
2024-02-05 08:00:00    3
2024/01/26             3
2024-01-14 18:35:00    3
2024-01-21 15:55:00    3
2024-02-16 21:00:00    3
2024-01-08 07:10:00    3
2024-01-18 21:50:00    3
2024-02-21 20:35:00    3
2024/01/05             3
2024-02-17 13:00:00    3
2024-01-06 08:25:00    3
24-02-24               3
2024-02-23 18:20:00    3
2024-02-06 15:50:00    3
12-02-24               3
2024-02-14 18:00:00    3
2024-02-26 19:50:00    3
2024-02-06 12:55:00    3
2024-01-08 09:15:00    3
2024-01-08 09:00:00    3
2024-02-04 20:40:00    3
2024-01-17 10:35:00    3
22.01.2024             3
2024-02-01 19:50:00    3
2024-02-17 06:00:00    3
05-01-24               3
2024-01-04 13:25:00    3
2024-01-24 19:50:00    3
2024-02-05 13:00:00    3
2024-02-25 13:00:00    3
2024-02-20 14:55:00    3
2024-01-14 10:15:00    3
2024-01-11 06:00:00    3
2024-02-17 17:45:00    3
2024-01-26 13:40:00    3
10-01-24               3
2024-01-16 12:00:00    3
2024-01-04 21:00:00    3
2024-02-01 07:10:00    3
2024-02-20 12:50:00    3
27-01-24               3
2024-02-21 06:10:00    3
2024-02-21 08:00:00    3
2024-02-01 21:50:00    3
2024-02-14 12:10:00    3
2024-01-10 08:50:00    3
feb 01 2024            3
2024-01-31 09:25:00    3
2024-01-07 16:05:00    3
2024-01-03 06:50:00    3
23.02.2024             3
2024-02-05 15:35:00    3
2024-02-23 20:50:00    3
2024-02-21 18:00:00    3
2024-02-25 18:25:00    3
2024/02/03             3
2024-01-03 21:35:00    3
2024-01-14 19:25:00    3
2024-01-04 12:40:00    3
2024-01-03 14:10:00    3
2024-02-02 07:00:00    3
2024-02-01 18:00:00    3
2024-01-02 07:30:00    3
2024-01-06 08:15:00    3
2024-01-31 11:20:00    3
2024-02-17 19:50:00    3
2024-01-22 20:40:00    3
2024-02-25 15:30:00    3
20-01-24               3
2024-01-05 02:20:00    3
2024-01-07 13:50:00    3
2024-01-27 15:45:00    3
2024-01-10 13:00:00    3
2024-01-08 18:00:00    3
2024-01-16 12:55:00    3
2024-01-20 06:50:00    3
2024-02-17 20:15:00    3
2024-01-15 07:20:00    3
2024-02-18 09:50:00    3
2024-02-17 20:40:00    3
2024-01-27 13:20:00    3
2024-02-28 16:05:00    3
2024-01-11 08:00:00    3
2024-02-11 18:25:00    3
2024-02-28 17:35:00    3
2024-02-28 06:10:00    3
2024-02-16 12:35:00    3
2024-01-09 13:05:00    3
2024-01-12 08:55:00    3
01-02-24               3
2024-02-10 07:00:00    3
2024-02-09 07:00:00    3
28-01-24               3
feb 06 2024            3
2024-01-07 07:00:00    3
2024-01-28 18:35:00    3
2024-01-22 14:15:00    3
2024-02-29 19:40:00    3
2024-02-21 15:00:00    3
2024-02-08 19:55:00    3
2024-01-04 06:10:00    3
2024-01-05 12:00:00    3
2024-01-28 19:25:00    3
2024-01-12 17:30:00    3
2024-01-27 12:05:00    3
2024-02-16 12:50:00    2
2024-01-13 10:00:00    2
2024-02-23 07:15:00    2
2024-02-12 08:00:00    2
2024-01-15 17:10:00    2
28.01.2024             2
2024-01-14 07:55:00    2
2024-02-10 15:15:00    2
2024-02-25 17:30:00    2
2024-02-08 17:55:00    2
2024-01-12 08:10:00    2
2024-02-13 06:15:00    2
2024-02-16 10:40:00    2
2024-02-04 07:35:00    2
2024-01-03 13:20:00    2
2024-01-25 08:10:00    2
2024-01-27 12:20:00    2
2024-01-05 07:55:00    2
2024-02-24 22:05:00    2
2024-02-08 12:40:00    2
2024-02-05 13:25:00    2
2024-02-07 07:55:00    2
2024-01-19 19:05:00    2
2024-02-03 13:00:00    2
2024-01-11 06:45:00    2
2024-01-02 07:00:00    2
2024/01/08             2
2024-01-06 18:00:00    2
2024-01-07 10:00:00    2
2024-01-02 21:35:00    2
2024-01-31 15:35:00    2
2024-02-26 20:30:00    2
2024-01-01 11:40:00    2
2024-01-21 13:05:00    2
2024-02-13 13:40:00    2
2024-02-29 06:00:00    2
2024-02-02 18:05:00    2
2024-02-05 06:10:00    2
2024/02/16             2
2024-02-25 18:50:00    2
feb 07 2024            2
2024-01-03 17:00:00    2
2024-02-15 11:50:00    2
2024-01-13 12:00:00    2
2024-02-08 15:20:00    2
2024-02-12 18:10:00    2
2024-01-24 13:40:00    2
2024-01-04 08:55:00    2
2024-01-27 13:05:00    2
2024-01-17 03:45:00    2
2024-01-17 17:00:00    2
2024-01-02 13:05:00    2
2024-02-14 13:20:00    2
2024/01/12             2
2024-01-18 12:00:00    2
2024-02-16 08:55:00    2
2024-02-15 14:15:00    2
2024-01-25 17:00:00    2
2024-01-20 13:05:00    2
2024-02-26 18:10:00    2
2024-01-14 11:30:00    2
2024-01-11 07:00:00    2
2024-02-27 14:30:00    2
2024-02-04 06:50:00    2
2024-02-04 21:10:00    2
2024-01-27 17:05:00    2
2024-02-18 12:10:00    2
2024-01-15 17:25:00    2
2024-02-01 09:00:00    2
2024-02-23 11:30:00    2
2024-01-18 12:10:00    2
2024-02-01 07:00:00    2
2024-02-13 22:40:00    2
2024-01-14 10:45:00    2
2024-02-20 16:00:00    2
2024/01/02             2
2024-02-27 09:00:00    2
2024-01-30 07:00:00    2
2024-02-26 21:50:00    2
2024-01-23 17:40:00    2
2024-01-09 12:10:00    2
2024-01-07 09:35:00    2
2024-02-29 01:30:00    2
2024-02-17 09:05:00    2
2024-01-25 15:45:00    2
2024-02-10 08:55:00    2
2024-01-22 07:20:00    2
2024-02-08 20:30:00    2
2024-01-12 18:55:00    2
2024-02-10 09:10:00    2
2024-01-10 19:55:00    2
2024-02-02 11:25:00    2
2024-01-24 09:35:00    2
2024-01-06 06:55:00    2
2024-02-23 16:45:00    2
2024-01-19 18:15:00    2
2024-02-23 11:00:00    2
2024-01-09 14:05:00    2
2024-01-19 08:00:00    2
2024/02/07             2
2024-01-20 12:50:00    2
31-01-24               2
2024-02-28 05:35:00    2
2024-02-18 21:00:00    2
2024-02-24 11:30:00    2
2024-02-11 17:40:00    2
2024-02-28 11:05:00    2
2024-02-04 20:00:00    2
2024-01-04 18:20:00    2
2024-01-03 16:20:00    2
2024-02-02 10:20:00    2
2024-02-02 07:45:00    2
2024-01-30 07:10:00    2
2024-01-22 08:55:00    2
2024-02-25 18:35:00    2
2024-02-19 07:35:00    2
2024/02/21             2
2024-02-20 09:30:00    2
2024-02-16 13:00:00    2
2024-01-30 20:10:00    2
2024-02-14 17:40:00    2
2024-02-07 07:10:00    2
2024-01-24 18:00:00    2
2024-01-03 08:50:00    2
2024-01-10 12:00:00    2
2024-02-11 08:50:00    2
2024-02-17 14:05:00    2
2024/01/09             2
2024-01-13 19:50:00    2
2024-02-26 02:00:00    2
2024-02-12 09:00:00    2
2024-01-15 06:05:00    2
2024-01-22 21:50:00    2
2024-01-07 09:30:00    2
2024-02-04 18:00:00    2
2024-02-08 14:10:00    2
2024-01-12 16:35:00    2
2024-01-02 14:05:00    2
2024-02-25 10:10:00    2
2024-01-08 17:40:00    2
2024-02-28 14:40:00    2
2024-01-12 06:55:00    2
2024-02-26 17:50:00    2
2024-01-19 11:00:00    2
2024-01-12 16:20:00    2
2024-01-19 12:10:00    2
04-02-24               2
2024-01-17 17:45:00    2
2024-01-27 11:15:00    2
2024-01-29 20:20:00    2
2024-02-08 08:25:00    2
2024-01-19 12:05:00    2
2024-02-22 22:10:00    2
2024-02-25 15:10:00    2
2024-01-12 13:55:00    2
2024-02-01 22:20:00    2
2024-01-09 23:25:00    2
2024-01-29 08:50:00    2
2024-01-28 23:25:00    2
2024-01-22 06:10:00    2
2024-01-01 09:35:00    2
2024-02-13 07:50:00    2
2024-01-23 10:30:00    2
2024-01-28 12:00:00    2
2024-02-27 15:00:00    2
2024-02-08 07:55:00    2
2024-02-27 17:00:00    2
2024-02-26 13:40:00    2
2024-02-10 10:00:00    2
2024-01-11 07:20:00    2
2024-02-28 12:10:00    2
2024-02-23 10:30:00    2
2024-01-16 18:05:00    2
2024-01-02 06:45:00    2
2024-02-04 09:30:00    2
2024-02-17 21:40:00    2
2024-01-25 07:15:00    2
2024-02-03 08:55:00    2
2024-01-17 18:40:00    2
2024-01-27 14:55:00    2
2024-01-02 06:10:00    2
2024-01-02 10:00:00    2
2024-02-15 10:00:00    2
2024-02-11 19:25:00    2
2024/02/22             2
2024-01-31 17:00:00    2
2024-02-26 06:10:00    2
2024-02-06 13:30:00    2
2024-02-09 16:20:00    2
2024-01-15 15:10:00    2
2024-02-03 06:50:00    2
2024-01-20 06:55:00    2
2024-01-14 07:45:00    2
2024-02-12 04:30:00    2
2024-01-20 22:10:00    2
2024-02-12 20:40:00    2
2024-01-01 10:00:00    2
30-01-24               2
2024-01-11 06:20:00    2
2024-02-11 13:05:00    2
2024-01-13 11:35:00    2
feb 29 2024            2
2024-01-23 21:00:00    2
2024-01-25 07:00:00    2
2024-02-20 07:15:00    2
2024-02-02 07:35:00    2
2024-01-06 20:30:00    2
2024-02-23 12:05:00    2
2024-02-28 13:45:00    2
2024-01-16 08:55:00    2
2024-01-13 13:00:00    2
2024-01-25 12:40:00    2
2024-02-19 18:10:00    2
2024-02-05 08:55:00    2
2024-02-27 09:15:00    2
2024-01-07 19:05:00    2
2024-02-19 08:55:00    2
2024-02-09 19:05:00    2
2024-01-06 10:35:00    2
10.01.2024             2
2024-01-21 13:00:00    2
feb 19 2024            2
2024-01-04 11:00:00    2
2024-01-20 10:00:00    2
2024-01-30 10:15:00    2
2024-02-07 07:30:00    2
2024-01-15 12:15:00    2
2024-01-10 17:55:00    2
2024-01-04 09:15:00    2
2024-02-08 13:15:00    2
2024-01-28 09:48:00    2
2024-02-24 08:10:00    2
2024-01-02 19:55:00    2
2024-01-27 08:55:00    2
2024-02-07 13:55:00    2
2024-02-14 13:45:00    2
2024-01-07 08:00:00    2
2024-02-06 07:30:00    2
2024-01-08 06:45:00    2
2024-01-05 17:55:00    2
2024-02-16 10:20:00    2
2024-01-25 13:20:00    2
2024-01-07 11:15:00    2
2024-01-29 14:40:00    2
2024-01-17 22:20:00    2
2024-01-14 21:00:00    2
2024-01-03 19:20:00    2
2024-01-17 06:10:00    2
2024-01-14 06:10:00    2
2024-02-10 08:00:00    2
2024-02-10 18:25:00    2
2024-01-07 06:50:00    2
2024-02-04 15:45:00    2
2024-02-08 19:40:00    2
2024-01-25 10:00:00    2
2024-01-23 18:05:00    2
2024-02-21 10:05:00    2
2024-02-13 14:15:00    2
2024-01-05 09:15:00    2
2024-02-24 14:00:00    2
2024-01-02 14:58:00    2
2024-01-20 06:30:00    2
2024-01-10 14:35:00    2
2024-01-07 16:15:00    2
2024-02-10 10:30:00    2
2024-02-17 18:35:00    2
2024-01-18 18:05:00    2
2024-02-19 17:00:00    2
2024-01-15 20:55:00    2
2024-01-11 20:30:00    2
21-02-24               2
2024-02-23 06:45:00    2
feb 09 2024            2
2024-02-19 13:00:00    2
2024-01-17 10:25:00    2
2024-01-10 11:55:00    2
2024-02-24 18:00:00    2
2024-01-02 12:10:00    2
2024-02-03 19:45:00    2
2024-02-16 12:10:00    2
2024-01-25 11:15:00    2
2024-01-12 15:55:00    2
2024-02-05 17:55:00    2
2024-02-08 13:05:00    2
2024-01-21 10:10:00    2
2024-01-17 13:25:00    2
2024-01-20 06:20:00    2
2024-01-26 18:15:00    2
2024-01-18 17:00:00    2
2024-01-27 08:40:00    2
2024-02-10 06:00:00    2
2024-02-09 00:05:00    2
2024-02-21 19:25:00    2
2024-01-27 23:05:00    2
2024-02-03 08:40:00    2
2024-02-13 13:45:00    2
2024-02-08 07:00:00    2
29.02.2024             2
2024-01-12 06:20:00    2
2024-01-07 06:00:00    2
2024-02-07 16:00:00    2
2024-02-20 08:10:00    2
2024-02-28 06:45:00    2
2024-02-04 18:05:00    2
2024-02-18 10:10:00    2
2024-02-16 17:20:00    2
2024-01-30 17:50:00    2
2024-02-24 14:05:00    2
2024-02-04 07:00:00    2
2024-01-07 12:00:00    2
2024-02-18 00:50:00    2
2024-01-23 21:20:00    2
2024-02-26 09:00:00    2
2024-01-15 07:30:00    2
2024/02/04             2
2024-01-13 10:30:00    2
2024-01-04 12:50:00    2
2024-01-27 14:05:00    2
2024-01-02 08:00:00    2
2024-02-08 19:10:00    2
2024-02-18 13:30:00    2
2024-01-17 10:00:00    2
2024-01-25 12:35:00    2
17-02-24               2
2024-01-18 08:10:00    2
2024-02-12 18:20:00    2
2024-02-22 13:20:00    2
2024-02-13 17:40:00    2
2024-01-07 23:45:00    2
2024-02-12 14:20:00    2
2024-02-08 13:45:00    2
2024-01-30 06:45:00    2
2024-01-26 01:45:00    2
2024-01-08 13:25:00    2
2024-02-04 07:15:00    2
2024-01-08 06:05:00    2
2024-01-06 16:15:00    2
2024-02-13 06:00:00    2
2024-02-23 21:05:00    2
2024-02-19 19:45:00    2
2024-01-20 17:55:00    2
2024-01-28 17:55:00    2
2024-01-31 10:40:00    2
2024-01-18 08:25:00    2
2024-02-17 08:30:00    2
2024-02-11 06:00:00    2
2024-01-28 12:50:00    2
2024-01-02 10:35:00    2
2024/01/11             2
2024-01-17 20:45:00    2
2024-02-09 13:40:00    2
2024-02-25 20:15:00    2
2024-01-24 09:00:00    2
2024-02-06 20:15:00    2
2024-02-06 21:50:00    2
2024-01-15 13:00:00    2
2024-02-27 11:25:00    2
20.01.2024             2
2024-02-22 09:21:00    2
2024-01-01 13:25:00    2
2024-01-27 19:50:00    2
2024-02-03 07:50:00    2
2024-02-04 08:10:00    2
2024-01-13 15:45:00    2
gen 29 2024            2
2024-02-22 09:25:00    2
2024-02-09 06:20:00    2
2024/01/15             2
2024-02-02 11:30:00    2
2024-02-03 15:25:00    2
2024-02-11 21:20:00    2
2024-02-16 20:50:00    2
2024-02-01 14:25:00    2
2024-02-02 07:55:00    2
2024-02-18 07:05:00    2
2024-01-03 16:40:00    2
2024-01-11 11:15:00    2
2024-02-16 16:10:00    2
2024-02-18 12:50:00    2
2024-02-27 07:25:00    2
2024-01-25 18:35:00    2
2024-01-10 08:00:00    2
2024-01-08 15:45:00    2
2024-02-13 20:45:00    2
2024-01-28 16:00:00    2
2024-02-06 11:15:00    2
2024-02-10 15:50:00    2
gen 08 2024            2
2024-02-02 18:00:00    2
2024-02-26 05:45:00    2
2024-01-15 02:20:00    2
2024-02-16 11:40:00    2
2024-01-13 21:05:00    2
2024-01-14 08:00:00    2
2024-01-15 18:15:00    2
2024-02-20 13:45:00    2
2024-02-16 15:00:00    2
2024-01-12 19:55:00    2
2024-02-10 00:15:00    2
2024-01-05 06:10:00    2
2024-01-12 07:30:00    2
2024-01-31 15:00:00    2
2024-02-29 18:00:00    2
2024-02-10 08:10:00    2
2024-01-06 08:10:00    2
2024-02-23 13:00:00    2
2024-02-01 08:05:00    2
2024-02-23 12:15:00    2
2024-02-10 09:35:00    2
2024-02-23 08:00:00    2
2024-02-15 13:00:00    2
2024-02-17 17:40:00    2
2024-02-01 10:20:00    2
2024-02-04 10:35:00    2
2024-02-16 20:00:00    2
2024-01-05 13:45:00    2
2024-02-01 08:30:00    2
2024-02-01 17:00:00    2
2024-02-26 13:25:00    2
2024-01-21 12:05:00    2
2024-02-26 17:10:00    2
2024-02-06 11:10:00    2
2024-02-15 08:00:00    2
2024-02-27 06:45:00    2
2024-02-28 09:35:00    2
2024-01-18 19:05:00    2
2024-02-06 01:45:00    2
2024-01-19 15:30:00    2
2024-01-20 12:10:00    2
2024-01-21 12:10:00    2
2024-01-29 12:25:00    2
07.01.2024             2
2024-02-03 20:40:00    2
2024-01-29 08:35:00    2
2024-02-21 12:50:00    2
2024-01-23 15:30:00    2
2024-02-20 17:55:00    2
2024-02-23 19:35:00    2
2024-01-23 09:15:00    2
2024-01-25 20:05:00    2
2024-01-02 05:45:00    2
2024-01-22 15:45:00    2
01-01-24               2
2024-02-28 18:00:00    2
2024/02/06             2
2024-02-18 23:15:00    2
2024-02-03 20:15:00    2
2024-01-06 08:40:00    2
2024-02-02 10:00:00    2
2024-02-02 13:30:00    2
2024-02-24 06:00:00    2
2024-02-22 19:40:00    2
2024-01-03 09:10:00    2
2024-01-15 09:30:00    2
2024-01-04 06:00:00    2
2024-02-04 10:20:00    2
2024-01-04 13:05:00    2
2024-02-17 18:30:00    2
2024-01-31 17:15:00    2
2024-01-07 17:20:00    2
2024-02-24 17:00:00    2
2024-02-10 11:30:00    2
2024-02-08 06:10:00    2
2024-01-03 09:25:00    2
2024-02-12 20:50:00    2
2024-02-20 18:00:00    2
2024-01-08 15:35:00    2
29.01.2024             2
2024-02-06 10:15:00    2
2024-02-16 16:55:00    2
2024-02-20 08:50:00    2
2024-02-16 07:55:00    2
2024-01-03 13:40:00    2
2024-02-17 15:06:00    2
2024-01-06 07:25:00    2
2024-01-05 18:55:00    2
2024-02-09 16:40:00    2
2024-01-03 19:40:00    2
2024-01-05 09:35:00    2
2024-02-08 13:35:00    2
2024-01-21 12:40:00    2
2024-01-16 10:15:00    2
2024-02-13 06:45:00    2
2024-01-22 17:50:00    2
2024-02-04 19:45:00    2
2024-01-01 17:45:00    2
2024-01-14 20:40:00    2
2024-01-04 09:24:00    2
2024/02/12             2
25.01.2024             2
2024-01-04 08:10:00    2
2024-01-28 07:50:00    2
2024-02-18 07:00:00    2
2024-02-11 13:30:00    2
2024-02-20 10:30:00    2
27.02.2024             2
2024-01-12 08:00:00    2
2024-01-10 13:25:00    2
2024-02-01 17:50:00    2
gen 20 2024            2
2024-02-23 19:05:00    2
2024-01-21 13:30:00    2
2024-01-22 10:35:00    2
2024-02-21 13:00:00    2
2024-01-20 10:20:00    2
12-01-24               2
2024-01-05 20:45:00    2
2024-02-20 14:20:00    2
2024-01-30 21:15:00    2
2024-02-22 17:45:00    2
2024-02-20 09:20:00    2
2024-01-31 21:00:00    2
2024-02-22 11:35:00    2
2024-01-13 10:05:00    2
2024-01-13 17:55:00    2
2024-02-23 13:40:00    2
2024-01-17 17:40:00    2
2024-01-04 07:55:00    2
2024-02-22 18:00:00    2
2024-02-04 20:45:00    2
2024-02-24 08:00:00    2
2024-02-17 16:00:00    2
2024-02-02 22:40:00    2
2024-02-25 21:10:00    2
2024-01-08 06:10:00    2
2024-01-29 12:35:00    2
2024-01-22 18:40:00    2
2024-02-13 09:00:00    2
2024-01-15 10:00:00    2
2024-02-18 03:45:00    2
2024-01-05 22:10:00    2
2024-01-17 18:20:00    2
2024-02-12 11:45:00    2
2024-01-29 17:35:00    2
2024-01-04 11:45:00    2
2024-02-20 07:50:00    2
2024-02-01 08:55:00    2
2024-01-22 08:50:00    2
2024-01-23 11:10:00    2
2024-02-05 05:45:00    2
2024-01-06 10:05:00    2
2024-01-28 16:10:00    2
2024-01-13 08:10:00    2
2024-01-30 13:20:00    2
2024-02-19 21:50:00    2
2024-02-15 19:40:00    2
2024-01-16 09:25:00    2
2024-02-25 20:25:00    2
2024-01-05 12:35:00    2
2024-01-19 17:55:00    2
2024-02-20 13:30:00    2
2024-01-22 09:00:00    2
2024-01-28 07:00:00    2
09-01-24               2
2024-02-29 15:30:00    2
2024-01-01 11:15:00    2
2024-01-14 12:10:00    2
08.02.2024             2
2024-02-05 12:55:00    2
2024-01-20 08:20:00    2
2024/02/15             2
2024-01-07 18:35:00    2
2024-01-08 14:20:00    2
2024-02-02 17:50:00    2
2024-02-10 17:55:00    2
2024-01-04 09:35:00    2
2024-01-17 13:20:00    2
2024-02-07 11:25:00    2
2024-02-17 18:00:00    2
2024-02-10 14:55:00    2
2024-02-08 16:15:00    2
2024-02-25 12:35:00    2
2024-02-19 14:20:00    2
2024-02-19 09:35:00    2
2024-01-23 16:45:00    2
2024-02-05 10:35:00    2
2024-01-19 18:45:00    2
2024-02-02 20:10:00    2
26-02-24               2
2024-02-22 18:20:00    2
2024-01-28 18:00:00    2

In [167]:
mesi_ita = {
    "GEN": "01", "FEB": "02", "MAR": "03", "APR": "04",
    "MAG": "05", "GIU": "06", "LUG": "07", "AGO": "08",
    "SET": "09", "OTT": "10", "NOV": "11", "DIC": "12"
}

def normalizza_data(val):
    val = str(val).strip()

    # "GEN 06 2024" → "2024-01-06 00:00:00"
    for ita, num in mesi_ita.items():
        if val.startswith(ita + " "):
            parts = val.split(" ")
            return f"{parts[2]}-{num}-{parts[1].zfill(2)} 00:00:00"

    # "2024-01-05T12:35:00" → "2024-01-05 12:35:00"
    val = val.replace("T", " ")

    # "2024/02/26" o "2024/02/26 09:00:00" → "2024-02-26 00:00:00"
    if re.match(r"\d{4}/\d{2}/\d{2}", val):
        val = val.replace("/", "-")
        if len(val) == 10:
            val = val + " 00:00:00"

    # "05.01.2024" → "2024-01-05 00:00:00"
    match = re.match(r"(\d{2})\.(\d{2})\.(\d{4})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    # "04-01-24" → "2024-01-04 00:00:00"
    match = re.match(r"(\d{2})-(\d{2})-(\d{2})$", val)
    if match:
        return f"20{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    # "22/01/2024 15:45:00" → "2024-01-22 15:45:00"
    match = re.match(r"(\d{2})/(\d{2})/(\d{4})\s(\d{2}:\d{2}:\d{2})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} {match.group(4)}"

    return val

df1["DATA_PARTENZA"] = df1["DATA_PARTENZA"].apply(normalizza_data)
df1["DATA_PARTENZA"] = pd.to_datetime(df1["DATA_PARTENZA"], errors="coerce")


print("NaT left:", df1["DATA_PARTENZA"].isnull().sum())
print("Range date:", df1["DATA_PARTENZA"].min(), "→", df1["DATA_PARTENZA"].max())
print("Examples:")
print(df1["DATA_PARTENZA"].head(5).to_string())

NaT left: 129
Range date: 2023-12-31 00:00:00 → 2024-02-29 22:20:00
Examples:
0   2024-01-30 09:15:00
1   2024-02-03 13:15:00
2   2024-01-15 08:45:00
3   2024-02-02 08:40:00
4   2024-02-16 12:50:00

### Descr Aeroporto Arr

In [168]:
print(f"Unique values: {df1['DESCR_AEREOPORTO_ARR'].nunique()}")
print(f"Null values: {df1['DESCR_AEREOPORTO_ARR'].isnull().sum()}")
print()
print(df1['DESCR_AEREOPORTO_ARR'].value_counts(dropna=False).to_string())

Unique values: 31
Null values: 0

DESCR_AEREOPORTO_ARR
fiumicino               1272
malpensa                1185
orio al serio            464
venezia marco polo       356
guglielmo marconi        326
napoli capodichino       202
linate                   174
ciampino                 163
sandro pertini           151
galileo galilei          139
fontanarossa             114
verona villafranca       108
treviso-sant'angelo       82
firenze peretola          68
palese                    57
punta raisi               26
falconara                 24
cristoforo colombo        20
sant egidio               16
liberi                    15
ronchi dei legionari      14
miramare                  12
lamezia terme              9
parma                      7
elmas                      7
papola casale              6
levaldigi                  6
comiso                     3
bolzano                    2
costa smeralda             1
brescia montichiari        1

### Descr Aeroporto Part

In [169]:
print(f"Unique values: {df1['DESCR_AEREOPORTO_PART'].nunique()}")
print(f"Null values: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print()
print(df1['DESCR_AEREOPORTO_PART'].value_counts(dropna=False).to_string())

Unique values: 119
Null values: 109

DESCR_AEREOPORTO_PART
rinas mother teresa                                                  578
stansted                                                             472
london gatwick                                                       381
london heathrow                                                      364
havalimani                                                           284
dubai international                                                  142
cairo international                                                  126
sabiha gokcen                                                        125
manchester                                                           122
mohamed v                                                            120
NaN                                                                  109
hamad international                                                  102
menara                                                                98
john f kennedy international                                          94
sharm el-sheikh international                                         89
carthage                                                              83
abu dhabi international                                               74
nikola tesla                                                          73
london city                                                           68
newark liberty international                                          55
london luton                                                          55
chisinau international airport                                        54
king abdulaziz international                                          50
edinburgh                                                             48
sao paulo/guarulhos-governador andre franco montoro international     45
ben gurion international                                              44
bole international                                                    44
queen alia international                                              42
bristol                                                               41
birmingham international                                              38
n.d.                                                                  34
?                                                                     33
beijing capital international                                         32
sphinx international                                                  29
ezeiza ministro pistarini                                             29
                                                                      28
pu dong                                                               28
zvartnots                                                             28
//                                                                    27
incheon international                                                 26
-                                                                     26
indira gandhi international                                           26
houari boumediene                                                     24
nd                                                                    23
kuwait international                                                  23
taiwan taoyuan international                                          22
unknown                                                               22
changi                                                                21
seeb                                                                  19
king khaled international                                             19
petrovec                                                              17
east midlands                                                         17
shenzhen                                                              16
hartsfield-jackson atlanta international                              16
galeao-antonio carlos jobim international                             16
male international                                                    15
heydar aliyev international                                           15
miami international                                                   15
marsa alam international                                              14
newcastle                                                             13
wenzhou                                                               12
montreal-pierre elliott trudeau international                         12
bahrain international                                                 12
sharjah                                                               12
kopitnari                                                             12
imam khomeini international                                           11
blaise diagne international                                           11
golubovci                                                             11
philadelphia international                                            11
tokyo international (haneda)                                          10
saiss                                                                  9
casa de campo international                                            9
hurghada international                                                 9
glasgow international                                                  9
benito juarez international                                            8
dallas/fort worth international                                        8
moi international                                                      8
al maktoum international                                               8
ibn batouta                                                            7
amilcar cabral international                                           7
farnborough                                                            7
hong kong international                                                7
prishtina international                                                7
beirut-rafic hariri international                                      7
london biggin hill                                                     7
hangzhou                                                               6
lester b pearson international                                         6
washington dulles international                                        6
kisauni                                                                5
lukou international                                                    5
liverpool john lennon                                                  5
tbilisi international                                                  5
adnan menderes                                                         5
zhengzhou                                                              4
mitiga                                                                 4
agadir almassira                                                       4
king fahd international                                                4
tianfu international                                                   4
raja sansi                                                             3
chongqing jiangbei international                                       3
belfast international                                                  3
sale                                                                   3
logan international                                                    3
luxor international                                                    3
new baiyun                                                             3
salalah                                                                3
sir seewoosagur ramgoolam int                                          2
cancun international                                                   2
leeds/bradford                                                         2
yuzhny                                                                 2
sangster international                                                 2
london oxford                                                          1
almaty                                                                 1
n/a                                                                    1
null                                                                   1
ataturk international                                                  1
lydd                                                                   1
raf northolt                                                           1
oakland international                                                  1
los angeles international                                              1

The column contained 3 types of issues:

1. **167 rows with extra whitespace** — fixed with `.str.strip()`

2. **83 placeholder values** — values such as `"n.d."`, `"nd"`, `"unknown"`, `"null"`
   that carry no real information but were written as text instead of
   being left empty. Converted to `pd.NA` using `.replace()`.

3. **109 original nulls** — empty cells already present in the dataset.

Points 2 and 3 brought the total null count to 192 (3.8% of rows).
All 192 were **recovered** using the IATA code present in the
`AREOPORTO_PARTENZA` column: through an IATA → full airport name
lookup table, each null was replaced with the correct name in lowercase
(e.g. `"STN"` → `"stansted"`, `"LHR"` → `"london heathrow"`).

**Final result: 0 nulls, 133 unique values, all lowercase.**

In [170]:
# ── Dizionario IATA → nome descrittivo ───────────────────────────────────────

PLACEHOLDER_NULL = {'n.d.', '?', '', '//', '-', 'unknown', 'nd', 'n/a', 'null', 'anu', 'none'}

# Prendo solo le righe dove il nome descrittivo è valido (non placeholder)
df1_validi = df1[~df1['DESCR_AEREOPORTO_PART'].isin(PLACEHOLDER_NULL) & df1['DESCR_AEREOPORTO_PART'].notna()]

iata_to_name = (
    df1_validi
    .groupby('AREOPORTO_PARTENZA')['DESCR_AEREOPORTO_PART']
    .agg(lambda x: x.mode()[0])
    .to_dict()
)

print(f"✅ Dizionario creato: {len(iata_to_name)} aeroporti mappati")

df1['DESCR_AEREOPORTO_PART'] = df1['DESCR_AEREOPORTO_PART'].apply(
    lambda x: np.nan if str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulli dopo sostituzione placeholder: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")

df1['DESCR_AEREOPORTO_PART'] = df1.apply(
    lambda row: iata_to_name.get(row['AREOPORTO_PARTENZA'], row['AREOPORTO_PARTENZA'])
    if pd.isna(row['DESCR_AEREOPORTO_PART'])
    else row['DESCR_AEREOPORTO_PART'],
    axis=1
)

print(f"Nulli rimasti: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print(df1['DESCR_AEREOPORTO_PART'].value_counts(dropna=False).to_string())

✅ Dizionario creato: 111 aeroporti mappati
Nulli dopo sostituzione placeholder: 304
Nulli rimasti: 0
DESCR_AEREOPORTO_PART
rinas mother teresa                                                  612
stansted                                                             502
london gatwick                                                       401
london heathrow                                                      387
havalimani                                                           300
dubai international                                                  153
cairo international                                                  133
sabiha gokcen                                                        132
mohamed v                                                            130
manchester                                                           129
hamad international                                                  105
menara                                                               105
john f kennedy international                                         104
sharm el-sheikh international                                         95
carthage                                                              86
nikola tesla                                                          81
abu dhabi international                                               77
london city                                                           73
newark liberty international                                          63
chisinau international airport                                        58
london luton                                                          58
king abdulaziz international                                          52
sao paulo/guarulhos-governador andre franco montoro international     51
edinburgh                                                             50
bristol                                                               46
queen alia international                                              46
bole international                                                    46
ben gurion international                                              45
birmingham international                                              41
beijing capital international                                         35
ezeiza ministro pistarini                                             31
zvartnots                                                             31
sphinx international                                                  30
pu dong                                                               30
incheon international                                                 28
indira gandhi international                                           27
taiwan taoyuan international                                          25
houari boumediene                                                     25
kuwait international                                                  23
changi                                                                22
king khaled international                                             21
seeb                                                                  20
east midlands                                                         18
petrovec                                                              17
male international                                                    17
shenzhen                                                              17
galeao-antonio carlos jobim international                             17
hartsfield-jackson atlanta international                              16
miami international                                                   16
heydar aliyev international                                           15
newcastle                                                             15
marsa alam international                                              15
sharjah                                                               15
wenzhou                                                               13
bahrain international                                                 13
imam khomeini international                                           12
blaise diagne international                                           12
montreal-pierre elliott trudeau international                         12
kopitnari                                                             12
golubovci                                                             11
philadelphia international                                            11
benito juarez international                                           10
glasgow international                                                 10
tokyo international (haneda)                                          10
saiss                                                                  9
casa de campo international                                            9
hurghada international                                                 9
amilcar cabral international                                           9
moi international                                                      9
hong kong international                                                8
ibn batouta                                                            8
dallas/fort worth international                                        8
prishtina international                                                8
london biggin hill                                                     8
al maktoum international                                               8
farnborough                                                            7
beirut-rafic hariri international                                      7
hangzhou                                                               6
lester b pearson international                                         6
liverpool john lennon                                                  6
tbilisi international                                                  6
washington dulles international                                        6
adnan menderes                                                         6
kisauni                                                                5
lukou international                                                    5
zhengzhou                                                              4
raja sansi                                                             4
sale                                                                   4
mitiga                                                                 4
agadir almassira                                                       4
king fahd international                                                4
tianfu international                                                   4
chongqing jiangbei international                                       3
belfast international                                                  3
logan international                                                    3
luxor international                                                    3
new baiyun                                                             3
salalah                                                                3
sir seewoosagur ramgoolam int                                          2
cancun international                                                   2
leeds/bradford                                                         2
yuzhny                                                                 2
sangster international                                                 2
london oxford                                                          1
almaty                                                                 1
anu                                                                    1
ataturk international                                                  1
lydd                                                                   1
raf northolt                                                           1
oakland international                                                  1
los angeles international                                              1

### Città Arrivo

In [171]:
print(f"Unique values: {df1['CITTA_ARR'].nunique()}")
print(f"Null values: {df1['CITTA_ARR'].isnull().sum()}")
print()
print(df1['CITTA_ARR'].value_counts(dropna=False).to_string())

Unique values: 29
Null values: 0

CITTA_ARR
roma             1435
milano           1359
bergamo           464
venezia           356
bologna           326
napoli            202
torino            151
pisa              139
catania           114
verona            108
treviso            82
firenze            68
bari               57
palermo            26
ancona             24
genova             20
perugia            16
pescara            15
trieste            14
rimini             12
lamezia terme       9
parma               7
cagliari            7
brindisi            6
cuneo               6
comiso              3
bolzano             2
olbia               1
brescia             1

### Città Partenza

In [172]:
print(f"Unique values: {df1['CITTA_PARTENZA'].nunique()}")
print(f"Null values: {df1['CITTA_PARTENZA'].isnull().sum()}")
print()
print(df1['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 110
Null values: 100

CITTA_PARTENZA
londra               1362
tirana                582
istanbul              408
dubai                 152
cairo                 125
manchester            124
casablanca            120
marrakech             102
NaN                   100
doha                   99
new york               99
sharm el sheikh        88
tunis                  81
belgrado               80
abu dhabi              73
newark                 57
chisinau               55
jeddah                 50
edinburgh              50
san paolo              48
bristol                45
tel aviv yafo          44
amman                  43
addis ababa            41
birmingham             38
pechino                34
n.d.                   31
yerevan                30
buenos aires           29
shanghai               29
seoul                  28
giza                   27
nuova delhi            26
algeri                 25
taipei                 24
?                      23
nd                     23
kuwait city            22
                       22
-                      21
singapore              20
muscat                 20
riyadh                 20
derby                  18
male                   17
//                     16
unknown                15
shenzhen               15
newcastle              15
atlanta                15
miami                  15
rio de janeiro         15
baku                   14
sharjah                14
skopie                 13
wenzhou                13
marsa alam             13
dakar                  12
montreal               12
manama                 12
kutaisi                12
tehran                 11
podgorica              10
filadelfia             10
tokyo                  10
fes                     9
la romana               9
hurghada                9
sal                     9
citta del messico       9
mombasa                 9
glasgow                 9
hong kong               8
tangier                 8
dallas-fort worth       8
pristina                7
hangzhou                6
farnborough             6
toronto                 6
beirut                  6
liverpool               6
tbilisi                 6
washington              6
smirne                  6
nanjing                 5
zhengzhou               4
zanzibar                4
amritsar                4
rabat                   4
tripoli                 4
agadir                  4
dammam                  4
chengdu                 4
chongqing               3
belfast                 3
boston                  3
luxor                   3
guangzhou               3
plaisance               2
cancun                  2
leeds                   2
tashkent                2
montego bay             2
salalah                 2
oxford                  1
almaty                  1
st. john's              1
lydd                    1
northolt                1
oakland                 1
los angeles             1

In [173]:
# Recover nulls via IATA → city lookup
iata_city = {
    "tia": "tirana",   "stn": "londra",    "lgw": "londra",   "lhr": "londra",
    "lcy": "londra",   "ltn": "londra",    "bqh": "londra",   "fab": "londra",
    "ist": "istanbul", "dxb": "dubai",     "cai": "il cairo", "saw": "istanbul",
    "cmn": "casablanca","doh": "doha",      "rak": "marrakech","jfk": "new york",
    "ssh": "sharm el-sheikh","tun": "tunisi","beg": "belgrado","auh": "abu dhabi",
    "ewr": "new york", "jed": "jeddah",    "edi": "edinburgo","gru": "san paolo",
    "eze": "buenos aires","add": "addis abeba","mex": "citta del messico",
    "pek": "pechino",  "rmo": "chisinau",  "bhx": "birmingham","pvg": "shanghai",
    "hkg": "hong kong","mct": "muscat",    "mle": "male",     "rba": "rabat",
    "evn": "yerevan",  "tbs": "tbilisi",   "ema": "east midlands","ruh": "riad",
    "shj": "sharjah",  "gla": "glasgow",   "icn": "seul",     "rmf": "marsa alam",
    "tng": "tangeri",  "sid": "praia",     "spx": "cairo",    "ika": "teheran",
    "prn": "pristina", "mba": "mombasa",   "szx": "shenzhen", "mia": "miami",
    "tpe": "taipei",   "sin": "singapore", "tlv": "tel aviv", "amm": "amman",
    "brs": "bristol",  "man": "manchester","anu": "saint john's","ncl": "newcastle",
    "del": "nuova delhi","atl": "atlanta", "kwi": "kuwait",   "dfw": "dallas",
    "iad": "washington","yul": "montreal", "yyz": "toronto",  "hnd": "tokyo",
    "bey": "beirut",   "alg": "algeri",    "kiv": "chisinau", "gyd": "baku",
    "lpl": "liverpool","skp": "skopje",    "tgd": "podgorica","phl": "filadelfia",
    "fez": "fez",      "gig": "rio de janeiro","atq": "amritsar","znz": "zanzibar",
    "nkg": "nanchino", "aga": "agadir",    "mji": "misurata", "dmm": "dammam",
    "ckg": "chongqing","bfs": "belfast",   "bos": "boston",   "lxr": "luxor",
    "can": "guangzhou","wnz": "wenzhou",   "hgh": "hangzhou", "bah": "manama",
    "dss": "dakar",    "kut": "kutaisi",   "hrg": "hurghada", "lrm": "al marj",
    "oak": "oakland",  "lax": "los angeles","oxf": "oxford",  "lba": "leeds",
    "ala": "almaty",   "isl": "islamabad", "lyx": "marsa matruh","nht": "londra",
    "mbj": "montego bay","cun": "cancun",  "mru": "port louis","tas": "tashkent",
    "sll": "freetown", "cgo": "zhengzhou", "tfu": "chengdu",  "lyx": "marsa matruh",
}

null_mask = df1["CITTA_PARTENZA"].isnull()
df1.loc[null_mask, "CITTA_PARTENZA"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"]
    .str.strip().str.lower()
    .map(iata_city)
)

print(f"Null left: {df1['CITTA_PARTENZA'].isnull().sum()}")
print(f"Unique values: {df1['CITTA_PARTENZA'].nunique()}")

print(df1['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

Null left: 0
Unique values: 115
CITTA_PARTENZA
londra               1392
tirana                596
istanbul              417
dubai                 155
cairo                 125
manchester            125
casablanca            123
marrakech             104
new york              102
doha                  100
sharm el sheikh        88
tunis                  81
belgrado               80
abu dhabi              74
chisinau               57
newark                 57
jeddah                 51
san paolo              50
edinburgh              50
bristol                46
tel aviv yafo          44
amman                  44
addis ababa            41
birmingham             40
pechino                34
n.d.                   31
buenos aires           31
yerevan                31
shanghai               30
seoul                  28
giza                   27
nuova delhi            26
taipei                 25
algeri                 25
?                      23
nd                     23
kuwait city            22
                       22
singapore              21
-                      21
muscat                 20
riyadh                 20
derby                  18
male                   17
atlanta                16
miami                  16
//                     16
unknown                15
shenzhen               15
newcastle              15
rio de janeiro         15
baku                   14
marsa alam             14
sharjah                14
skopie                 13
wenzhou                13
manama                 13
dakar                  12
montreal               12
kutaisi                12
tehran                 11
podgorica              11
filadelfia             11
glasgow                10
tokyo                  10
fes                     9
la romana               9
hurghada                9
sal                     9
citta del messico       9
mombasa                 9
hong kong               8
tangier                 8
dallas-fort worth       8
pristina                7
hangzhou                6
farnborough             6
toronto                 6
beirut                  6
liverpool               6
tbilisi                 6
washington              6
smirne                  6
zanzibar                5
nanjing                 5
zhengzhou               4
amritsar                4
rabat                   4
tripoli                 4
addis abeba             4
agadir                  4
dammam                  4
chengdu                 4
chongqing               3
belfast                 3
boston                  3
luxor                   3
guangzhou               3
il cairo                2
plaisance               2
cancun                  2
tunisi                  2
leeds                   2
tashkent                2
montego bay             2
salalah                 2
skopje                  1
oxford                  1
almaty                  1
st. john's              1
lydd                    1
sharm el-sheikh         1
northolt                1
oakland                 1
los angeles             1

### Codice Paese Arrivo / Partenza

In [174]:
print("--- CODICE_PAESE_ARR ---")
print(f"Unique: {df1['CODICE_PAESE_ARR'].nunique()}  |  Null: {df1['CODICE_PAESE_ARR'].isnull().sum()}")
print(df1['CODICE_PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- CODICE_PAESE_PART ---")
print(f"Unique: {df1['CODICE_PAESE_PART'].nunique()}  |  Null: {df1['CODICE_PAESE_PART'].isnull().sum()}")
print(df1['CODICE_PAESE_PART'].value_counts(dropna=False).to_string())

--- CODICE_PAESE_ARR ---
Unique: 8  |  Null: 0
CODICE_PAESE_ARR
ita    4690
it      248
fra      25
gbr      18
esp      18
tur      17
deu      13
gb        1

--- CODICE_PAESE_PART ---
Unique: 67  |  Null: 54
CODICE_PAESE_PART
gbr        1626
alb         550
tur         407
egy         259
mar         251
are         234
usa         215
chn         116
qat         101
tun          83
srb          79
gb           78
sau          75
bra          66
mda          58
NaN          54
eth          46
jor          45
isr          43
al           35
arg          30
arm          29
ind          27
kor          26
dza          25
tr           24
unknown      24
twn          23
sgp          22
omn          22
kwt          22
mkd          17
eg           17
can          17
geo          17
mdv          16
             15
aze          15
nd           14
n.d.         13
bhr          13
//           13
irn          12
?            12
sen          12
mex          12
ae           12
mne          11
ken           9
-             9
jpn           9
hkg           8
dom           8
cpv           8
ma            7
rks           7
lbn           6
tza           5
xx            5
lby           4
mus           2
eu            2
uzb           2
jam           2
00            1
kaz           1
atg           1
zz            1

In [175]:
# Cross-check: AREOPORTO_ARRIVO contains only Italian airports, so CODICE_PAESE_ARR
# must be Italy for every row. Any non-"ita" value is a data-entry error.
# We overwrite the entire column rather than mapping variants, since the ground
# truth (Italian arrival airport) is unambiguous.

n_wrong = (df1["CODICE_PAESE_ARR"] != "ita").sum()
print(f"Rows with non-'ita' value before fix: {n_wrong}")
if n_wrong > 0:
    print(df1.loc[df1["CODICE_PAESE_ARR"] != "ita", "CODICE_PAESE_ARR"].value_counts().to_string())

df1["CODICE_PAESE_ARR"] = "ita"

print(f"\nUnique values after fix: {df1['CODICE_PAESE_ARR'].nunique()}")
print(df1["CODICE_PAESE_ARR"].value_counts().to_string())

# CODICE_PAESE_PART: recover nulls using IATA → ISO-3 country code lookup.
iata_country_code = {
    "tia": "alb", "stn": "gbr", "lgw": "gbr", "lhr": "gbr", "lcy": "gbr",
    "ltn": "gbr", "bqh": "gbr", "fab": "gbr", "nht": "gbr", "lpl": "gbr",
    "ncl": "gbr", "edi": "gbr", "bhx": "gbr", "gla": "gbr", "bfs": "gbr",
    "lba": "gbr", "ema": "gbr", "brs": "gbr", "man": "gbr", "oxf": "gbr",
    "ist": "tur", "saw": "tur", "adb": "tur",
    "dxb": "are", "shj": "are", "auh": "are", "dwc": "are",
    "cai": "egy", "ssh": "egy", "hrg": "egy", "lxr": "egy", "rmf": "egy",
    "cmn": "mar", "rak": "mar", "tng": "mar", "fez": "mar", "aga": "mar", "rba": "mar",
    "doh": "qat",
    "jfk": "usa", "ewr": "usa", "mia": "usa", "atl": "usa", "dfw": "usa",
    "iad": "usa", "bos": "usa", "phl": "usa", "oak": "usa", "lax": "usa",
    "tun": "tun", "beg": "srb",
    "jed": "sau", "ruh": "sau", "dmm": "sau",
    "gru": "bra", "gig": "bra",
    "eze": "arg", "add": "eth",
    "mex": "mex", "cun": "mex",
    "pek": "chn", "pvg": "chn", "szx": "chn", "can": "chn", "wnz": "chn",
    "hgh": "chn", "nkg": "chn", "cgo": "chn", "tfu": "chn", "ckg": "chn",
    "rmo": "mda", "kiv": "mda",
    "hkg": "hkg", "mct": "omn", "mle": "mdv", "evn": "arm",
    "tbs": "geo", "kut": "geo", "icn": "kor", "sid": "cpv", "spx": "egy",
    "ika": "irn", "prn": "xkx", "mba": "ken", "znz": "tza",
    "tpe": "twn", "sin": "sgp", "tlv": "isr", "amm": "jor",
    "del": "ind", "atq": "ind", "kwi": "kwt",
    "yul": "can", "yyz": "can", "hnd": "jpn", "bey": "lbn", "alg": "dza",
    "gyd": "aze", "skp": "mkd", "tgd": "mne", "anu": "atg", "dss": "sen",
    "bah": "bhr", "lrm": "lby", "mji": "lby", "mbj": "jam", "mru": "mus",
    "tas": "uzb", "sll": "sle", "ala": "kaz", "isl": "pak",
}

null_mask = df1["CODICE_PAESE_PART"].isnull()
df1.loc[null_mask, "CODICE_PAESE_PART"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"]
    .str.strip().str.lower()
    .map(iata_country_code)
)

print(f"\nNull left CODICE_PAESE_PART: {df1['CODICE_PAESE_PART'].isnull().sum()}")
print(df1['CODICE_PAESE_PART'].value_counts(dropna=False).head(15).to_string())

Rows with non-'ita' value before fix: 340
CODICE_PAESE_ARR
it     248
fra     25
gbr     18
esp     18
tur     17
deu     13
gb       1

Unique values after fix: 1
CODICE_PAESE_ARR
ita    5030

Null left CODICE_PAESE_PART: 0
CODICE_PAESE_PART
gbr    1648
alb     559
tur     411
egy     262
mar     251
are     236
usa     219
chn     118
qat     102
tun      83
srb      80
gb       78
sau      75
bra      67
mda      58

### Paese Arrivo / Partenza

In [176]:
print("--- PAESE_ARR ---")
print(f"Unique: {df1['PAESE_ARR'].nunique()}  |  Null: {df1['PAESE_ARR'].isnull().sum()}")
print(df1['PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- PAESE_PART ---")
print(f"Unique: {df1['PAESE_PART'].nunique()}  |  Null: {df1['PAESE_PART'].isnull().sum()}")
print(df1['PAESE_PART'].value_counts(dropna=False).to_string())

--- PAESE_ARR ---
Unique: 1  |  Null: 0
PAESE_ARR
italia    5030

--- PAESE_PART ---
Unique: 57  |  Null: 74
PAESE_PART
regno unito              1694
albania                   587
turchia                   421
egitto                    267
marocco                   253
emirati arabi uniti       243
stati uniti               220
cina                      117
qatar                     101
tunisia                    81
serbia                     80
arabia saudita             76
NaN                        74
brasile                    63
moldavia                   56
giordania                  45
etiopia                    44
israele                    42
argentina                  30
india                      29
armenia                    28
corea del sud              27
algeria                    24
taiwan                     22
kuwait                     22
singapore                  21
oman                       21
nd                         21
//                         21
?                          20
n.d.                       18
unknown                    18
macedonia                  17
maldive                    17
-                          17
canada                     17
georgia                    17
azerbaigian                14
                           14
bahrain                    13
senegal                    12
messico                    12
montenegro                 11
giappone                   10
iran                        9
repubblica dominicana       9
capo verde                  9
kenya                       9
hong kong                   8
libano                      7
cossovo                     6
tanzania                    5
libia                       3
mauritius                   2
uzbekistan                  2
giamaica                    2
kazakistan                  1
antigua e barbuda           1

In [177]:
# PAESE_ARR: always Italy — no action needed.
# PAESE_PART: recover nulls using ISO-3 code already filled in CODICE_PAESE_PART.
codice_paese_map = {
    "alb": "albania",          "gbr": "regno unito",      "tur": "turchia",
    "are": "emirati arabi",    "egy": "egitto",            "mar": "marocco",
    "qat": "qatar",            "usa": "stati uniti",       "tun": "tunisia",
    "srb": "serbia",           "sau": "arabia saudita",    "bra": "brasile",
    "arg": "argentina",        "eth": "etiopia",           "mex": "messico",
    "chn": "cina",             "mda": "moldavia",          "hkg": "hong kong",
    "omn": "oman",             "mdv": "maldive",           "arm": "armenia",
    "geo": "georgia",          "kor": "corea del sud",     "cpv": "capo verde",
    "irn": "iran",             "xkx": "kosovo",            "ken": "kenya",
    "tza": "tanzania",         "twn": "taiwan",            "sgp": "singapore",
    "isr": "israele",          "jor": "giordania",         "ind": "india",
    "kwt": "kuwait",           "can": "canada",            "jpn": "giappone",
    "lbn": "libano",           "dza": "algeria",           "aze": "azerbaigian",
    "mkd": "macedonia",        "mne": "montenegro",        "atg": "antigua",
    "sen": "senegal",          "bhr": "bahrein",           "lby": "libia",
    "jam": "giamaica",         "mus": "mauritius",         "uzb": "uzbekistan",
    "sle": "sierra leone",     "kaz": "kazakistan",        "pak": "pakistan",
}

null_mask = df1["PAESE_PART"].isnull()
df1.loc[null_mask, "PAESE_PART"] = (
    df1.loc[null_mask, "CODICE_PAESE_PART"]
    .str.strip().str.lower()
    .map(codice_paese_map)
)

print(f"Null left PAESE_PART: {df1['PAESE_PART'].isnull().sum()}")
print(df1['PAESE_PART'].value_counts(dropna=False).head(15).to_string())

Null left PAESE_PART: 4
PAESE_PART
regno unito            1714
albania                 595
turchia                 429
egitto                  272
marocco                 254
emirati arabi uniti     243
stati uniti             225
cina                    119
qatar                   102
tunisia                  82
serbia                   81
arabia saudita           76
brasile                  64
moldavia                 56
giordania                46

### Zona

In [178]:
print(f"Unique values: {df1['ZONA'].nunique()}")
print(f"Null values: {df1['ZONA'].isnull().sum()}")
print()
print(df1['ZONA'].value_counts(dropna=False).sort_index().to_string())

Unique values: 12
Null values: 0

ZONA
-1       3
1      177
10       1
2     1821
4      559
5     1457
6      210
7      143
8      575
9       78
99       1
??       5

In [179]:
# -1 is not a valid zone — treat it as missing before casting to integer.
df1["ZONA"] = df1["ZONA"].replace("-1", np.nan)
df1["ZONA"] = pd.to_numeric(df1["ZONA"], errors="coerce")
df1.loc[df1["ZONA"] == -1, "ZONA"] = np.nan   # catch numeric -1 if already parsed
df1["ZONA"] = df1["ZONA"].astype(pd.Int64Dtype())

print(f"Null left (were -1): {df1['ZONA'].isnull().sum()}")
print(f"dtype: {df1['ZONA'].dtype}")
print(df1["ZONA"].value_counts(dropna=False).sort_index().to_string())

Null left (were -1): 8
dtype: Int64
ZONA
1        177
2       1821
4        559
5       1457
6        210
7        143
8        575
9         78
10         1
99         1
<NA>       8

### TOT

In [180]:
print(f"Unique values: {df1['TOT'].nunique()}")
print(f"Null values: {df1['TOT'].isnull().sum()}")
print()
print(df1['TOT'].value_counts(dropna=False).head(20).to_string())

Unique values: 348
Null values: 0

TOT
1       2351
2        174
3        148
4        113
7         84
5         83
8         75
6         68
10        50
9         47
0         41
?         40
15        40
n.d.      35
16        34
12        32
11        32
14        31
18        28
13        27

In [181]:
# Cast to integer.
df1["TOT"] = pd.to_numeric(df1["TOT"], errors="coerce").astype(pd.Int64Dtype())

print(f"Null left: {df1['TOT'].isnull().sum()}")
print(f"dtype: {df1['TOT'].dtype}")
print(f"Min: {df1['TOT'].min()}  |  Max: {df1['TOT'].max()}  |  Mean: {df1['TOT'].mean():.1f}")

TypeError: cannot safely cast non-equivalent float64 to int64

### Motivo Allarme

In [ ]:
print(f"Unique values: {df1['MOTIVO_ALLARME'].nunique()}")
print(f"Null values: {df1['MOTIVO_ALLARME'].isnull().sum()}")
print()
print(df1['MOTIVO_ALLARME'].value_counts(dropna=False).to_string())

In [ ]:
# Standardise category labels.
motivo_map = {
    "sdi"      : "sdi",
    "nsis"     : "nsis",
    "sdi/nsis" : "sdi/nsis",
    "tsc"      : "tsc",
    "interpol" : "interpol",
    "bcs"      : "bcs",
    "manuale"  : "manuale",
}

df1["MOTIVO_ALLARME"] = df1["MOTIVO_ALLARME"].map(lambda x: motivo_map.get(str(x).strip(), np.nan) if pd.notna(x) else np.nan)

print(f"Null left: {df1['MOTIVO_ALLARME'].isnull().sum()}")
print(df1["MOTIVO_ALLARME"].value_counts(dropna=False).to_string())

### Note Operatore

In [ ]:
print(f"Unique values: {df1['note_operatore'].nunique()}")
print(f"Null values: {df1['note_operatore'].isnull().sum()}  ({df1['note_operatore'].isnull().mean()*100:.1f}%)")
print()
print(df1['note_operatore'].value_counts(dropna=False).head(15).to_string())

### Flag Rischio

In [ ]:
print(f"Unique values: {df1['flag_rischio'].nunique()}")
print(f"Null values: {df1['flag_rischio'].isnull().sum()}  ({df1['flag_rischio'].isnull().mean()*100:.1f}%)")
print()
print(df1['flag_rischio'].value_counts(dropna=False).to_string())

### Colonne Duplicate

In [ ]:
# The duplicate columns may use different formatting (case, punctuation, encoding)
# from their cleaned counterparts. Normalise both sides before comparing.

def norm_str(s):
    """Lowercase, strip whitespace and trailing dots; treat null-like strings as empty."""
    if pd.isna(s):
        return ""
    s = str(s).strip().lower().rstrip(".")
    return "" if s in {"nan", "none", "n/a", "nd", "n.d.", "<na>"} else s

str_checks = [
    ("Paese Partenza",   "PAESE_PART"),
    ("CODICE PAESE ARR", "CODICE_PAESE_ARR"),
    ("paese%arr",        "PAESE_ARR"),
]

for dup, orig in str_checks:
    nd = df1[dup].map(norm_str)
    no = df1[orig].map(norm_str)
    n_mismatch = (nd != no).sum()
    print(f"'{dup}' ~= '{orig}':  {n_mismatch} mismatches out of {len(df1)}")
    if n_mismatch > 0 and n_mismatch <= 10:
        print(df1.loc[nd != no, [dup, orig]].to_string())
    elif n_mismatch > 10:
        print("  sample differences:")
        print(df1.loc[nd != no, [dup, orig]].head(5).to_string())

# Numeric check: tot voli (str) vs TOT (Int64)
n_mismatch_tot = (
    pd.to_numeric(df1["tot voli"], errors="coerce") != df1["TOT"].astype(float)
).sum()
print(f"\n'tot voli' ~= 'TOT':  {n_mismatch_tot} mismatches")

# Integer check: 3zona (int64) vs ZONA (Int64, -1 → NaN)
# For rows where ZONA is NA (was -1), '3zona' should have -1 → skip those
valid = df1["ZONA"].notna()
n_mismatch_zona = (df1.loc[valid, "3zona"] != df1.loc[valid, "ZONA"].astype(int)).sum()
na_zona = (~valid).sum()
print(f"'3zona' ~= 'ZONA':  {n_mismatch_zona} mismatches on valid rows  ({na_zona} rows had -1 → NaN)")

In [ ]:
# Drop the duplicate columns.
cols_to_drop = ["Paese Partenza", "CODICE PAESE ARR", "3zona", "paese%arr", "tot voli"]
df1.drop(columns=cols_to_drop, inplace=True)

print(f"Remaining columns ({df1.shape[1]}):")
print(df1.columns.tolist())

# Tipologia Viaggiatore Dataset

First general look at the dataset (df2)

In [ ]:
df2.shape

(5095, 33)

In [ ]:
df2.head(5)

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571

In [ ]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5095 entries, 0 to 5094
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NAZIONALITA            4979 non-null   str
 1   AREOPORTO_ARRIVO       5095 non-null   str
 2   AREOPORTO_PARTENZA     5095 non-null   str
 3   ANNO_PARTENZA          5095 non-null   str
 4   MESE_PARTENZA          5095 non-null   str
 5   GIORNO_PARTENZA        5095 non-null   int64
 6   DATA_PARTENZA          5095 non-null   str
 7   DESCR_AEREOPORTO_ARR   5095 non-null   str
 8   DESCR_AEREOPORTO_PART  5095 non-null   str
 9   CITTA_ARR              5095 non-null   str
 10  CITTA_PARTENZA         5095 non-null   str
 11  CODICE_PAESE_ARR       5095 non-null   str
 12  CODICE_PAESE_PART      5095 non-null   str
 13  PAESE_ARR              5095 non-null   str
 14  PAESE_PART             5095 non-null   str
 15  ZONA                   5095 non-null   str
 16  ENTRATI                5095 non-null   str
 17  INVESTIGATI            5095 non-null   str
 18  ALLARMATI              5095 non-null   str
 19  TIPO_DOCUMENTO         5033 non-null   str
 20  GENERE                 5050 non-null   str
 21  FASCIA_ETA             5095 non-null   str
 22  FLAG_TRANSITO          5095 non-null   str
 23  COMPAGNIA_AEREA        5008 non-null   str
 24  NUMERO_VOLO            5025 non-null   str
 25  ESITO_CONTROLLO        3806 non-null   str
 26  note_operatore         61 non-null     str
 27  codice_rischio         41 non-null     str
 28  Tipo Documento         5095 non-null   str
 29  FASCIA ETA             5095 non-null   str
 30  3nazionalita           5095 non-null   str
 31  compagnia%aerea        5095 non-null   str
 32  num volo               5095 non-null   str
dtypes: int64(1), str(32)
memory usage: 1.3 MB