# Load libraries

In [81]:
import pandas as pd 
import numpy as np
import re

# Load datasets

In [82]:
df1 = pd.read_csv("data/ALLARMI.csv")
df2 = pd.read_csv("data/TIPOLOGIA_VIAGGIATORE.csv")

In [83]:
df1

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5075,Nulla a procedere SDI,MXP,LTN,2023,01,2024-01-19 17:30:00,Malpensa,London Luton,Milano,Londra,...,2,5,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,5
5076,Voli disponibili in ingresso al Sistema,BLQ,RAK,2024,02,FEB 06 2024,Guglielmo Marconi,Menara,Bologna,Marrakech,...,8,1,TSC,NaN,NaN,Marocco,ITA,8,Italia,1
5077,Voli con Allarmi,FCO,DOH,2024,01,2024-01-12 15:35:00,Fiumicino,Hamad International,Roma,Doha,...,5,1,NSIS,NaN,NaN,Qatar,ITA,5,Italia,1
5078,"Voli solo visualizzati, ma NON investigati",LIN,LHR,2024,01,2024-01-13 11:50:00,Linate,London Heathrow,Milano,Londra,...,2,1,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,1
5079,Voli investigati (SDI/NSIS - INTERPOL - TSC),PSA,LGW,2024,02,2024-02-26 13:30:00,Galileo Galilei,London Gatwick,Pisa,Londra,...,8,1,TSC,NaN,NaN,Regno Unito,ITA,8,Italia,1

In [84]:
df2

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5090,ALB,BLQ,TIA,2024,02,15,2024-02-18 09:10:00,Guglielmo Marconi,Rinas Mother Teresa,Bologna,...,Ryanair DAC,FR8399,NaN,NaN,NaN,N.D.,0-17,ALB,Ryanair DAC,FR8399
5091,ALB,FCO,TIA,2024,01,10,2024-01-10 06:10:00,Fiumicino,Rinas Mother Teresa,Roma,...,Wizz Air Malta,W43857,NaN,NaN,NaN,Passaporto,46-60,ALB,Wizz Air Malta,W43857
5092,ALB,FCO,JED,2024,01,31,31/01/2024 22:15:00,Fiumicino,King Abdulaziz International,Roma,...,Wizz Air Malta,w48350,FERMATO,NaN,NaN,N.D.,31-45,ALB,Wizz Air Malta,w48350
5093,ALB,BGY,TIA,2024,01,1,2024-01-01 08:25:00,Orio al Serio,Rinas Mother Teresa,Bergamo,...,Ryanair DAC,FR8350,IN ATTESA,NaN,NaN,Carta d'identità,18-30,ALB,Ryanair DAC,FR8350
5094,ALB,FCO,MIA,2024,01,12,2024-01-12 19:50:00,Fiumicino,Miami International,Roma,...,ITA Airways,NaN,FERMATO,NaN,NaN,Carta d'identità,61+,ALB,ITA Airways,AZ0631

# Allarmi Dataset

First general look at the dataset (df1)

In [85]:
df1.shape

(5080, 24)

In [86]:
df1.head(5)

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2

In [87]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5080 entries, 0 to 5079
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   OCCORRENZE             5080 non-null   str
 1   AREOPORTO_ARRIVO       5080 non-null   str
 2   AREOPORTO_PARTENZA     5080 non-null   str
 3   ANNO_PARTENZA          5080 non-null   str
 4   MESE_PARTENZA          5080 non-null   str
 5   DATA_PARTENZA          5080 non-null   str
 6   DESCR_AEREOPORTO_ARR   5080 non-null   str
 7   DESCR_AEREOPORTO_PART  4971 non-null   str
 8   CITTA_ARR              5080 non-null   str
 9   CITTA_PARTENZA         4979 non-null   str
 10  CODICE_PAESE_ARR       5080 non-null   str
 11  CODICE_PAESE_PART      5026 non-null   str
 12  PAESE_ARR              5080 non-null   str
 13  PAESE_PART             5006 non-null   str
 14  ZONA                   5080 non-null   str
 15  TOT                    5080 non-null   str
 16  MOTIVO_ALLARME         3920 non-null   str
 17  note_operatore         77 non-null     str
 18  flag_rischio           51 non-null     str
 19  Paese Partenza         5080 non-null   str
 20  CODICE PAESE ARR       5080 non-null   str
 21  3zona                  5080 non-null   int64
 22  paese%arr              5080 non-null   str
 23  tot voli               5080 non-null   str
dtypes: int64(1), str(23)
memory usage: 952.6 KB

In [88]:
# Normalizing the dataset, lowercasing and stripping useless cases
df1 = df1.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

# Checking for duplicates and dropping them 
print('Initial duplicates:')
print(df1.duplicated().sum())
df1 = df1.drop_duplicates()
print('Duplicates after cleaning:')
print(df1.duplicated().sum())

Initial duplicates:
50
Duplicates after cleaning:
0

### Occorrenze

In [89]:
print(f"Unique values: {df1['OCCORRENZE'].nunique()}")
print(f"Null values: {df1['OCCORRENZE'].isnull().sum()}")
print()
print(df1['OCCORRENZE'].value_counts(dropna=False).to_string())

Unique values: 30
Null values: 0

OCCORRENZE
viaggiatori entrati nel sistema                 618
voli disponibili in ingresso al sistema         583
voli solo visualizzati, ma non investigati      563
voli investigati (sdi/nsis - interpol - tsc)    540
viaggiatori investigati                         520
allarmi generati da sdi/nsis                    509
voli con allarmi                                505
viaggiatori con allarmi                         463
nulla a procedere sdi                           247
allarmi chiusi                                  243
allarmi rilevanti                               112
errata segnalazione sdi                          25
allarmi generati da bcs                          21
allarmi chiusi con azione (cc.xx)                14
notifica atti/provv                              10
allarmi generati da interpol                      8
allarmi non chiusi                                7
mancato aggiornamento sdi                         6
nulla a procedere nsis                            6
respinto/a                                        5
errata segnalazione bcs                           5
allarmi generati                                  5
inammissibilita schengen - art.24                 4
errata segnalazione nsis                          3
mancato aggiornamento schengen nsis               2
altro                                             2
nulla a procedere int                             1
???                                               1
n/c                                               1
allarmati                                         1

Grouping categories that are similar to each other

In [90]:
occorrenze_map = {
    'viaggiatori entrati nel sistema'              : 'viaggiatori entrati',
    'voli disponibili in ingresso al sistema'      : 'voli disponibili',
    'voli solo visualizzati, ma non investigati'   : 'voli solo visualizzati',
    'voli investigati (sdi/nsis - interpol - tsc)' : 'voli investigati',
    'viaggiatori investigati'                      : 'viaggiatori investigati',
    'voli con allarmi'                             : 'voli con allarmi',
    'viaggiatori con allarmi'                      : 'viaggiatori con allarmi',
    'allarmi generati da sdi/nsis'                 : 'allarmi generati',
    'allarmi generati da bcs'                      : 'allarmi generati',
    'allarmi generati da interpol'                 : 'allarmi generati',
    'allarmi generati'                             : 'allarmi generati',
    'allarmi chiusi'                               : 'allarmi chiusi',
    'allarmi chiusi con azione (cc.xx)'            : 'allarmi chiusi',
    'allarmi rilevanti'                            : 'allarmi rilevanti',
    'allarmi non chiusi'                           : 'allarmi non chiusi',
    'nulla a procedere sdi'                        : 'esito negativo',
    'nulla a procedere nsis'                       : 'esito negativo',
    'nulla a procedere int'                        : 'esito negativo',
    'errata segnalazione sdi'                      : 'esito negativo',
    'errata segnalazione nsis'                     : 'esito negativo',
    'errata segnalazione bcs'                      : 'esito negativo',
    'respinto/a'                                   : 'esito negativo',
    'mancato aggiornamento sdi'                    : 'mancato aggiornamento',
    'mancato aggiornamento schengen nsis'          : 'mancato aggiornamento',
    'notifica atti/provv'                          : 'altro',
    'inammissibilita schengen - art.24'            : 'altro',
    'altro'                                        : 'altro',
    '???'                                          : np.nan,
    'n/c'                                          : np.nan,
    'ali armatt'                                   : np.nan,
}

df1['OCCORRENZE'] = df1['OCCORRENZE'].map(occorrenze_map)

print(f"\nNull Values: {df1['OCCORRENZE'].isnull().sum()}")
print(f"\nDistribution:")
print(df1['OCCORRENZE'].value_counts(dropna=False).to_string())

Null Values: 3

Distribution:
OCCORRENZE
viaggiatori entrati        618
voli disponibili           583
voli solo visualizzati     563
allarmi generati           543
voli investigati           540
viaggiatori investigati    520
voli con allarmi           505
viaggiatori con allarmi    463
esito negativo             292
allarmi chiusi             257
allarmi rilevanti          112
altro                       16
mancato aggiornamento        8
allarmi non chiusi           7
NaN                          3

### Aeroporto Arrivo

In [91]:
print(f"Unique values: {df1['AREOPORTO_ARRIVO'].nunique()}")
print(f"Null values: {df1['AREOPORTO_ARRIVO'].isnull().sum()}")
print()
print(df1['AREOPORTO_ARRIVO'].value_counts(dropna=False).to_string())

Unique values: 31
Null values: 0

AREOPORTO_ARRIVO
fco    1272
mxp    1185
bgy     464
vce     356
blq     326
nap     202
lin     174
cia     163
trn     151
psa     139
cta     114
vrn     108
tsf      82
flr      68
bri      57
pmo      26
aoi      24
goa      20
peg      16
psr      15
trs      14
rmi      12
suf       9
pmf       7
cag       7
bds       6
cuf       6
ciy       3
bzo       2
olb       1
vbs       1

In [92]:
# ── df1 – AREOPORTO_PARTENZA ─────────────────────────────────────────────────
print(f"Valori unici: {df1['AREOPORTO_PARTENZA'].nunique()}")
print(f"Valori nulli: {df1['AREOPORTO_PARTENZA'].isnull().sum()}")
print()
print(df1['AREOPORTO_PARTENZA'].value_counts(dropna=False).to_string())

Valori unici: 112
Valori nulli: 0

AREOPORTO_PARTENZA
tia    612
stn    502
lgw    401
lhr    387
ist    300
dxb    153
cai    133
saw    132
cmn    130
man    129
doh    105
rak    105
jfk    104
ssh     95
tun     86
beg     81
auh     77
lcy     73
ewr     63
ltn     58
jed     52
gru     51
edi     50
brs     46
amm     46
add     46
tlv     45
rmo     43
bhx     41
pek     35
eze     31
evn     31
spx     30
pvg     30
icn     28
del     27
tpe     25
alg     25
kwi     23
sin     22
ruh     21
mct     20
ema     18
skp     17
mle     17
szx     17
gig     17
atl     16
mia     16
kiv     15
gyd     15
ncl     15
rmf     15
shj     15
wnz     13
bah     13
ika     12
dss     12
yul     12
kut     12
tgd     11
phl     11
mex     10
gla     10
hnd     10
fez      9
lrm      9
hrg      9
sid      9
mba      9
hkg      8
tng      8
dfw      8
prn      8
bqh      8
dwc      8
fab      7
bey      7
hgh      6
yyz      6
lpl      6
tbs      6
iad      6
adb      6
znz      5
nkg      5
cgo      4
atq      4
rba      4
mji      4
aga      4
dmm      4
tfu      4
ckg      3
bfs      3
bos      3
lxr      3
can      3
sll      3
mru      2
cun      2
lba      2
tas      2
mbj      2
oxf      1
ala      1
anu      1
isl      1
lyx      1
nht      1
oak      1
lax      1

### Anno Partenza

In [93]:
print(f"Unique values: {df1['ANNO_PARTENZA'].nunique()}")
print(f"Null values: {df1['ANNO_PARTENZA'].isnull().sum()}")
print()
print(df1['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 5
Null values: 0

ANNO_PARTENZA
2024         4631
2023          256
24             52
anno 2024      49
2024.          42

In [94]:
def normalizza_anno(val):
    if pd.isna(val): return np.nan
    val = str(val).strip()
    match = re.search(r'\b(20\d{2})\b', val)
    if match: return int(match.group(1))
    match = re.search(r'\b(\d{2})\b', val)
    if match: return int('20' + match.group(1))
    return np.nan

df1['ANNO_PARTENZA'] = df1['ANNO_PARTENZA'].apply(normalizza_anno)

print(df1['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

ANNO_PARTENZA
2024    4774
2023     256

### Mese Partenza

In [95]:
print(f"Unique values: {df1['MESE_PARTENZA'].nunique()}")
print(f"Null values: {df1['MESE_PARTENZA'].isnull().sum()}")
print()
print(df1['MESE_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 14
Null values: 0

MESE_PARTENZA
01     2425
02     2273
gen      80
feb      63
12       26
07       23
06       22
04       21
11       19
09       17
03       16
08       15
05       15
10       15

In [96]:
mesi_map = {"gen": "01", "feb": "02"}
df1["MESE_PARTENZA"] = df1["MESE_PARTENZA"].replace(mesi_map)

print(df1["MESE_PARTENZA"].value_counts(dropna=False).sort_index().to_string())

MESE_PARTENZA
01    2505
02    2336
03      16
04      21
05      15
06      22
07      23
08      15
09      17
10      15
11      19
12      26

### Data Partenza

In [97]:
print(f"Unique values: {df1['DATA_PARTENZA'].nunique()}")
print(f"Null values: {df1['DATA_PARTENZA'].isnull().sum()}")
print()
print(df1['DATA_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 3810
Null values: 0

DATA_PARTENZA
2024-02-04 06:10:00    6
2024-01-31 18:00:00    6
2024-01-19 08:55:00    5
2024-01-22 13:00:00    5
2024/02/26             5
2024-01-04 11:30:00    5
2024-01-06 08:00:00    5
2024-02-29 16:40:00    5
2024-02-18 06:50:00    5
2024-02-09 12:50:00    4
05.01.2024             4
gen 06 2024            4
feb 18 2024            4
2024-01-30 12:35:00    4
18.02.2024             4
2024-01-22 07:30:00    4
2024-02-19 09:00:00    4
2024-02-10 22:20:00    4
gen 14 2024            4
2024-02-08 10:00:00    4
17-01-24               4
2024-02-18 13:05:00    4
2024-01-01 08:00:00    4
2024-02-02 09:15:00    4
2024-01-05 19:05:00    4
2024-01-27 18:05:00    4
23-02-24               4
2024-01-24 08:00:00    4
2024-02-09 18:05:00    4
2024-01-21 17:50:00    4
2024-02-19 17:55:00    4
2024-01-07 18:00:00    4
2024-01-04 09:25:00    4
2024-02-13 17:55:00    4
2024-02-02 17:20:00    4
2024-02-02 12:50:00    4
2024-02-09 13:20:00    4
2024-02-19 20:30:00    4
2024-02-23 18:00:00    4
2024-02-19 18:20:00    4
2024-01-19 14:45:00    4
2024-02-19 15:45:00    4
2024-02-17 06:45:00    4
2024-01-10 08:55:00    4
2024-02-11 07:15:00    4
2024-02-21 08:55:00    4
2024-02-03 08:10:00    4
2024-01-02 08:25:00    4
2024-01-18 20:45:00    4
2024-02-09 07:55:00    4
2024-01-06 09:20:00    3
2024-01-27 06:40:00    3
2024-02-25 13:10:00    3
2024-02-04 07:45:00    3
2024-01-01 05:45:00    3
2024-01-01 10:30:00    3
2024-01-07 12:30:00    3
2024/02/25             3
09.01.2024             3
2024-02-22 21:50:00    3
2024-01-02 12:00:00    3
2024-01-05 13:40:00    3
2024-02-16 13:40:00    3
2024-02-18 11:45:00    3
2024/02/08             3
2024-01-02 06:55:00    3
2024-01-26 06:15:00    3
2024-01-27 15:35:00    3
2024-01-12 07:15:00    3
2024-01-24 06:10:00    3
2024-01-18 07:00:00    3
2024-01-14 09:35:00    3
2024-02-04 20:15:00    3
2024-01-11 14:05:00    3
2024/02/01             3
2024-02-16 17:35:00    3
2024-01-21 21:00:00    3
2024-01-26 18:00:00    3
2024-02-17 06:20:00    3
2024-02-11 09:35:00    3
2024-02-10 07:50:00    3
2024-01-07 17:00:00    3
2024-01-23 08:55:00    3
01.01.2024             3
2024-01-26 13:00:00    3
gen 27 2024            3
2024-01-13 12:50:00    3
2024-02-09 07:15:00    3
2024-01-18 12:35:00    3
2024-01-03 07:25:00    3
2024/01/18             3
2024-01-19 10:20:00    3
2024-01-12 15:35:00    3
2024-01-08 17:25:00    3
2024-02-16 17:30:00    3
2024-01-13 07:25:00    3
2024-01-04 14:20:00    3
2024-01-27 10:00:00    3
2024-02-13 09:15:00    3
2024-01-08 19:40:00    3
2024-02-07 18:00:00    3
2024-02-26 07:45:00    3
2024-02-09 20:40:00    3
2024-02-25 18:20:00    3
2024-01-29 07:30:00    3
2024-02-16 14:50:00    3
2024-01-22 18:00:00    3
2024-01-20 19:50:00    3
2024-02-05 18:00:00    3
2024-01-21 21:50:00    3
2024-02-17 06:05:00    3
2024-01-02 19:50:00    3
2024-02-05 08:00:00    3
2024/01/26             3
2024-01-14 18:35:00    3
2024-01-21 15:55:00    3
2024-02-16 21:00:00    3
2024-01-08 07:10:00    3
2024-01-18 21:50:00    3
2024-02-21 20:35:00    3
2024/01/05             3
2024-02-17 13:00:00    3
2024-01-06 08:25:00    3
24-02-24               3
2024-02-23 18:20:00    3
2024-02-06 15:50:00    3
12-02-24               3
2024-02-14 18:00:00    3
2024-02-26 19:50:00    3
2024-02-06 12:55:00    3
2024-01-08 09:15:00    3
2024-01-08 09:00:00    3
2024-02-04 20:40:00    3
2024-01-17 10:35:00    3
22.01.2024             3
2024-02-01 19:50:00    3
2024-02-17 06:00:00    3
05-01-24               3
2024-01-04 13:25:00    3
2024-01-24 19:50:00    3
2024-02-05 13:00:00    3
2024-02-25 13:00:00    3
2024-02-20 14:55:00    3
2024-01-14 10:15:00    3
2024-01-11 06:00:00    3
2024-02-17 17:45:00    3
2024-01-26 13:40:00    3
10-01-24               3
2024-01-16 12:00:00    3
2024-01-04 21:00:00    3
2024-02-01 07:10:00    3
2024-02-20 12:50:00    3
27-01-24               3
2024-02-21 06:10:00    3
2024-02-21 08:00:00    3
2024-02-01 21:50:00    3
2024-02-14 12:10:00    3
2024-01-10 08:50:00    3
feb 01 2024            3
2024-01-31 09:25:00    3
2024-01-07 16:05:00    3
2024-01-03 06:50:00    3
23.02.2024             3
2024-02-05 15:35:00    3
2024-02-23 20:50:00    3
2024-02-21 18:00:00    3
2024-02-25 18:25:00    3
2024/02/03             3
2024-01-03 21:35:00    3
2024-01-14 19:25:00    3
2024-01-04 12:40:00    3
2024-01-03 14:10:00    3
2024-02-02 07:00:00    3
2024-02-01 18:00:00    3
2024-01-02 07:30:00    3
2024-01-06 08:15:00    3
2024-01-31 11:20:00    3
2024-02-17 19:50:00    3
2024-01-22 20:40:00    3
2024-02-25 15:30:00    3
20-01-24               3
2024-01-05 02:20:00    3
2024-01-07 13:50:00    3
2024-01-27 15:45:00    3
2024-01-10 13:00:00    3
2024-01-08 18:00:00    3
2024-01-16 12:55:00    3
2024-01-20 06:50:00    3
2024-02-17 20:15:00    3
2024-01-15 07:20:00    3
2024-02-18 09:50:00    3
2024-02-17 20:40:00    3
2024-01-27 13:20:00    3
2024-02-28 16:05:00    3
2024-01-11 08:00:00    3
2024-02-11 18:25:00    3
2024-02-28 17:35:00    3
2024-02-28 06:10:00    3
2024-02-16 12:35:00    3
2024-01-09 13:05:00    3
2024-01-12 08:55:00    3
01-02-24               3
2024-02-10 07:00:00    3
2024-02-09 07:00:00    3
28-01-24               3
feb 06 2024            3
2024-01-07 07:00:00    3
2024-01-28 18:35:00    3
2024-01-22 14:15:00    3
2024-02-29 19:40:00    3
2024-02-21 15:00:00    3
2024-02-08 19:55:00    3
2024-01-04 06:10:00    3
2024-01-05 12:00:00    3
2024-01-28 19:25:00    3
2024-01-12 17:30:00    3
2024-01-27 12:05:00    3
2024-02-16 12:50:00    2
2024-01-13 10:00:00    2
2024-02-23 07:15:00    2
2024-02-12 08:00:00    2
2024-01-15 17:10:00    2
28.01.2024             2
2024-01-14 07:55:00    2
2024-02-10 15:15:00    2
2024-02-25 17:30:00    2
2024-02-08 17:55:00    2
2024-01-12 08:10:00    2
2024-02-13 06:15:00    2
2024-02-16 10:40:00    2
2024-02-04 07:35:00    2
2024-01-03 13:20:00    2
2024-01-25 08:10:00    2
2024-01-27 12:20:00    2
2024-01-05 07:55:00    2
2024-02-24 22:05:00    2
2024-02-08 12:40:00    2
2024-02-05 13:25:00    2
2024-02-07 07:55:00    2
2024-01-19 19:05:00    2
2024-02-03 13:00:00    2
2024-01-11 06:45:00    2
2024-01-02 07:00:00    2
2024/01/08             2
2024-01-06 18:00:00    2
2024-01-07 10:00:00    2
2024-01-02 21:35:00    2
2024-01-31 15:35:00    2
2024-02-26 20:30:00    2
2024-01-01 11:40:00    2
2024-01-21 13:05:00    2
2024-02-13 13:40:00    2
2024-02-29 06:00:00    2
2024-02-02 18:05:00    2
2024-02-05 06:10:00    2
2024/02/16             2
2024-02-25 18:50:00    2
feb 07 2024            2
2024-01-03 17:00:00    2
2024-02-15 11:50:00    2
2024-01-13 12:00:00    2
2024-02-08 15:20:00    2
2024-02-12 18:10:00    2
2024-01-24 13:40:00    2
2024-01-04 08:55:00    2
2024-01-27 13:05:00    2
2024-01-17 03:45:00    2
2024-01-17 17:00:00    2
2024-01-02 13:05:00    2
2024-02-14 13:20:00    2
2024/01/12             2
2024-01-18 12:00:00    2
2024-02-16 08:55:00    2
2024-02-15 14:15:00    2
2024-01-25 17:00:00    2
2024-01-20 13:05:00    2
2024-02-26 18:10:00    2
2024-01-14 11:30:00    2
2024-01-11 07:00:00    2
2024-02-27 14:30:00    2
2024-02-04 06:50:00    2
2024-02-04 21:10:00    2
2024-01-27 17:05:00    2
2024-02-18 12:10:00    2
2024-01-15 17:25:00    2
2024-02-01 09:00:00    2
2024-02-23 11:30:00    2
2024-01-18 12:10:00    2
2024-02-01 07:00:00    2
2024-02-13 22:40:00    2
2024-01-14 10:45:00    2
2024-02-20 16:00:00    2
2024/01/02             2
2024-02-27 09:00:00    2
2024-01-30 07:00:00    2
2024-02-26 21:50:00    2
2024-01-23 17:40:00    2
2024-01-09 12:10:00    2
2024-01-07 09:35:00    2
2024-02-29 01:30:00    2
2024-02-17 09:05:00    2
2024-01-25 15:45:00    2
2024-02-10 08:55:00    2
2024-01-22 07:20:00    2
2024-02-08 20:30:00    2
2024-01-12 18:55:00    2
2024-02-10 09:10:00    2
2024-01-10 19:55:00    2
2024-02-02 11:25:00    2
2024-01-24 09:35:00    2
2024-01-06 06:55:00    2
2024-02-23 16:45:00    2
2024-01-19 18:15:00    2
2024-02-23 11:00:00    2
2024-01-09 14:05:00    2
2024-01-19 08:00:00    2
2024/02/07             2
2024-01-20 12:50:00    2
31-01-24               2
2024-02-28 05:35:00    2
2024-02-18 21:00:00    2
2024-02-24 11:30:00    2
2024-02-11 17:40:00    2
2024-02-28 11:05:00    2
2024-02-04 20:00:00    2
2024-01-04 18:20:00    2
2024-01-03 16:20:00    2
2024-02-02 10:20:00    2
2024-02-02 07:45:00    2
2024-01-30 07:10:00    2
2024-01-22 08:55:00    2
2024-02-25 18:35:00    2
2024-02-19 07:35:00    2
2024/02/21             2
2024-02-20 09:30:00    2
2024-02-16 13:00:00    2
2024-01-30 20:10:00    2
2024-02-14 17:40:00    2
2024-02-07 07:10:00    2
2024-01-24 18:00:00    2
2024-01-03 08:50:00    2
2024-01-10 12:00:00    2
2024-02-11 08:50:00    2
2024-02-17 14:05:00    2
2024/01/09             2
2024-01-13 19:50:00    2
2024-02-26 02:00:00    2
2024-02-12 09:00:00    2
2024-01-15 06:05:00    2
2024-01-22 21:50:00    2
2024-01-07 09:30:00    2
2024-02-04 18:00:00    2
2024-02-08 14:10:00    2
2024-01-12 16:35:00    2
2024-01-02 14:05:00    2
2024-02-25 10:10:00    2
2024-01-08 17:40:00    2
2024-02-28 14:40:00    2
2024-01-12 06:55:00    2
2024-02-26 17:50:00    2
2024-01-19 11:00:00    2
2024-01-12 16:20:00    2
2024-01-19 12:10:00    2
04-02-24               2
2024-01-17 17:45:00    2
2024-01-27 11:15:00    2
2024-01-29 20:20:00    2
2024-02-08 08:25:00    2
2024-01-19 12:05:00    2
2024-02-22 22:10:00    2
2024-02-25 15:10:00    2
2024-01-12 13:55:00    2
2024-02-01 22:20:00    2
2024-01-09 23:25:00    2
2024-01-29 08:50:00    2
2024-01-28 23:25:00    2
2024-01-22 06:10:00    2
2024-01-01 09:35:00    2
2024-02-13 07:50:00    2
2024-01-23 10:30:00    2
2024-01-28 12:00:00    2
2024-02-27 15:00:00    2
2024-02-08 07:55:00    2
2024-02-27 17:00:00    2
2024-02-26 13:40:00    2
2024-02-10 10:00:00    2
2024-01-11 07:20:00    2
2024-02-28 12:10:00    2
2024-02-23 10:30:00    2
2024-01-16 18:05:00    2
2024-01-02 06:45:00    2
2024-02-04 09:30:00    2
2024-02-17 21:40:00    2
2024-01-25 07:15:00    2
2024-02-03 08:55:00    2
2024-01-17 18:40:00    2
2024-01-27 14:55:00    2
2024-01-02 06:10:00    2
2024-01-02 10:00:00    2
2024-02-15 10:00:00    2
2024-02-11 19:25:00    2
2024/02/22             2
2024-01-31 17:00:00    2
2024-02-26 06:10:00    2
2024-02-06 13:30:00    2
2024-02-09 16:20:00    2
2024-01-15 15:10:00    2
2024-02-03 06:50:00    2
2024-01-20 06:55:00    2
2024-01-14 07:45:00    2
2024-02-12 04:30:00    2
2024-01-20 22:10:00    2
2024-02-12 20:40:00    2
2024-01-01 10:00:00    2
30-01-24               2
2024-01-11 06:20:00    2
2024-02-11 13:05:00    2
2024-01-13 11:35:00    2
feb 29 2024            2
2024-01-23 21:00:00    2
2024-01-25 07:00:00    2
2024-02-20 07:15:00    2
2024-02-02 07:35:00    2
2024-01-06 20:30:00    2
2024-02-23 12:05:00    2
2024-02-28 13:45:00    2
2024-01-16 08:55:00    2
2024-01-13 13:00:00    2
2024-01-25 12:40:00    2
2024-02-19 18:10:00    2
2024-02-05 08:55:00    2
2024-02-27 09:15:00    2
2024-01-07 19:05:00    2
2024-02-19 08:55:00    2
2024-02-09 19:05:00    2
2024-01-06 10:35:00    2
10.01.2024             2
2024-01-21 13:00:00    2
feb 19 2024            2
2024-01-04 11:00:00    2
2024-01-20 10:00:00    2
2024-01-30 10:15:00    2
2024-02-07 07:30:00    2
2024-01-15 12:15:00    2
2024-01-10 17:55:00    2
2024-01-04 09:15:00    2
2024-02-08 13:15:00    2
2024-01-28 09:48:00    2
2024-02-24 08:10:00    2
2024-01-02 19:55:00    2
2024-01-27 08:55:00    2
2024-02-07 13:55:00    2
2024-02-14 13:45:00    2
2024-01-07 08:00:00    2
2024-02-06 07:30:00    2
2024-01-08 06:45:00    2
2024-01-05 17:55:00    2
2024-02-16 10:20:00    2
2024-01-25 13:20:00    2
2024-01-07 11:15:00    2
2024-01-29 14:40:00    2
2024-01-17 22:20:00    2
2024-01-14 21:00:00    2
2024-01-03 19:20:00    2
2024-01-17 06:10:00    2
2024-01-14 06:10:00    2
2024-02-10 08:00:00    2
2024-02-10 18:25:00    2
2024-01-07 06:50:00    2
2024-02-04 15:45:00    2
2024-02-08 19:40:00    2
2024-01-25 10:00:00    2
2024-01-23 18:05:00    2
2024-02-21 10:05:00    2
2024-02-13 14:15:00    2
2024-01-05 09:15:00    2
2024-02-24 14:00:00    2
2024-01-02 14:58:00    2
2024-01-20 06:30:00    2
2024-01-10 14:35:00    2
2024-01-07 16:15:00    2
2024-02-10 10:30:00    2
2024-02-17 18:35:00    2
2024-01-18 18:05:00    2
2024-02-19 17:00:00    2
2024-01-15 20:55:00    2
2024-01-11 20:30:00    2
21-02-24               2
2024-02-23 06:45:00    2
feb 09 2024            2
2024-02-19 13:00:00    2
2024-01-17 10:25:00    2
2024-01-10 11:55:00    2
2024-02-24 18:00:00    2
2024-01-02 12:10:00    2
2024-02-03 19:45:00    2
2024-02-16 12:10:00    2
2024-01-25 11:15:00    2
2024-01-12 15:55:00    2
2024-02-05 17:55:00    2
2024-02-08 13:05:00    2
2024-01-21 10:10:00    2
2024-01-17 13:25:00    2
2024-01-20 06:20:00    2
2024-01-26 18:15:00    2
2024-01-18 17:00:00    2
2024-01-27 08:40:00    2
2024-02-10 06:00:00    2
2024-02-09 00:05:00    2
2024-02-21 19:25:00    2
2024-01-27 23:05:00    2
2024-02-03 08:40:00    2
2024-02-13 13:45:00    2
2024-02-08 07:00:00    2
29.02.2024             2
2024-01-12 06:20:00    2
2024-01-07 06:00:00    2
2024-02-07 16:00:00    2
2024-02-20 08:10:00    2
2024-02-28 06:45:00    2
2024-02-04 18:05:00    2
2024-02-18 10:10:00    2
2024-02-16 17:20:00    2
2024-01-30 17:50:00    2
2024-02-24 14:05:00    2
2024-02-04 07:00:00    2
2024-01-07 12:00:00    2
2024-02-18 00:50:00    2
2024-01-23 21:20:00    2
2024-02-26 09:00:00    2
2024-01-15 07:30:00    2
2024/02/04             2
2024-01-13 10:30:00    2
2024-01-04 12:50:00    2
2024-01-27 14:05:00    2
2024-01-02 08:00:00    2
2024-02-08 19:10:00    2
2024-02-18 13:30:00    2
2024-01-17 10:00:00    2
2024-01-25 12:35:00    2
17-02-24               2
2024-01-18 08:10:00    2
2024-02-12 18:20:00    2
2024-02-22 13:20:00    2
2024-02-13 17:40:00    2
2024-01-07 23:45:00    2
2024-02-12 14:20:00    2
2024-02-08 13:45:00    2
2024-01-30 06:45:00    2
2024-01-26 01:45:00    2
2024-01-08 13:25:00    2
2024-02-04 07:15:00    2
2024-01-08 06:05:00    2
2024-01-06 16:15:00    2
2024-02-13 06:00:00    2
2024-02-23 21:05:00    2
2024-02-19 19:45:00    2
2024-01-20 17:55:00    2
2024-01-28 17:55:00    2
2024-01-31 10:40:00    2
2024-01-18 08:25:00    2
2024-02-17 08:30:00    2
2024-02-11 06:00:00    2
2024-01-28 12:50:00    2
2024-01-02 10:35:00    2
2024/01/11             2
2024-01-17 20:45:00    2
2024-02-09 13:40:00    2
2024-02-25 20:15:00    2
2024-01-24 09:00:00    2
2024-02-06 20:15:00    2
2024-02-06 21:50:00    2
2024-01-15 13:00:00    2
2024-02-27 11:25:00    2
20.01.2024             2
2024-02-22 09:21:00    2
2024-01-01 13:25:00    2
2024-01-27 19:50:00    2
2024-02-03 07:50:00    2
2024-02-04 08:10:00    2
2024-01-13 15:45:00    2
gen 29 2024            2
2024-02-22 09:25:00    2
2024-02-09 06:20:00    2
2024/01/15             2
2024-02-02 11:30:00    2
2024-02-03 15:25:00    2
2024-02-11 21:20:00    2
2024-02-16 20:50:00    2
2024-02-01 14:25:00    2
2024-02-02 07:55:00    2
2024-02-18 07:05:00    2
2024-01-03 16:40:00    2
2024-01-11 11:15:00    2
2024-02-16 16:10:00    2
2024-02-18 12:50:00    2
2024-02-27 07:25:00    2
2024-01-25 18:35:00    2
2024-01-10 08:00:00    2
2024-01-08 15:45:00    2
2024-02-13 20:45:00    2
2024-01-28 16:00:00    2
2024-02-06 11:15:00    2
2024-02-10 15:50:00    2
gen 08 2024            2
2024-02-02 18:00:00    2
2024-02-26 05:45:00    2
2024-01-15 02:20:00    2
2024-02-16 11:40:00    2
2024-01-13 21:05:00    2
2024-01-14 08:00:00    2
2024-01-15 18:15:00    2
2024-02-20 13:45:00    2
2024-02-16 15:00:00    2
2024-01-12 19:55:00    2
2024-02-10 00:15:00    2
2024-01-05 06:10:00    2
2024-01-12 07:30:00    2
2024-01-31 15:00:00    2
2024-02-29 18:00:00    2
2024-02-10 08:10:00    2
2024-01-06 08:10:00    2
2024-02-23 13:00:00    2
2024-02-01 08:05:00    2
2024-02-23 12:15:00    2
2024-02-10 09:35:00    2
2024-02-23 08:00:00    2
2024-02-15 13:00:00    2
2024-02-17 17:40:00    2
2024-02-01 10:20:00    2
2024-02-04 10:35:00    2
2024-02-16 20:00:00    2
2024-01-05 13:45:00    2
2024-02-01 08:30:00    2
2024-02-01 17:00:00    2
2024-02-26 13:25:00    2
2024-01-21 12:05:00    2
2024-02-26 17:10:00    2
2024-02-06 11:10:00    2
2024-02-15 08:00:00    2
2024-02-27 06:45:00    2
2024-02-28 09:35:00    2
2024-01-18 19:05:00    2
2024-02-06 01:45:00    2
2024-01-19 15:30:00    2
2024-01-20 12:10:00    2
2024-01-21 12:10:00    2
2024-01-29 12:25:00    2
07.01.2024             2
2024-02-03 20:40:00    2
2024-01-29 08:35:00    2
2024-02-21 12:50:00    2
2024-01-23 15:30:00    2
2024-02-20 17:55:00    2
2024-02-23 19:35:00    2
2024-01-23 09:15:00    2
2024-01-25 20:05:00    2
2024-01-02 05:45:00    2
2024-01-22 15:45:00    2
01-01-24               2
2024-02-28 18:00:00    2
2024/02/06             2
2024-02-18 23:15:00    2
2024-02-03 20:15:00    2
2024-01-06 08:40:00    2
2024-02-02 10:00:00    2
2024-02-02 13:30:00    2
2024-02-24 06:00:00    2
2024-02-22 19:40:00    2
2024-01-03 09:10:00    2
2024-01-15 09:30:00    2
2024-01-04 06:00:00    2
2024-02-04 10:20:00    2
2024-01-04 13:05:00    2
2024-02-17 18:30:00    2
2024-01-31 17:15:00    2
2024-01-07 17:20:00    2
2024-02-24 17:00:00    2
2024-02-10 11:30:00    2
2024-02-08 06:10:00    2
2024-01-03 09:25:00    2
2024-02-12 20:50:00    2
2024-02-20 18:00:00    2
2024-01-08 15:35:00    2
29.01.2024             2
2024-02-06 10:15:00    2
2024-02-16 16:55:00    2
2024-02-20 08:50:00    2
2024-02-16 07:55:00    2
2024-01-03 13:40:00    2
2024-02-17 15:06:00    2
2024-01-06 07:25:00    2
2024-01-05 18:55:00    2
2024-02-09 16:40:00    2
2024-01-03 19:40:00    2
2024-01-05 09:35:00    2
2024-02-08 13:35:00    2
2024-01-21 12:40:00    2
2024-01-16 10:15:00    2
2024-02-13 06:45:00    2
2024-01-22 17:50:00    2
2024-02-04 19:45:00    2
2024-01-01 17:45:00    2
2024-01-14 20:40:00    2
2024-01-04 09:24:00    2
2024/02/12             2
25.01.2024             2
2024-01-04 08:10:00    2
2024-01-28 07:50:00    2
2024-02-18 07:00:00    2
2024-02-11 13:30:00    2
2024-02-20 10:30:00    2
27.02.2024             2
2024-01-12 08:00:00    2
2024-01-10 13:25:00    2
2024-02-01 17:50:00    2
gen 20 2024            2
2024-02-23 19:05:00    2
2024-01-21 13:30:00    2
2024-01-22 10:35:00    2
2024-02-21 13:00:00    2
2024-01-20 10:20:00    2
12-01-24               2
2024-01-05 20:45:00    2
2024-02-20 14:20:00    2
2024-01-30 21:15:00    2
2024-02-22 17:45:00    2
2024-02-20 09:20:00    2
2024-01-31 21:00:00    2
2024-02-22 11:35:00    2
2024-01-13 10:05:00    2
2024-01-13 17:55:00    2
2024-02-23 13:40:00    2
2024-01-17 17:40:00    2
2024-01-04 07:55:00    2
2024-02-22 18:00:00    2
2024-02-04 20:45:00    2
2024-02-24 08:00:00    2
2024-02-17 16:00:00    2
2024-02-02 22:40:00    2
2024-02-25 21:10:00    2
2024-01-08 06:10:00    2
2024-01-29 12:35:00    2
2024-01-22 18:40:00    2
2024-02-13 09:00:00    2
2024-01-15 10:00:00    2
2024-02-18 03:45:00    2
2024-01-05 22:10:00    2
2024-01-17 18:20:00    2
2024-02-12 11:45:00    2
2024-01-29 17:35:00    2
2024-01-04 11:45:00    2
2024-02-20 07:50:00    2
2024-02-01 08:55:00    2
2024-01-22 08:50:00    2
2024-01-23 11:10:00    2
2024-02-05 05:45:00    2
2024-01-06 10:05:00    2
2024-01-28 16:10:00    2
2024-01-13 08:10:00    2
2024-01-30 13:20:00    2
2024-02-19 21:50:00    2
2024-02-15 19:40:00    2
2024-01-16 09:25:00    2
2024-02-25 20:25:00    2
2024-01-05 12:35:00    2
2024-01-19 17:55:00    2
2024-02-20 13:30:00    2
2024-01-22 09:00:00    2
2024-01-28 07:00:00    2
09-01-24               2
2024-02-29 15:30:00    2
2024-01-01 11:15:00    2
2024-01-14 12:10:00    2
08.02.2024             2
2024-02-05 12:55:00    2
2024-01-20 08:20:00    2
2024/02/15             2
2024-01-07 18:35:00    2
2024-01-08 14:20:00    2
2024-02-02 17:50:00    2
2024-02-10 17:55:00    2
2024-01-04 09:35:00    2
2024-01-17 13:20:00    2
2024-02-07 11:25:00    2
2024-02-17 18:00:00    2
2024-02-10 14:55:00    2
2024-02-08 16:15:00    2
2024-02-25 12:35:00    2
2024-02-19 14:20:00    2
2024-02-19 09:35:00    2
2024-01-23 16:45:00    2
2024-02-05 10:35:00    2
2024-01-19 18:45:00    2
2024-02-02 20:10:00    2
26-02-24               2
2024-02-22 18:20:00    2
2024-01-28 18:00:00    2

In [98]:
mesi_ita = {
    "GEN": "01", "FEB": "02", "MAR": "03", "APR": "04",
    "MAG": "05", "GIU": "06", "LUG": "07", "AGO": "08",
    "SET": "09", "OTT": "10", "NOV": "11", "DIC": "12"
}

def normalizza_data(val):
    val = str(val).strip()

    # "GEN 06 2024" → "2024-01-06 00:00:00"
    for ita, num in mesi_ita.items():
        if val.startswith(ita + " "):
            parts = val.split(" ")
            return f"{parts[2]}-{num}-{parts[1].zfill(2)} 00:00:00"

    # "2024-01-05T12:35:00" → "2024-01-05 12:35:00"
    val = val.replace("T", " ")

    # "2024/02/26" o "2024/02/26 09:00:00" → "2024-02-26 00:00:00"
    if re.match(r"\d{4}/\d{2}/\d{2}", val):
        val = val.replace("/", "-")
        if len(val) == 10:
            val = val + " 00:00:00"

    # "05.01.2024" → "2024-01-05 00:00:00"
    match = re.match(r"(\d{2})\.(\d{2})\.(\d{4})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    # "04-01-24" → "2024-01-04 00:00:00"
    match = re.match(r"(\d{2})-(\d{2})-(\d{2})$", val)
    if match:
        return f"20{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    # "22/01/2024 15:45:00" → "2024-01-22 15:45:00"
    match = re.match(r"(\d{2})/(\d{2})/(\d{4})\s(\d{2}:\d{2}:\d{2})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} {match.group(4)}"

    return val

df1["DATA_PARTENZA"] = df1["DATA_PARTENZA"].apply(normalizza_data)
df1["DATA_PARTENZA"] = pd.to_datetime(df1["DATA_PARTENZA"], errors="coerce")


# Recover NaT rows using ANNO_PARTENZA + MESE_PARTENZA (set to 1st of the month)
nat_mask = df1["DATA_PARTENZA"].isnull()
df1.loc[nat_mask, "DATA_PARTENZA"] = pd.to_datetime(
    df1.loc[nat_mask, "ANNO_PARTENZA"].astype(str) + "-" +
    df1.loc[nat_mask, "MESE_PARTENZA"].astype(str).str.zfill(2) + "-01",
    errors="coerce"
)

print("NaT left:", df1["DATA_PARTENZA"].isnull().sum())
print("Range date:", df1["DATA_PARTENZA"].min(), "→", df1["DATA_PARTENZA"].max())
print("Examples:")
print(df1["DATA_PARTENZA"].head(5).to_string())

NaT left: 0
Range date: 2023-01-01 00:00:00 → 2024-12-01 00:00:00
Examples:
0   2024-01-30 09:15:00
1   2024-02-03 13:15:00
2   2024-01-15 08:45:00
3   2024-02-02 08:40:00
4   2024-02-16 12:50:00

### Descr Aeroporto Arr

In [99]:
print(f"Unique values: {df1['DESCR_AEREOPORTO_ARR'].nunique()}")
print(f"Null values: {df1['DESCR_AEREOPORTO_ARR'].isnull().sum()}")
print()
print(df1['DESCR_AEREOPORTO_ARR'].value_counts(dropna=False).to_string())

Unique values: 31
Null values: 0

DESCR_AEREOPORTO_ARR
fiumicino               1272
malpensa                1185
orio al serio            464
venezia marco polo       356
guglielmo marconi        326
napoli capodichino       202
linate                   174
ciampino                 163
sandro pertini           151
galileo galilei          139
fontanarossa             114
verona villafranca       108
treviso-sant'angelo       82
firenze peretola          68
palese                    57
punta raisi               26
falconara                 24
cristoforo colombo        20
sant egidio               16
liberi                    15
ronchi dei legionari      14
miramare                  12
lamezia terme              9
parma                      7
elmas                      7
papola casale              6
levaldigi                  6
comiso                     3
bolzano                    2
costa smeralda             1
brescia montichiari        1

### Descr Aeroporto Part

In [100]:
print(f"Unique values: {df1['DESCR_AEREOPORTO_PART'].nunique()}")
print(f"Null values: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print()
print(df1['DESCR_AEREOPORTO_PART'].value_counts(dropna=False).to_string())

Unique values: 119
Null values: 109

DESCR_AEREOPORTO_PART
rinas mother teresa                                                  578
stansted                                                             472
london gatwick                                                       381
london heathrow                                                      364
havalimani                                                           284
dubai international                                                  142
cairo international                                                  126
sabiha gokcen                                                        125
manchester                                                           122
mohamed v                                                            120
NaN                                                                  109
hamad international                                                  102
menara                                                                98
john f kennedy international                                          94
sharm el-sheikh international                                         89
carthage                                                              83
abu dhabi international                                               74
nikola tesla                                                          73
london city                                                           68
newark liberty international                                          55
london luton                                                          55
chisinau international airport                                        54
king abdulaziz international                                          50
edinburgh                                                             48
sao paulo/guarulhos-governador andre franco montoro international     45
ben gurion international                                              44
bole international                                                    44
queen alia international                                              42
bristol                                                               41
birmingham international                                              38
n.d.                                                                  34
?                                                                     33
beijing capital international                                         32
sphinx international                                                  29
ezeiza ministro pistarini                                             29
                                                                      28
pu dong                                                               28
zvartnots                                                             28
//                                                                    27
incheon international                                                 26
-                                                                     26
indira gandhi international                                           26
houari boumediene                                                     24
nd                                                                    23
kuwait international                                                  23
taiwan taoyuan international                                          22
unknown                                                               22
changi                                                                21
seeb                                                                  19
king khaled international                                             19
petrovec                                                              17
east midlands                                                         17
shenzhen                                                              16
hartsfield-jackson atlanta international                              16
galeao-antonio carlos jobim international                             16
male international                                                    15
heydar aliyev international                                           15
miami international                                                   15
marsa alam international                                              14
newcastle                                                             13
wenzhou                                                               12
montreal-pierre elliott trudeau international                         12
bahrain international                                                 12
sharjah                                                               12
kopitnari                                                             12
imam khomeini international                                           11
blaise diagne international                                           11
golubovci                                                             11
philadelphia international                                            11
tokyo international (haneda)                                          10
saiss                                                                  9
casa de campo international                                            9
hurghada international                                                 9
glasgow international                                                  9
benito juarez international                                            8
dallas/fort worth international                                        8
moi international                                                      8
al maktoum international                                               8
ibn batouta                                                            7
amilcar cabral international                                           7
farnborough                                                            7
hong kong international                                                7
prishtina international                                                7
beirut-rafic hariri international                                      7
london biggin hill                                                     7
hangzhou                                                               6
lester b pearson international                                         6
washington dulles international                                        6
kisauni                                                                5
lukou international                                                    5
liverpool john lennon                                                  5
tbilisi international                                                  5
adnan menderes                                                         5
zhengzhou                                                              4
mitiga                                                                 4
agadir almassira                                                       4
king fahd international                                                4
tianfu international                                                   4
raja sansi                                                             3
chongqing jiangbei international                                       3
belfast international                                                  3
sale                                                                   3
logan international                                                    3
luxor international                                                    3
new baiyun                                                             3
salalah                                                                3
sir seewoosagur ramgoolam int                                          2
cancun international                                                   2
leeds/bradford                                                         2
yuzhny                                                                 2
sangster international                                                 2
london oxford                                                          1
almaty                                                                 1
n/a                                                                    1
null                                                                   1
ataturk international                                                  1
lydd                                                                   1
raf northolt                                                           1
oakland international                                                  1
los angeles international                                              1

The column contained 3 types of issues:

1. **167 rows with extra whitespace** — fixed with `.str.strip()`

2. **83 placeholder values** — values such as `"n.d."`, `"nd"`, `"unknown"`, `"null"`
   that carry no real information but were written as text instead of
   being left empty. Converted to `pd.NA` using `.replace()`.

3. **109 original nulls** — empty cells already present in the dataset.

Points 2 and 3 brought the total null count to 192 (3.8% of rows).
All 192 were **recovered** using the IATA code present in the
`AREOPORTO_PARTENZA` column: through an IATA → full airport name
lookup table, each null was replaced with the correct name in lowercase
(e.g. `"STN"` → `"stansted"`, `"LHR"` → `"london heathrow"`).

**Final result: 0 nulls, 133 unique values, all lowercase.**

In [101]:
# ── Dizionario IATA → nome descrittivo ───────────────────────────────────────

PLACEHOLDER_NULL = {'n.d.', '?', '', '//', '-', 'unknown', 'nd', 'n/a', 'null', 'anu', 'none'}

# Prendo solo le righe dove il nome descrittivo è valido (non placeholder)
df1_validi = df1[~df1['DESCR_AEREOPORTO_PART'].isin(PLACEHOLDER_NULL) & df1['DESCR_AEREOPORTO_PART'].notna()]

iata_to_name = (
    df1_validi
    .groupby('AREOPORTO_PARTENZA')['DESCR_AEREOPORTO_PART']
    .agg(lambda x: x.mode()[0])
    .to_dict()
)

print(f"✅ Dizionario creato: {len(iata_to_name)} aeroporti mappati")

df1['DESCR_AEREOPORTO_PART'] = df1['DESCR_AEREOPORTO_PART'].apply(
    lambda x: np.nan if str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulli dopo sostituzione placeholder: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")

df1['DESCR_AEREOPORTO_PART'] = df1.apply(
    lambda row: iata_to_name.get(row['AREOPORTO_PARTENZA'], row['AREOPORTO_PARTENZA'])
    if pd.isna(row['DESCR_AEREOPORTO_PART'])
    else row['DESCR_AEREOPORTO_PART'],
    axis=1
)

print(f"Nulli rimasti: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print(df1['DESCR_AEREOPORTO_PART'].value_counts(dropna=False).to_string())

✅ Dizionario creato: 111 aeroporti mappati
Nulli dopo sostituzione placeholder: 304
Nulli rimasti: 0
DESCR_AEREOPORTO_PART
rinas mother teresa                                                  612
stansted                                                             502
london gatwick                                                       401
london heathrow                                                      387
havalimani                                                           300
dubai international                                                  153
cairo international                                                  133
sabiha gokcen                                                        132
mohamed v                                                            130
manchester                                                           129
hamad international                                                  105
menara                                                               105
john f kennedy international                                         104
sharm el-sheikh international                                         95
carthage                                                              86
nikola tesla                                                          81
abu dhabi international                                               77
london city                                                           73
newark liberty international                                          63
chisinau international airport                                        58
london luton                                                          58
king abdulaziz international                                          52
sao paulo/guarulhos-governador andre franco montoro international     51
edinburgh                                                             50
bristol                                                               46
queen alia international                                              46
bole international                                                    46
ben gurion international                                              45
birmingham international                                              41
beijing capital international                                         35
ezeiza ministro pistarini                                             31
zvartnots                                                             31
sphinx international                                                  30
pu dong                                                               30
incheon international                                                 28
indira gandhi international                                           27
taiwan taoyuan international                                          25
houari boumediene                                                     25
kuwait international                                                  23
changi                                                                22
king khaled international                                             21
seeb                                                                  20
east midlands                                                         18
petrovec                                                              17
male international                                                    17
shenzhen                                                              17
galeao-antonio carlos jobim international                             17
hartsfield-jackson atlanta international                              16
miami international                                                   16
heydar aliyev international                                           15
newcastle                                                             15
marsa alam international                                              15
sharjah                                                               15
wenzhou                                                               13
bahrain international                                                 13
imam khomeini international                                           12
blaise diagne international                                           12
montreal-pierre elliott trudeau international                         12
kopitnari                                                             12
golubovci                                                             11
philadelphia international                                            11
benito juarez international                                           10
glasgow international                                                 10
tokyo international (haneda)                                          10
saiss                                                                  9
casa de campo international                                            9
hurghada international                                                 9
amilcar cabral international                                           9
moi international                                                      9
hong kong international                                                8
ibn batouta                                                            8
dallas/fort worth international                                        8
prishtina international                                                8
london biggin hill                                                     8
al maktoum international                                               8
farnborough                                                            7
beirut-rafic hariri international                                      7
hangzhou                                                               6
lester b pearson international                                         6
liverpool john lennon                                                  6
tbilisi international                                                  6
washington dulles international                                        6
adnan menderes                                                         6
kisauni                                                                5
lukou international                                                    5
zhengzhou                                                              4
raja sansi                                                             4
sale                                                                   4
mitiga                                                                 4
agadir almassira                                                       4
king fahd international                                                4
tianfu international                                                   4
chongqing jiangbei international                                       3
belfast international                                                  3
logan international                                                    3
luxor international                                                    3
new baiyun                                                             3
salalah                                                                3
sir seewoosagur ramgoolam int                                          2
cancun international                                                   2
leeds/bradford                                                         2
yuzhny                                                                 2
sangster international                                                 2
london oxford                                                          1
almaty                                                                 1
anu                                                                    1
ataturk international                                                  1
lydd                                                                   1
raf northolt                                                           1
oakland international                                                  1
los angeles international                                              1

### Città Arrivo

In [102]:
print(f"Unique values: {df1['CITTA_ARR'].nunique()}")
print(f"Null values: {df1['CITTA_ARR'].isnull().sum()}")
print()
print(df1['CITTA_ARR'].value_counts(dropna=False).to_string())

Unique values: 29
Null values: 0

CITTA_ARR
roma             1435
milano           1359
bergamo           464
venezia           356
bologna           326
napoli            202
torino            151
pisa              139
catania           114
verona            108
treviso            82
firenze            68
bari               57
palermo            26
ancona             24
genova             20
perugia            16
pescara            15
trieste            14
rimini             12
lamezia terme       9
parma               7
cagliari            7
brindisi            6
cuneo               6
comiso              3
bolzano             2
olbia               1
brescia             1

### Città Partenza

In [103]:
print(f"Unique values: {df1['CITTA_PARTENZA'].nunique()}")
print(f"Null values: {df1['CITTA_PARTENZA'].isnull().sum()}")
print()
print(df1['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 110
Null values: 100

CITTA_PARTENZA
londra               1362
tirana                582
istanbul              408
dubai                 152
cairo                 125
manchester            124
casablanca            120
marrakech             102
NaN                   100
doha                   99
new york               99
sharm el sheikh        88
tunis                  81
belgrado               80
abu dhabi              73
newark                 57
chisinau               55
jeddah                 50
edinburgh              50
san paolo              48
bristol                45
tel aviv yafo          44
amman                  43
addis ababa            41
birmingham             38
pechino                34
n.d.                   31
yerevan                30
buenos aires           29
shanghai               29
seoul                  28
giza                   27
nuova delhi            26
algeri                 25
taipei                 24
?                      23
nd                     23
kuwait city            22
                       22
-                      21
singapore              20
muscat                 20
riyadh                 20
derby                  18
male                   17
//                     16
unknown                15
shenzhen               15
newcastle              15
atlanta                15
miami                  15
rio de janeiro         15
baku                   14
sharjah                14
skopie                 13
wenzhou                13
marsa alam             13
dakar                  12
montreal               12
manama                 12
kutaisi                12
tehran                 11
podgorica              10
filadelfia             10
tokyo                  10
fes                     9
la romana               9
hurghada                9
sal                     9
citta del messico       9
mombasa                 9
glasgow                 9
hong kong               8
tangier                 8
dallas-fort worth       8
pristina                7
hangzhou                6
farnborough             6
toronto                 6
beirut                  6
liverpool               6
tbilisi                 6
washington              6
smirne                  6
nanjing                 5
zhengzhou               4
zanzibar                4
amritsar                4
rabat                   4
tripoli                 4
agadir                  4
dammam                  4
chengdu                 4
chongqing               3
belfast                 3
boston                  3
luxor                   3
guangzhou               3
plaisance               2
cancun                  2
leeds                   2
tashkent                2
montego bay             2
salalah                 2
oxford                  1
almaty                  1
st. john's              1
lydd                    1
northolt                1
oakland                 1
los angeles             1

In [104]:
# ── Replace placeholder values with NaN, then recover via IATA lookup ────────

PLACEHOLDER_NULL = {'n.d.', '?', '', '//', '-', 'unknown', 'nd', 'n/a', 'null', 'anu', 'none'}

df1["CITTA_PARTENZA"] = df1["CITTA_PARTENZA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df1['CITTA_PARTENZA'].isnull().sum()}")

# Recover nulls via IATA → city lookup
iata_city = {
    "tia": "tirana",   "stn": "londra",    "lgw": "londra",   "lhr": "londra",
    "lcy": "londra",   "ltn": "londra",    "bqh": "londra",   "fab": "londra",
    "ist": "istanbul", "dxb": "dubai",     "cai": "il cairo", "saw": "istanbul",
    "cmn": "casablanca","doh": "doha",      "rak": "marrakech","jfk": "new york",
    "ssh": "sharm el-sheikh","tun": "tunisi","beg": "belgrado","auh": "abu dhabi",
    "ewr": "new york", "jed": "jeddah",    "edi": "edinburgo","gru": "san paolo",
    "eze": "buenos aires","add": "addis abeba","mex": "citta del messico",
    "pek": "pechino",  "rmo": "chisinau",  "bhx": "birmingham","pvg": "shanghai",
    "hkg": "hong kong","mct": "muscat",    "mle": "male",     "rba": "rabat",
    "evn": "yerevan",  "tbs": "tbilisi",   "ema": "east midlands","ruh": "riad",
    "shj": "sharjah",  "gla": "glasgow",   "icn": "seul",     "rmf": "marsa alam",
    "tng": "tangeri",  "sid": "praia",     "spx": "cairo",    "ika": "teheran",
    "prn": "pristina", "mba": "mombasa",   "szx": "shenzhen", "mia": "miami",
    "tpe": "taipei",   "sin": "singapore", "tlv": "tel aviv", "amm": "amman",
    "brs": "bristol",  "man": "manchester","anu": "saint john's","ncl": "newcastle",
    "del": "nuova delhi","atl": "atlanta", "kwi": "kuwait",   "dfw": "dallas",
    "iad": "washington","yul": "montreal", "yyz": "toronto",  "hnd": "tokyo",
    "bey": "beirut",   "alg": "algeri",    "kiv": "chisinau", "gyd": "baku",
    "lpl": "liverpool","skp": "skopje",    "tgd": "podgorica","phl": "filadelfia",
    "fez": "fez",      "gig": "rio de janeiro","atq": "amritsar","znz": "zanzibar",
    "nkg": "nanchino", "aga": "agadir",    "mji": "misurata", "dmm": "dammam",
    "ckg": "chongqing","bfs": "belfast",   "bos": "boston",   "lxr": "luxor",
    "can": "guangzhou","wnz": "wenzhou",   "hgh": "hangzhou", "bah": "manama",
    "dss": "dakar",    "kut": "kutaisi",   "hrg": "hurghada", "lrm": "al marj",
    "oak": "oakland",  "lax": "los angeles","oxf": "oxford",  "lba": "leeds",
    "ala": "almaty",   "isl": "islamabad", "lyx": "marsa matruh","nht": "londra",
    "mbj": "montego bay","cun": "cancun",  "mru": "port louis","tas": "tashkent",
    "sll": "freetown", "cgo": "zhengzhou", "tfu": "chengdu",  "lyx": "marsa matruh",
}

null_mask = df1["CITTA_PARTENZA"].isnull()
df1.loc[null_mask, "CITTA_PARTENZA"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"]
    .str.strip().str.lower()
    .map(iata_city)
)

# Fallback: recover any remaining nulls from other rows sharing the same IATA code
iata_city_from_data = (
    df1[df1["CITTA_PARTENZA"].notna()]
    .groupby("AREOPORTO_PARTENZA")["CITTA_PARTENZA"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df1["CITTA_PARTENZA"].isnull()
df1.loc[null_mask, "CITTA_PARTENZA"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_city_from_data)
)

print(f"Null left: {df1['CITTA_PARTENZA'].isnull().sum()}")
print(f"Unique values: {df1['CITTA_PARTENZA'].nunique()}")

print(df1['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

Nulls after placeholder cleanup: 251
Null left: 0
Unique values: 113
CITTA_PARTENZA
londra               1430
tirana                612
istanbul              433
dubai                 161
casablanca            130
manchester            129
cairo                 128
new york              110
doha                  105
marrakech             105
sharm el sheikh        88
tunis                  81
belgrado               81
abu dhabi              77
chisinau               58
newark                 57
jeddah                 52
san paolo              51
edinburgh              50
bristol                46
amman                  46
tel aviv yafo          44
birmingham             41
addis ababa            41
pechino                35
buenos aires           31
yerevan                31
shanghai               30
seoul                  28
giza                   27
nuova delhi            27
taipei                 25
algeri                 25
singapore              22
kuwait city            22
muscat                 20
riyadh                 20
derby                  18
male                   17
shenzhen               17
rio de janeiro         17
atlanta                16
miami                  16
baku                   15
newcastle              15
marsa alam             15
sharjah                15
skopie                 13
wenzhou                13
manama                 13
dakar                  12
montreal               12
kutaisi                12
tehran                 11
podgorica              11
filadelfia             11
citta del messico      10
glasgow                10
tokyo                  10
fes                     9
la romana               9
hurghada                9
sal                     9
mombasa                 9
hong kong               8
il cairo                8
tangier                 8
dallas-fort worth       8
pristina                8
beirut                  7
sharm el-sheikh         7
hangzhou                6
farnborough             6
toronto                 6
liverpool               6
tbilisi                 6
washington              6
smirne                  6
tunisi                  5
zanzibar                5
addis abeba             5
nanjing                 5
zhengzhou               4
amritsar                4
rabat                   4
tripoli                 4
skopje                  4
agadir                  4
dammam                  4
chengdu                 4
chongqing               3
belfast                 3
boston                  3
luxor                   3
guangzhou               3
plaisance               2
cancun                  2
leeds                   2
tashkent                2
montego bay             2
salalah                 2
riad                    1
oxford                  1
teheran                 1
almaty                  1
st. john's              1
freetown                1
kuwait                  1
tel aviv                1
lydd                    1
northolt                1
oakland                 1
los angeles             1

### Codice Paese Arrivo / Partenza

In [105]:
print("--- CODICE_PAESE_ARR ---")
print(f"Unique: {df1['CODICE_PAESE_ARR'].nunique()}  |  Null: {df1['CODICE_PAESE_ARR'].isnull().sum()}")
print(df1['CODICE_PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- CODICE_PAESE_PART ---")
print(f"Unique: {df1['CODICE_PAESE_PART'].nunique()}  |  Null: {df1['CODICE_PAESE_PART'].isnull().sum()}")
print(df1['CODICE_PAESE_PART'].value_counts(dropna=False).to_string())

--- CODICE_PAESE_ARR ---
Unique: 8  |  Null: 0
CODICE_PAESE_ARR
ita    4690
it      248
fra      25
gbr      18
esp      18
tur      17
deu      13
gb        1

--- CODICE_PAESE_PART ---
Unique: 67  |  Null: 54
CODICE_PAESE_PART
gbr        1626
alb         550
tur         407
egy         259
mar         251
are         234
usa         215
chn         116
qat         101
tun          83
srb          79
gb           78
sau          75
bra          66
mda          58
NaN          54
eth          46
jor          45
isr          43
al           35
arg          30
arm          29
ind          27
kor          26
dza          25
tr           24
unknown      24
twn          23
sgp          22
omn          22
kwt          22
mkd          17
eg           17
can          17
geo          17
mdv          16
             15
aze          15
nd           14
n.d.         13
bhr          13
//           13
irn          12
?            12
sen          12
mex          12
ae           12
mne          11
ken           9
-             9
jpn           9
hkg           8
dom           8
cpv           8
ma            7
rks           7
lbn           6
tza           5
xx            5
lby           4
mus           2
eu            2
uzb           2
jam           2
00            1
kaz           1
atg           1
zz            1

In [106]:
# Cross-check: AREOPORTO_ARRIVO contains only Italian airports, so CODICE_PAESE_ARR
# must be Italy for every row. Any non-"ita" value is a data-entry error.
# We overwrite the entire column rather than mapping variants, since the ground
# truth (Italian arrival airport) is unambiguous.

n_wrong = (df1["CODICE_PAESE_ARR"] != "ita").sum()
print(f"Rows with non-'ita' value before fix: {n_wrong}")
if n_wrong > 0:
    print(df1.loc[df1["CODICE_PAESE_ARR"] != "ita", "CODICE_PAESE_ARR"].value_counts().to_string())

df1["CODICE_PAESE_ARR"] = "ita"

print(f"\nUnique values after fix: {df1['CODICE_PAESE_ARR'].nunique()}")
print(df1["CODICE_PAESE_ARR"].value_counts().to_string())

# CODICE_PAESE_PART: recover nulls using IATA → ISO-3 country code lookup.
iata_country_code = {
    "tia": "alb", "stn": "gbr", "lgw": "gbr", "lhr": "gbr", "lcy": "gbr",
    "ltn": "gbr", "bqh": "gbr", "fab": "gbr", "nht": "gbr", "lpl": "gbr",
    "ncl": "gbr", "edi": "gbr", "bhx": "gbr", "gla": "gbr", "bfs": "gbr",
    "lba": "gbr", "ema": "gbr", "brs": "gbr", "man": "gbr", "oxf": "gbr",
    "ist": "tur", "saw": "tur", "adb": "tur",
    "dxb": "are", "shj": "are", "auh": "are", "dwc": "are",
    "cai": "egy", "ssh": "egy", "hrg": "egy", "lxr": "egy", "rmf": "egy",
    "cmn": "mar", "rak": "mar", "tng": "mar", "fez": "mar", "aga": "mar", "rba": "mar",
    "doh": "qat",
    "jfk": "usa", "ewr": "usa", "mia": "usa", "atl": "usa", "dfw": "usa",
    "iad": "usa", "bos": "usa", "phl": "usa", "oak": "usa", "lax": "usa",
    "tun": "tun", "beg": "srb",
    "jed": "sau", "ruh": "sau", "dmm": "sau",
    "gru": "bra", "gig": "bra",
    "eze": "arg", "add": "eth",
    "mex": "mex", "cun": "mex",
    "pek": "chn", "pvg": "chn", "szx": "chn", "can": "chn", "wnz": "chn",
    "hgh": "chn", "nkg": "chn", "cgo": "chn", "tfu": "chn", "ckg": "chn",
    "rmo": "mda", "kiv": "mda",
    "hkg": "hkg", "mct": "omn", "mle": "mdv", "evn": "arm",
    "tbs": "geo", "kut": "geo", "icn": "kor", "sid": "cpv", "spx": "egy",
    "ika": "irn", "prn": "xkx", "mba": "ken", "znz": "tza",
    "tpe": "twn", "sin": "sgp", "tlv": "isr", "amm": "jor",
    "del": "ind", "atq": "ind", "kwi": "kwt",
    "yul": "can", "yyz": "can", "hnd": "jpn", "bey": "lbn", "alg": "dza",
    "gyd": "aze", "skp": "mkd", "tgd": "mne", "anu": "atg", "dss": "sen",
    "bah": "bhr", "lrm": "lby", "mji": "lby", "mbj": "jam", "mru": "mus",
    "tas": "uzb", "sll": "sle", "ala": "kaz", "isl": "pak",
}

null_mask = df1["CODICE_PAESE_PART"].isnull()
df1.loc[null_mask, "CODICE_PAESE_PART"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"]
    .str.strip().str.lower()
    .map(iata_country_code)
)

print(f"\nNull left CODICE_PAESE_PART: {df1['CODICE_PAESE_PART'].isnull().sum()}")
print(df1['CODICE_PAESE_PART'].value_counts(dropna=False).head(15).to_string())

Rows with non-'ita' value before fix: 340
CODICE_PAESE_ARR
it     248
fra     25
gbr     18
esp     18
tur     17
deu     13
gb       1

Unique values after fix: 1
CODICE_PAESE_ARR
ita    5030

Null left CODICE_PAESE_PART: 0
CODICE_PAESE_PART
gbr    1648
alb     559
tur     411
egy     262
mar     251
are     236
usa     219
chn     118
qat     102
tun      83
srb      80
gb       78
sau      75
bra      67
mda      58

### Paese Arrivo / Partenza

In [107]:
print("--- PAESE_ARR ---")
print(f"Unique: {df1['PAESE_ARR'].nunique()}  |  Null: {df1['PAESE_ARR'].isnull().sum()}")
print(df1['PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- PAESE_PART ---")
print(f"Unique: {df1['PAESE_PART'].nunique()}  |  Null: {df1['PAESE_PART'].isnull().sum()}")
print(df1['PAESE_PART'].value_counts(dropna=False).to_string())

--- PAESE_ARR ---
Unique: 1  |  Null: 0
PAESE_ARR
italia    5030

--- PAESE_PART ---
Unique: 57  |  Null: 74
PAESE_PART
regno unito              1694
albania                   587
turchia                   421
egitto                    267
marocco                   253
emirati arabi uniti       243
stati uniti               220
cina                      117
qatar                     101
tunisia                    81
serbia                     80
arabia saudita             76
NaN                        74
brasile                    63
moldavia                   56
giordania                  45
etiopia                    44
israele                    42
argentina                  30
india                      29
armenia                    28
corea del sud              27
algeria                    24
taiwan                     22
kuwait                     22
singapore                  21
oman                       21
nd                         21
//                         21
?                          20
n.d.                       18
unknown                    18
macedonia                  17
maldive                    17
-                          17
canada                     17
georgia                    17
azerbaigian                14
                           14
bahrain                    13
senegal                    12
messico                    12
montenegro                 11
giappone                   10
iran                        9
repubblica dominicana       9
capo verde                  9
kenya                       9
hong kong                   8
libano                      7
cossovo                     6
tanzania                    5
libia                       3
mauritius                   2
uzbekistan                  2
giamaica                    2
kazakistan                  1
antigua e barbuda           1

In [108]:
# PAESE_ARR: always Italy — no action needed.
# PAESE_PART: first replace placeholders with NaN, then recover via ISO-3 lookup.

PLACEHOLDER_NULL = {'n.d.', '?', '', '//', '-', 'unknown', 'nd', 'n/a', 'null', 'anu', 'none'}

df1["PAESE_PART"] = df1["PAESE_PART"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df1['PAESE_PART'].isnull().sum()}")

codice_paese_map = {
    "alb": "albania",          "gbr": "regno unito",      "tur": "turchia",
    "are": "emirati arabi",    "egy": "egitto",            "mar": "marocco",
    "qat": "qatar",            "usa": "stati uniti",       "tun": "tunisia",
    "srb": "serbia",           "sau": "arabia saudita",    "bra": "brasile",
    "arg": "argentina",        "eth": "etiopia",           "mex": "messico",
    "chn": "cina",             "mda": "moldavia",          "hkg": "hong kong",
    "omn": "oman",             "mdv": "maldive",           "arm": "armenia",
    "geo": "georgia",          "kor": "corea del sud",     "cpv": "capo verde",
    "irn": "iran",             "xkx": "kosovo",            "ken": "kenya",
    "tza": "tanzania",         "twn": "taiwan",            "sgp": "singapore",
    "isr": "israele",          "jor": "giordania",         "ind": "india",
    "kwt": "kuwait",           "can": "canada",            "jpn": "giappone",
    "lbn": "libano",           "dza": "algeria",           "aze": "azerbaigian",
    "mkd": "macedonia",        "mne": "montenegro",        "atg": "antigua",
    "sen": "senegal",          "bhr": "bahrein",           "lby": "libia",
    "jam": "giamaica",         "mus": "mauritius",         "uzb": "uzbekistan",
    "sle": "sierra leone",     "kaz": "kazakistan",        "pak": "pakistan",
}

null_mask = df1["PAESE_PART"].isnull()
df1.loc[null_mask, "PAESE_PART"] = (
    df1.loc[null_mask, "CODICE_PAESE_PART"]
    .str.strip().str.lower()
    .map(codice_paese_map)
)

# Fallback: recover any remaining nulls from other rows sharing the same IATA code
iata_paese_from_data = (
    df1[df1["PAESE_PART"].notna()]
    .groupby("AREOPORTO_PARTENZA")["PAESE_PART"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df1["PAESE_PART"].isnull()
df1.loc[null_mask, "PAESE_PART"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_paese_from_data)
)

print(f"Null left PAESE_PART: {df1['PAESE_PART'].isnull().sum()}")
print(df1['PAESE_PART'].value_counts(dropna=False).head(30).to_string())

Nulls after placeholder cleanup: 203
Null left PAESE_PART: 0
PAESE_PART
regno unito            1759
albania                 612
turchia                 439
egitto                  285
marocco                 260
emirati arabi uniti     243
stati uniti             229
cina                    120
qatar                   105
tunisia                  86
serbia                   81
arabia saudita           77
brasile                  68
moldavia                 58
giordania                46
etiopia                  46
israele                  45
argentina                31
india                    31
armenia                  31
corea del sud            28
taiwan                   25
algeria                  25
oman                     23
kuwait                   23
singapore                22
canada                   18
georgia                  18
macedonia                17
maldive                  17

### Zona

In [109]:
print(f"Unique values: {df1['ZONA'].nunique()}")
print(f"Null values: {df1['ZONA'].isnull().sum()}")
print()
print(df1['ZONA'].value_counts(dropna=False).sort_index().to_string())

Unique values: 12
Null values: 0

ZONA
-1       3
1      177
10       1
2     1821
4      559
5     1457
6      210
7      143
8      575
9       78
99       1
??       5

In [110]:
# -1 is not a valid zone — treat it as missing before casting to integer.
df1["ZONA"] = df1["ZONA"].replace("-1", np.nan)
df1["ZONA"] = pd.to_numeric(df1["ZONA"], errors="coerce")
df1.loc[df1["ZONA"] == -1, "ZONA"] = np.nan   # catch numeric -1 if already parsed
df1["ZONA"] = df1["ZONA"].astype(pd.Int64Dtype())

print(f"Null left (were -1): {df1['ZONA'].isnull().sum()}")
print(f"dtype: {df1['ZONA'].dtype}")
print(df1["ZONA"].value_counts(dropna=False).sort_index().to_string())

Null left (were -1): 8
dtype: Int64
ZONA
1        177
2       1821
4        559
5       1457
6        210
7        143
8        575
9         78
10         1
99         1
<NA>       8

### TOT

In [111]:
print(f"Unique values: {df1['TOT'].nunique()}")
print(f"Null values: {df1['TOT'].isnull().sum()}")
print()
print(df1['TOT'].value_counts(dropna=False).head(20).to_string())

Unique values: 348
Null values: 0

TOT
1       2351
2        174
3        148
4        113
7         84
5         83
8         75
6         68
10        50
9         47
0         41
?         40
15        40
n.d.      35
16        34
12        32
11        32
14        31
18        28
13        27

In [112]:
# Cast to integer, recovering nulls from the duplicate column "tot voli" first.
df1["TOT"] = pd.to_numeric(df1["TOT"], errors="coerce")

null_mask = df1["TOT"].isnull()
print(f"Nulls after initial parse: {null_mask.sum()}")

df1.loc[null_mask, "TOT"] = pd.to_numeric(df1.loc[null_mask, "tot voli"], errors="coerce")
print(f"Nulls after recovery from 'tot voli': {df1['TOT'].isnull().sum()}")

# Null out impossible values: negatives and 99999 (error placeholder)
n_negative = (df1["TOT"] < 0).sum()
n_placeholder = (df1["TOT"] == 99999).sum()
df1.loc[df1["TOT"] < 0, "TOT"] = np.nan
df1.loc[df1["TOT"] == 99999, "TOT"] = np.nan
print(f"Nulled out: {n_negative} negative value(s), {n_placeholder} placeholder(s) (99999)")

# pd.to_numeric returns float64 (NaN forces floats); go through nullable Float64
# first so pandas can safely promote NA before converting to nullable Int64.
df1["TOT"] = df1["TOT"].astype("Float64").astype("Int64")

print(f"Null left: {df1['TOT'].isnull().sum()}")
print(f"dtype: {df1['TOT'].dtype}")
print(f"Min: {df1['TOT'].min()}  |  Max: {df1['TOT'].max()}  |  Mean: {df1['TOT'].mean():.1f}")

Nulls after initial parse: 155
Nulls after recovery from 'tot voli': 155
Nulled out: 7 negative value(s), 2 placeholder(s) (99999)
Null left: 164
dtype: Int64
Min: 0  |  Max: 10000  |  Mean: 44.6

### Motivo Allarme

In [113]:
print(f"Unique values: {df1['MOTIVO_ALLARME'].nunique()}")
print(f"Null values: {df1['MOTIVO_ALLARME'].isnull().sum()}")
print()
print(df1['MOTIVO_ALLARME'].value_counts(dropna=False).to_string())

Unique values: 5
Null values: 1143

MOTIVO_ALLARME
NaN         1143
tsc          812
sdi          810
manuale      773
nsis         755
interpol     737

In [114]:
# Standardise category labels.
motivo_map = {
    "sdi"      : "sdi",
    "nsis"     : "nsis",
    "sdi/nsis" : "sdi/nsis",
    "tsc"      : "tsc",
    "interpol" : "interpol",
    "bcs"      : "bcs",
    "manuale"  : "manuale",
}

df1["MOTIVO_ALLARME"] = df1["MOTIVO_ALLARME"].map(lambda x: motivo_map.get(str(x).strip(), np.nan) if pd.notna(x) else np.nan)

print(f"Null left: {df1['MOTIVO_ALLARME'].isnull().sum()}")
print(df1["MOTIVO_ALLARME"].value_counts(dropna=False).to_string())

Null left: 1143
MOTIVO_ALLARME
NaN         1143
tsc          812
sdi          810
manuale      773
nsis         755
interpol     737

### Note Operatore

In [115]:
print(f"Unique values: {df1['note_operatore'].nunique()}")
print(f"Null values: {df1['note_operatore'].isnull().sum()}  ({df1['note_operatore'].isnull().mean()*100:.1f}%)")
print()
print(df1['note_operatore'].value_counts(dropna=False).head(15).to_string())

Unique values: 4
Null values: 4954  (98.5%)

note_operatore
NaN                   4954
alert manuale           22
passeggero noto         20
doppio controllo        17
verifica richiesta      17

### Flag Rischio

In [116]:
print(f"Unique values: {df1['flag_rischio'].nunique()}")
print(f"Null values: {df1['flag_rischio'].isnull().sum()}  ({df1['flag_rischio'].isnull().mean()*100:.1f}%)")
print()
print(df1['flag_rischio'].value_counts(dropna=False).to_string())

Unique values: 2
Null values: 4980  (99.0%)

flag_rischio
NaN      4980
alto       26
medio      24

### Colonne Duplicate

In [117]:
# The duplicate columns may use different formatting (case, punctuation, encoding)
# from their cleaned counterparts. Normalise both sides before comparing.

def norm_str(s):
    """Lowercase, strip whitespace and trailing dots; treat null-like strings as empty."""
    if pd.isna(s):
        return ""
    s = str(s).strip().lower().rstrip(".")
    return "" if s in {"nan", "none", "n/a", "nd", "n.d.", "<na>"} else s

str_checks = [
    ("Paese Partenza",   "PAESE_PART"),
    ("CODICE PAESE ARR", "CODICE_PAESE_ARR"),
    ("paese%arr",        "PAESE_ARR"),
]

for dup, orig in str_checks:
    nd = df1[dup].map(norm_str)
    no = df1[orig].map(norm_str)
    n_mismatch = (nd != no).sum()
    print(f"'{dup}' ~= '{orig}':  {n_mismatch} mismatches out of {len(df1)}")
    if n_mismatch > 0 and n_mismatch <= 10:
        print(df1.loc[nd != no, [dup, orig]].to_string())
    elif n_mismatch > 10:
        print("  sample differences:")
        print(df1.loc[nd != no, [dup, orig]].head(5).to_string())

# Numeric check: tot voli (str) vs TOT (Int64)
n_mismatch_tot = (
    pd.to_numeric(df1["tot voli"], errors="coerce") != df1["TOT"].astype(float)
).sum()
print(f"\n'tot voli' ~= 'TOT':  {n_mismatch_tot} mismatches")

# Integer check: 3zona (int64) vs ZONA (Int64, -1 → NaN)
# For rows where ZONA is NA (was -1), '3zona' should have -1 → skip those
valid = df1["ZONA"].notna()
n_mismatch_zona = (df1.loc[valid, "3zona"] != df1.loc[valid, "ZONA"].astype(int)).sum()
na_zona = (~valid).sum()
print(f"'3zona' ~= 'ZONA':  {n_mismatch_zona} mismatches on valid rows  ({na_zona} rows had -1 → NaN)")

'Paese Partenza' ~= 'PAESE_PART':  10 mismatches out of 5030
           Paese Partenza     PAESE_PART
348   emirati arabi uniti  emirati arabi
553   emirati arabi uniti  emirati arabi
575   emirati arabi uniti  emirati arabi
1169  emirati arabi uniti  emirati arabi
1783  emirati arabi uniti  emirati arabi
2871  emirati arabi uniti  emirati arabi
3390  emirati arabi uniti  emirati arabi
3462  emirati arabi uniti  emirati arabi
3910  emirati arabi uniti  emirati arabi
4339  emirati arabi uniti  emirati arabi
'CODICE PAESE ARR' ~= 'CODICE_PAESE_ARR':  0 mismatches out of 5030
'paese%arr' ~= 'PAESE_ARR':  0 mismatches out of 5030

'tot voli' ~= 'TOT':  200 mismatches
'3zona' ~= 'ZONA':  2 mismatches on valid rows  (8 rows had -1 → NaN)

In [118]:
# Drop duplicate and redundant columns.
cols_to_drop = [
    # Original duplicate columns
    "Paese Partenza", "CODICE PAESE ARR", "3zona", "paese%arr", "tot voli",
    # Airport descriptions: redundant with IATA codes
    "DESCR_AEREOPORTO_ARR", "DESCR_AEREOPORTO_PART",
    # Arrival country: always "italia"/"ita" — zero variance
    "CODICE_PAESE_ARR", "PAESE_ARR",
    # Departure country: keep PAESE_PART, drop ISO-3 code
    "CODICE_PAESE_PART",
    # Date: ANNO and MESE are subsumed by DATA_PARTENZA (NaT rows already recovered above)
    "ANNO_PARTENZA", "MESE_PARTENZA",
]
df1.drop(columns=cols_to_drop, inplace=True)

print(f"Remaining columns ({df1.shape[1]}):")
print(df1.columns.tolist())

Remaining columns (12):
['OCCORRENZE', 'AREOPORTO_ARRIVO', 'AREOPORTO_PARTENZA', 'DATA_PARTENZA', 'CITTA_ARR', 'CITTA_PARTENZA', 'PAESE_PART', 'ZONA', 'TOT', 'MOTIVO_ALLARME', 'note_operatore', 'flag_rischio']

In [119]:
df1

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,DATA_PARTENZA,CITTA_ARR,CITTA_PARTENZA,PAESE_PART,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio
0,voli con allarmi,fco,ist,2024-01-30 09:15:00,roma,istanbul,turchia,5,1,manuale,NaN,NaN
1,viaggiatori con allarmi,cia,stn,2024-02-03 13:15:00,roma,londra,regno unito,5,5,manuale,NaN,NaN
2,viaggiatori entrati,fco,lhr,2024-01-15 08:45:00,roma,londra,regno unito,5,110,tsc,NaN,NaN
3,voli con allarmi,mxp,lhr,2024-02-02 08:40:00,milano,londra,regno unito,2,1,sdi,NaN,NaN
4,viaggiatori con allarmi,psa,brs,2024-02-16 12:50:00,pisa,bristol,regno unito,8,2,interpol,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5075,esito negativo,mxp,ltn,2024-01-19 17:30:00,milano,londra,regno unito,2,5,tsc,NaN,NaN
5076,voli disponibili,blq,rak,2024-02-01 00:00:00,bologna,marrakech,marocco,8,1,tsc,NaN,NaN
5077,voli con allarmi,fco,doh,2024-01-12 15:35:00,roma,doha,qatar,5,1,nsis,NaN,NaN
5078,voli solo visualizzati,lin,lhr,2024-01-13 11:50:00,milano,londra,regno unito,2,1,tsc,NaN,NaN
5079,voli investigati,psa,lgw,2024-02-26 13:30:00,pisa,londra,regno unito,8,1,tsc,NaN,NaN

# Tipologia Viaggiatore Dataset

First general look at the dataset (df2)

In [120]:
df2.shape

(5095, 33)

In [121]:
df2.head(5)

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571

In [122]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5095 entries, 0 to 5094
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NAZIONALITA            4979 non-null   str
 1   AREOPORTO_ARRIVO       5095 non-null   str
 2   AREOPORTO_PARTENZA     5095 non-null   str
 3   ANNO_PARTENZA          5095 non-null   str
 4   MESE_PARTENZA          5095 non-null   str
 5   GIORNO_PARTENZA        5095 non-null   int64
 6   DATA_PARTENZA          5095 non-null   str
 7   DESCR_AEREOPORTO_ARR   5095 non-null   str
 8   DESCR_AEREOPORTO_PART  5095 non-null   str
 9   CITTA_ARR              5095 non-null   str
 10  CITTA_PARTENZA         5095 non-null   str
 11  CODICE_PAESE_ARR       5095 non-null   str
 12  CODICE_PAESE_PART      5095 non-null   str
 13  PAESE_ARR              5095 non-null   str
 14  PAESE_PART             5095 non-null   str
 15  ZONA                   5095 non-null   str
 16  ENTRATI                5095 non-null   str
 17  INVESTIGATI            5095 non-null   str
 18  ALLARMATI              5095 non-null   str
 19  TIPO_DOCUMENTO         5033 non-null   str
 20  GENERE                 5050 non-null   str
 21  FASCIA_ETA             5095 non-null   str
 22  FLAG_TRANSITO          5095 non-null   str
 23  COMPAGNIA_AEREA        5008 non-null   str
 24  NUMERO_VOLO            5025 non-null   str
 25  ESITO_CONTROLLO        3806 non-null   str
 26  note_operatore         61 non-null     str
 27  codice_rischio         41 non-null     str
 28  Tipo Documento         5095 non-null   str
 29  FASCIA ETA             5095 non-null   str
 30  3nazionalita           5095 non-null   str
 31  compagnia%aerea        5095 non-null   str
 32  num volo               5095 non-null   str
dtypes: int64(1), str(32)
memory usage: 1.3 MB

In [123]:
# Normalize: lowercase and strip all string values
df2 = df2.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

print("Initial duplicates:", df2.duplicated().sum())
df2 = df2.drop_duplicates()
print("Duplicates after cleaning:", df2.duplicated().sum())
print(f"Shape: {df2.shape}")

Initial duplicates: 61
Duplicates after cleaning: 0
Shape: (5034, 33)

### NAZIONALITA

In [124]:
print(f"Unique values: {df2['NAZIONALITA'].nunique()}")
print(f"Null values: {df2['NAZIONALITA'].isnull().sum()}")
print()
print(df2['NAZIONALITA'].value_counts(dropna=False).to_string())

Unique values: 19
Null values: 112

NAZIONALITA
alb        4232
afg         380
NaN         112
ago          50
and          34
nd           34
-            31
?            28
n.d.         26
//           25
             24
unknown      24
are          19
zz            3
unk           3
xx            3
???           2
abw           2
aia           1
eu            1

In [125]:
# Replace placeholder values with NaN (keep valid ISO-3 codes)
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "unk", "zz", "none", "xx", "???"}

df2["NAZIONALITA"] = df2["NAZIONALITA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Null left: {df2['NAZIONALITA'].isnull().sum()}")
print(df2["NAZIONALITA"].value_counts(dropna=False).to_string())

Null left: 315
NAZIONALITA
alb    4232
afg     380
NaN     315
ago      50
and      34
are      19
abw       2
aia       1
eu        1

### Airport columns

In [126]:
print("--- AREOPORTO_ARRIVO ---")
print(f"Unique: {df2['AREOPORTO_ARRIVO'].nunique()}  |  Null: {df2['AREOPORTO_ARRIVO'].isnull().sum()}")
print(df2['AREOPORTO_ARRIVO'].value_counts(dropna=False).to_string())
print()
print("--- AREOPORTO_PARTENZA ---")
print(f"Unique: {df2['AREOPORTO_PARTENZA'].nunique()}  |  Null: {df2['AREOPORTO_PARTENZA'].isnull().sum()}")
print(df2['AREOPORTO_PARTENZA'].value_counts(dropna=False).to_string())

--- AREOPORTO_ARRIVO ---
Unique: 29  |  Null: 0
AREOPORTO_ARRIVO
mxp    1029
fco     870
bgy     672
blq     462
psa     281
vce     204
tsf     184
cta     158
trn     155
bri     154
cia     151
vrn     146
goa      95
nap      91
aoi      62
lin      55
peg      47
psr      43
flr      37
rmi      26
trs      24
bds      22
cag      20
pmo      17
suf      14
ciy      10
cuf       2
reg       2
pmf       1

--- AREOPORTO_PARTENZA ---
Unique: 177  |  Null: 0
AREOPORTO_PARTENZA
tia    2240
stn     502
lgw     261
saw     209
jfk     111
dxb     111
ist     109
man      87
lhr      84
ssh      83
ika      81
kbl      72
jed      70
ltn      54
mle      47
auh      37
bhx      34
skp      31
ewr      29
prn      29
lad      27
rak      27
brs      25
tgd      23
bkk      23
hkt      22
amm      21
ruh      18
mia      17
tun      16
rmf      16
shj      15
beg      15
cai      15
znz      14
yyz      14
rmo      14
isb      13
spx      13
cmn      13
lcy      12
mhd      12
doh      10
edi       9
mba       9
evn       9
pew       9
lrm       8
hrg       8
kut       7
adb       7
dps       7
pvg       7
can       7
bfs       6
gru       6
mru       6
mel       6
ncl       6
cgk       6
jax       6
del       6
kiv       6
kwi       6
ema       6
syd       6
gyd       5
pek       5
kul       5
dar       5
gig       5
dtw       5
ord       4
mex       4
sin       4
med       4
hnd       4
tlv       4
nrt       4
bos       4
iad       3
cle       3
dfw       3
mnl       3
icn       3
mct       3
skg       3
sgn       3
tpa       3
cun       3
hkg       3
han       2
lax       2
tfu       2
dwc       2
iah       2
pkx       2
tbs       2
dmm       2
yul       2
ayt       2
yvr       2
blr       2
esb       2
eze       2
ifn       2
nbo       2
vko       2
phl       2
dur       1
yyc       1
tas       1
sof       1
cvg       1
buf       1
gzt       1
elq       1
nav       1
sdu       1
ywg       1
poa       1
fll       1
bna       1
abj       1
bah       1
gla       1
mji       1
per       1
ssa       1
bne       1
smf       1
syz       1
bog       1
tsa       1
myr       1
fih       1
asm       1
svo       1
add       1
los       1
fez       1
mpm       1
yhz       1
syr       1
lpl       1
pvr       1
asb       1
nos       1
kzn       1
hgh       1
kch       1
fra       1
adl       1
yeg       1
skt       1
tpe       1
bsb       1
ceb       1
arn       1
rec       1
fuk       1
ala       1
sjj       1
tng       1
nsi       1
akl       1
las       1
oua       1
oxb       1
fru       1
aer       1
amd       1
szx       1
atl       1
alg       1
dss       1
scl       1

### ANNO_PARTENZA

In [127]:
print(f"Unique values: {df2['ANNO_PARTENZA'].nunique()}")
print(f"Null values: {df2['ANNO_PARTENZA'].isnull().sum()}")
print()
print(df2['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 4
Null values: 0

ANNO_PARTENZA
2024         4639
2023          251
24             72
anno 2024      72

In [128]:
def normalizza_anno(val):
    if pd.isna(val): return np.nan
    val = str(val).strip()
    match = re.search(r"\b(20\d{2})\b", val)
    if match: return int(match.group(1))
    match = re.search(r"\b(\d{2})\b", val)
    if match: return int("20" + match.group(1))
    return np.nan

df2["ANNO_PARTENZA"] = df2["ANNO_PARTENZA"].apply(normalizza_anno)
print(df2["ANNO_PARTENZA"].value_counts(dropna=False).to_string())

ANNO_PARTENZA
2024    4783
2023     251

### MESE_PARTENZA

In [129]:
print(f"Unique values: {df2['MESE_PARTENZA'].nunique()}")
print(f"Null values: {df2['MESE_PARTENZA'].isnull().sum()}")
print()
print(df2['MESE_PARTENZA'].value_counts(dropna=False).sort_index().to_string())

Unique values: 5
Null values: 0

MESE_PARTENZA
01     2598
02     2282
12        1
feb      60
gen      93

In [130]:
mesi_map = {"gen": "01", "feb": "02"}
df2["MESE_PARTENZA"] = df2["MESE_PARTENZA"].replace(mesi_map)

print(df2["MESE_PARTENZA"].value_counts(dropna=False).sort_index().to_string())

MESE_PARTENZA
01    2691
02    2342
12       1

### GIORNO_PARTENZA

In [131]:
df2["GIORNO_PARTENZA"] = pd.to_numeric(df2["GIORNO_PARTENZA"], errors="coerce")

print(f"Unique values: {df2['GIORNO_PARTENZA'].nunique()}")
print(f"Null values: {df2['GIORNO_PARTENZA'].isnull().sum()}")
print(f"Min: {df2['GIORNO_PARTENZA'].min()}  |  Max: {df2['GIORNO_PARTENZA'].max()}")
print()

# Flag invalid days (outside 1-31)
invalid = df2[(df2["GIORNO_PARTENZA"] < 1) | (df2["GIORNO_PARTENZA"] > 31)]
print(f"Invalid day values: {len(invalid)}")
print(df2["GIORNO_PARTENZA"].value_counts(dropna=False).sort_index().to_string())

Unique values: 31
Null values: 0
Min: 1  |  Max: 31

Invalid day values: 0
GIORNO_PARTENZA
1     168
2     191
3     177
4     190
5     167
6     190
7     177
8     158
9     167
10    162
11    179
12    171
13    190
14    178
15    155
16    176
17    152
18    171
19    174
20    176
21    148
22    151
23    168
24    171
25    155
26    170
27    174
28    138
29    150
30     76
31     64

In [132]:
# Null out invalid day values
n_invalid = ((df2["GIORNO_PARTENZA"] < 1) | (df2["GIORNO_PARTENZA"] > 31)).sum()
df2.loc[(df2["GIORNO_PARTENZA"] < 1) | (df2["GIORNO_PARTENZA"] > 31), "GIORNO_PARTENZA"] = np.nan
df2["GIORNO_PARTENZA"] = df2["GIORNO_PARTENZA"].astype("Int64")
print(f"Nulled {n_invalid} invalid day(s). Null left: {df2['GIORNO_PARTENZA'].isnull().sum()}")

Nulled 0 invalid day(s). Null left: 0

### DATA_PARTENZA

In [133]:
print(f"Unique values: {df2['DATA_PARTENZA'].nunique()}")
print(f"Null values: {df2['DATA_PARTENZA'].isnull().sum()}")
print()
print(df2['DATA_PARTENZA'].value_counts(dropna=False).head(15).to_string())

Unique values: 3977
Null values: 0

DATA_PARTENZA
2024-02-11 16:55:00    7
2024-01-14 16:55:00    7
2024-01-21 16:55:00    6
2024-01-28 16:55:00    6
2024-01-10 05:35:00    6
2024-02-18 16:55:00    5
feb 10 2024            5
24.01.2024             5
2024-01-03 08:55:00    5
gen 18 2024            5
2024-01-09 05:35:00    5
2024-02-13 05:35:00    5
2024-01-02 05:35:00    5
2024-01-09 15:45:00    5
2024-02-03 19:50:00    5

In [134]:
mesi_ita = {
    "GEN": "01", "FEB": "02", "MAR": "03", "APR": "04",
    "MAG": "05", "GIU": "06", "LUG": "07", "AGO": "08",
    "SET": "09", "OTT": "10", "NOV": "11", "DIC": "12"
}

def normalizza_data(val):
    val = str(val).strip()

    # "GEN 06 2024" → "2024-01-06 00:00:00"
    for ita, num in mesi_ita.items():
        if val.upper().startswith(ita + " "):
            parts = val.split(" ")
            return f"{parts[2]}-{num}-{parts[1].zfill(2)} 00:00:00"

    val = val.replace("T", " ")

    if re.match(r"\d{4}/\d{2}/\d{2}", val):
        val = val.replace("/", "-")
        if len(val) == 10:
            val += " 00:00:00"

    match = re.match(r"(\d{2})\.(\d{2})\.(\d{4})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    match = re.match(r"(\d{2})-(\d{2})-(\d{2})$", val)
    if match:
        return f"20{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    match = re.match(r"(\d{2})/(\d{2})/(\d{4})\s(\d{2}:\d{2}:\d{2})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} {match.group(4)}"

    return val

df2["DATA_PARTENZA"] = df2["DATA_PARTENZA"].apply(normalizza_data)
df2["DATA_PARTENZA"] = pd.to_datetime(df2["DATA_PARTENZA"], errors="coerce")

# Recover NaT using ANNO + MESE + GIORNO (full date available in df2)
nat_mask = df2["DATA_PARTENZA"].isnull()
df2.loc[nat_mask, "DATA_PARTENZA"] = pd.to_datetime(
    df2.loc[nat_mask, "ANNO_PARTENZA"].astype(str) + "-" +
    df2.loc[nat_mask, "MESE_PARTENZA"].astype(str).str.zfill(2) + "-" +
    df2.loc[nat_mask, "GIORNO_PARTENZA"].astype(str).str.zfill(2),
    errors="coerce"
)

print(f"NaT left: {df2['DATA_PARTENZA'].isnull().sum()}")
print(f"Range: {df2['DATA_PARTENZA'].min()} → {df2['DATA_PARTENZA'].max()}")

NaT left: 0
Range: 2023-01-14 00:00:00 → 2024-02-29 21:55:00

### Airport descriptions (DESCR_AEREOPORTO_ARR / DESCR_AEREOPORTO_PART)

In [135]:
print("--- DESCR_AEREOPORTO_ARR ---")
print(f"Unique: {df2['DESCR_AEREOPORTO_ARR'].nunique()}  |  Null: {df2['DESCR_AEREOPORTO_ARR'].isnull().sum()}")
print()
print("--- DESCR_AEREOPORTO_PART ---")
print(f"Unique: {df2['DESCR_AEREOPORTO_PART'].nunique()}  |  Null: {df2['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print()
print("Both will be dropped — redundant with IATA codes.")

--- DESCR_AEREOPORTO_ARR ---
Unique: 29  |  Null: 0

--- DESCR_AEREOPORTO_PART ---
Unique: 176  |  Null: 0

Both will be dropped — redundant with IATA codes.

### CITTA_ARR and CITTA_PARTENZA

In [136]:
print("--- CITTA_ARR ---")
print(f"Unique: {df2['CITTA_ARR'].nunique()}  |  Null: {df2['CITTA_ARR'].isnull().sum()}")
print(df2['CITTA_ARR'].value_counts(dropna=False).to_string())
print()
print("--- CITTA_PARTENZA ---")
print(f"Unique: {df2['CITTA_PARTENZA'].nunique()}  |  Null: {df2['CITTA_PARTENZA'].isnull().sum()}")
print(df2['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

--- CITTA_ARR ---
Unique: 27  |  Null: 0
CITTA_ARR
milano             1084
roma               1021
bergamo             672
bologna             462
pisa                281
venezia             204
treviso             184
catania             158
torino              155
bari                154
verona              146
genova               95
napoli               91
ancona               62
perugia              47
pescara              43
firenze              37
rimini               26
trieste              24
brindisi             22
cagliari             20
palermo              17
lamezia terme        14
comiso               10
cuneo                 2
reggio calabria       2
parma                 1

--- CITTA_PARTENZA ---
Unique: 165  |  Null: 0
CITTA_PARTENZA
tirana               2240
londra                913
istanbul              318
dubai                 113
new york              111
manchester             87
sharm el sheikh        83
tehran                 81
kabul                  72
jeddah                 70
male                   47
abu dhabi              37
birmingham             34
skopie                 31
newark                 29
pristina               29
luanda                 27
marrakech              27
bristol                25
podgorica              23
bangkok                23
phuket                 22
amman                  21
chisinau               20
riyadh                 18
miami                  17
tunis                  16
marsa alam             16
sharjah                15
belgrado               15
cairo                  15
zanzibar               14
toronto                14
islamabad              13
giza                   13
casablanca             13
mashad                 12
doha                   10
edinburgh               9
mombasa                 9
yerevan                 9
peshawar                9
la romana               8
hurghada                8
tokyo                   8
kutaisi                 7
smirne                  7
denpasar                7
pechino                 7
shanghai                7
guangzhou               7
belfast                 6
san paolo               6
plaisance               6
melbourne               6
newcastle               6
giacarta                6
rio de janeiro          6
jacksonville            6
nuova delhi             6
kuwait city             6
derby                   6
sidney                  6
baku                    5
kuala lumpur            5
dar es salaam           5
detroit                 5
chicago                 4
citta del messico       4
singapore               4
madinah                 4
tel aviv yafo           4
boston                  4
washington              3
cleveland               3
dallas-fort worth       3
manila                  3
seoul                   3
muscat                  3
thessaloniki            3
ho chi minh city        3
tampa                   3
cancun                  3
mosca                   3
hong kong               3
hanoi                   2
los angeles             2
chengdu                 2
taipei                  2
houston                 2
tbilisi                 2
dammam                  2
montreal                2
antalya                 2
vancouver               2
bangalore               2
ankara                  2
buenos aires            2
isfahan                 2
nairobi                 2
filadelfia              2
durban                  1
calgary                 1
tashkent                1
sofia                   1
cincinnati              1
buffalo                 1
gaziantep               1
buraidah                1
nevsehir                1
winnipeg                1
porto alegre            1
fort lauderdale         1
nashville               1
abidjan                 1
manama                  1
glasgow                 1
tripoli                 1
perth                   1
salvador                1
brisbane                1
sacramento              1
shiraz                  1
bogota                  1
myrtle beach            1
kinshasa                1
asmara                  1
addis ababa             1
lagos                   1
fes                     1
maputo                  1
halifax                 1
syracuse                1
liverpool               1
puerto vallarta         1
ashgabat                1
nosy-be                 1
kazan                   1
hangzhou                1
kuching                 1
francoforte             1
adelaide                1
edmonton                1
sialkot                 1
brasilia                1
cebu                    1
stoccolma               1
recife                  1
fukuoka                 1
almaty                  1
sarajevo                1
tangier                 1
yaounde                 1
auckland                1
las vegas               1
ouagadougou             1
bissau                  1
bishkek                 1
sochi                   1
ahmedabad               1
shenzhen                1
atlanta                 1
algeri                  1
dakar                   1
santiago                1

In [137]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "anu", "none"}

df2["CITTA_PARTENZA"] = df2["CITTA_PARTENZA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df2['CITTA_PARTENZA'].isnull().sum()}")

# Recover nulls via IATA → city lookup (same dictionary as df1)
iata_city = {
    "tia": "tirana",   "stn": "londra",    "lgw": "londra",   "lhr": "londra",
    "lcy": "londra",   "ltn": "londra",    "bqh": "londra",   "fab": "londra",
    "ist": "istanbul", "dxb": "dubai",     "cai": "il cairo", "saw": "istanbul",
    "cmn": "casablanca","doh": "doha",     "rak": "marrakech","jfk": "new york",
    "ssh": "sharm el-sheikh","tun": "tunisi","beg": "belgrado","auh": "abu dhabi",
    "ewr": "new york", "jed": "jeddah",    "edi": "edinburgo","gru": "san paolo",
    "eze": "buenos aires","add": "addis abeba","mex": "citta del messico",
    "pek": "pechino",  "rmo": "chisinau",  "bhx": "birmingham","pvg": "shanghai",
    "hkg": "hong kong","mct": "muscat",    "mle": "male",     "rba": "rabat",
    "evn": "yerevan",  "tbs": "tbilisi",   "ema": "east midlands","ruh": "riad",
    "shj": "sharjah",  "gla": "glasgow",   "icn": "seul",     "rmf": "marsa alam",
    "tng": "tangeri",  "sid": "praia",     "spx": "cairo",    "ika": "teheran",
    "prn": "pristina", "mba": "mombasa",   "szx": "shenzhen", "mia": "miami",
    "tpe": "taipei",   "sin": "singapore", "tlv": "tel aviv", "amm": "amman",
    "brs": "bristol",  "man": "manchester","anu": "saint john's","ncl": "newcastle",
    "del": "nuova delhi","atl": "atlanta", "kwi": "kuwait",   "dfw": "dallas",
    "iad": "washington","yul": "montreal", "yyz": "toronto",  "hnd": "tokyo",
    "bey": "beirut",   "alg": "algeri",    "kiv": "chisinau", "gyd": "baku",
    "lpl": "liverpool","skp": "skopje",    "tgd": "podgorica","phl": "filadelfia",
    "fez": "fez",      "gig": "rio de janeiro","atq": "amritsar","znz": "zanzibar",
    "nkg": "nanchino", "aga": "agadir",    "mji": "misurata", "dmm": "dammam",
    "ckg": "chongqing","bfs": "belfast",   "bos": "boston",   "lxr": "luxor",
    "can": "guangzhou","wnz": "wenzhou",   "hgh": "hangzhou", "bah": "manama",
    "dss": "dakar",    "kut": "kutaisi",   "hrg": "hurghada", "oak": "oakland",
    "lax": "los angeles","oxf": "oxford",  "lba": "leeds",    "ala": "almaty",
    "mbj": "montego bay","cun": "cancun",  "mru": "port louis","tas": "tashkent",
    "cgo": "zhengzhou","tfu": "chengdu",  "nht": "londra",
}

null_mask = df2["CITTA_PARTENZA"].isnull()
df2.loc[null_mask, "CITTA_PARTENZA"] = (
    df2.loc[null_mask, "AREOPORTO_PARTENZA"].str.strip().str.lower().map(iata_city)
)

# Fallback: data-driven lookup from other rows
iata_city_from_data = (
    df2[df2["CITTA_PARTENZA"].notna()]
    .groupby("AREOPORTO_PARTENZA")["CITTA_PARTENZA"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df2["CITTA_PARTENZA"].isnull()
df2.loc[null_mask, "CITTA_PARTENZA"] = (
    df2.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_city_from_data)
)

print(f"Null left: {df2['CITTA_PARTENZA'].isnull().sum()}")
print(f"Unique values: {df2['CITTA_PARTENZA'].nunique()}")

Nulls after placeholder cleanup: 0
Null left: 0
Unique values: 165

### Country columns

In [138]:
print("--- CODICE_PAESE_ARR ---")
print(f"Unique: {df2['CODICE_PAESE_ARR'].nunique()}  |  Null: {df2['CODICE_PAESE_ARR'].isnull().sum()}")
print(df2['CODICE_PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- CODICE_PAESE_PART ---")
print(f"Unique: {df2['CODICE_PAESE_PART'].nunique()}  |  Null: {df2['CODICE_PAESE_PART'].isnull().sum()}")
print(df2['CODICE_PAESE_PART'].value_counts(dropna=False).head(20).to_string())

--- CODICE_PAESE_ARR ---
Unique: 2  |  Null: 0
CODICE_PAESE_ARR
ita    4780
it      254

--- CODICE_PAESE_PART ---
Unique: 82  |  Null: 0
CODICE_PAESE_PART
alb    2132
gbr    1035
tur     307
usa     203
are     156
egy     124
al      108
irn      96
sau      95
afg      72
gb       53
mdv      47
tha      45
mar      39
mkd      31
rks      29
ago      27
chn      25
tr       24
mne      23

In [139]:
# CODICE_PAESE_ARR: always Italy — overwrite all variants with "ita"
n_wrong = (df2["CODICE_PAESE_ARR"] != "ita").sum()
print(f"Rows with non-'ita' value: {n_wrong}")
df2["CODICE_PAESE_ARR"] = "ita"

Rows with non-'ita' value: 254

In [140]:
print("--- PAESE_ARR ---")
print(f"Unique: {df2['PAESE_ARR'].nunique()}  |  Null: {df2['PAESE_ARR'].isnull().sum()}")
print(df2['PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- PAESE_PART ---")
print(f"Unique: {df2['PAESE_PART'].nunique()}  |  Null: {df2['PAESE_PART'].isnull().sum()}")
print(df2['PAESE_PART'].value_counts(dropna=False).head(20).to_string())

--- PAESE_ARR ---
Unique: 1  |  Null: 0
PAESE_ARR
italia    5034

--- PAESE_PART ---
Unique: 76  |  Null: 0
PAESE_PART
albania                2240
regno unito            1088
turchia                 331
stati uniti             203
emirati arabi uniti     165
egitto                  135
iran                     96
arabia saudita           95
afghanistan              72
maldive                  47
thailandia               45
marocco                  42
macedonia                31
cossovo                  29
angola                   27
cina                     25
montenegro               23
pakistan                 23
canada                   22
giordania                21

In [141]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "anu", "none"}

df2["PAESE_PART"] = df2["PAESE_PART"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df2['PAESE_PART'].isnull().sum()}")

codice_paese_map = {
    "alb": "albania",          "gbr": "regno unito",      "tur": "turchia",
    "are": "emirati arabi",    "egy": "egitto",            "mar": "marocco",
    "qat": "qatar",            "usa": "stati uniti",       "tun": "tunisia",
    "srb": "serbia",           "sau": "arabia saudita",    "bra": "brasile",
    "arg": "argentina",        "eth": "etiopia",           "mex": "messico",
    "chn": "cina",             "mda": "moldavia",          "hkg": "hong kong",
    "omn": "oman",             "mdv": "maldive",           "arm": "armenia",
    "geo": "georgia",          "kor": "corea del sud",     "cpv": "capo verde",
    "irn": "iran",             "xkx": "kosovo",            "ken": "kenya",
    "tza": "tanzania",         "twn": "taiwan",            "sgp": "singapore",
    "isr": "israele",          "jor": "giordania",         "ind": "india",
    "kwt": "kuwait",           "can": "canada",            "jpn": "giappone",
    "lbn": "libano",           "dza": "algeria",           "aze": "azerbaigian",
    "mkd": "macedonia",        "mne": "montenegro",        "atg": "antigua",
    "sen": "senegal",          "bhr": "bahrein",           "lby": "libia",
    "jam": "giamaica",         "mus": "mauritius",         "uzb": "uzbekistan",
    "sle": "sierra leone",     "kaz": "kazakistan",        "pak": "pakistan",
    "afg": "afghanistan",      "tha": "thailandia",        "npl": "nepal",
    "phl": "filippine",        "lka": "sri lanka",         "bgd": "bangladesh",
    "nga": "nigeria",          "cmr": "camerun",           "gha": "ghana",
    "civ": "costa d'avorio",  "mli": "mali",              "gin": "guinea",
}

null_mask = df2["PAESE_PART"].isnull()
df2.loc[null_mask, "PAESE_PART"] = (
    df2.loc[null_mask, "CODICE_PAESE_PART"].str.strip().str.lower().map(codice_paese_map)
)

# Fallback: data-driven lookup
iata_paese_from_data = (
    df2[df2["PAESE_PART"].notna()]
    .groupby("AREOPORTO_PARTENZA")["PAESE_PART"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df2["PAESE_PART"].isnull()
df2.loc[null_mask, "PAESE_PART"] = (
    df2.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_paese_from_data)
)

print(f"Null left PAESE_PART: {df2['PAESE_PART'].isnull().sum()}")
print(df2["PAESE_PART"].value_counts(dropna=False).head(20).to_string())

Nulls after placeholder cleanup: 0
Null left PAESE_PART: 0
PAESE_PART
albania                2240
regno unito            1088
turchia                 331
stati uniti             203
emirati arabi uniti     165
egitto                  135
iran                     96
arabia saudita           95
afghanistan              72
maldive                  47
thailandia               45
marocco                  42
macedonia                31
cossovo                  29
angola                   27
cina                     25
montenegro               23
pakistan                 23
canada                   22
giordania                21

### ZONA

In [142]:
print(f"Unique values: {df2['ZONA'].nunique()}")
print(f"Null values: {df2['ZONA'].isnull().sum()}")
print()
print(df2['ZONA'].value_counts(dropna=False).sort_index().to_string())

Unique values: 13
Null values: 0

ZONA
-1       3
0        4
1      252
10       1
2     1752
4      557
5     1087
6      106
7      184
8      867
9      219
99       1
??       1

In [143]:
# -1 is not a valid zone — treat as missing before casting
df2["ZONA"] = df2["ZONA"].replace("-1", np.nan)
df2["ZONA"] = pd.to_numeric(df2["ZONA"], errors="coerce")
df2.loc[df2["ZONA"] == -1, "ZONA"] = np.nan
df2["ZONA"] = df2["ZONA"].astype(pd.Int64Dtype())

print(f"Null left (were -1): {df2['ZONA'].isnull().sum()}")
print(f"dtype: {df2['ZONA'].dtype}")
print(df2["ZONA"].value_counts(dropna=False).sort_index().to_string())

Null left (were -1): 4
dtype: Int64
ZONA
0          4
1        252
2       1752
4        557
5       1087
6        106
7        184
8        867
9        219
10         1
99         1
<NA>       4

### ENTRATI, INVESTIGATI, ALLARMATI

In [144]:
for col in ["ENTRATI", "INVESTIGATI", "ALLARMATI"]:
    print(f"--- {col} ---")
    print(f"Unique: {df2[col].nunique()}  |  Null: {df2[col].isnull().sum()}")
    print(df2[col].value_counts(dropna=False).head(10).to_string())
    print()

--- ENTRATI ---
Unique: 251  |  Null: 0
ENTRATI
1       1866
2        509
3        185
4         96
5         62
n.d.      45
?         39
6         27
91        27
82        26

--- INVESTIGATI ---
Unique: 251  |  Null: 0
INVESTIGATI
1       1682
2        487
0        254
3        197
4        120
5         56
n.d.      50
?         33
6         29
91        27

--- ALLARMATI ---
Unique: 146  |  Null: 0
ALLARMATI
0     2071
1      665
2      150
4      119
3      111
6      106
10     103
7      100
5       99
12      99

In [145]:
# Cast to nullable integer — non-numeric placeholders become NaN
for col in ["ENTRATI", "INVESTIGATI", "ALLARMATI"]:
    df2[col] = pd.to_numeric(df2[col], errors="coerce").astype("Float64").astype("Int64")

# Null out negative values (impossible counts)
for col in ["ENTRATI", "INVESTIGATI", "ALLARMATI"]:
    n_neg = (df2[col] < 0).sum()
    df2.loc[df2[col] < 0, col] = pd.NA
    print(f"{col}: Null={df2[col].isnull().sum()}  Min={df2[col].min()}  Max={df2[col].max()}  (nulled {n_neg} negative(s))")

ENTRATI: Null=203  Min=0  Max=10000  (nulled 3 negative(s))
INVESTIGATI: Null=203  Min=0  Max=9999  (nulled 3 negative(s))
ALLARMATI: Null=203  Min=0  Max=5000  (nulled 3 negative(s))

### TIPO_DOCUMENTO

In [146]:
print(f"Unique values: {df2['TIPO_DOCUMENTO'].nunique()}")
print(f"Null values: {df2['TIPO_DOCUMENTO'].isnull().sum()}")
print()
print(df2['TIPO_DOCUMENTO'].value_counts(dropna=False).to_string())

Unique values: 11
Null values: 62

TIPO_DOCUMENTO
n.d.                     1607
visto                     848
permesso di soggiorno     820
passaporto                798
carta d'identità          775
NaN                        62
?                          29
unknown                    29
//                         21
nd                         17
-                          14
                           14

In [147]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none"}

df2["TIPO_DOCUMENTO"] = df2["TIPO_DOCUMENTO"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

# Recover nulls from duplicate column "Tipo Documento"
null_mask = df2["TIPO_DOCUMENTO"].isnull()
recovered = df2.loc[null_mask, "Tipo Documento"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else str(x).strip().lower()
)
df2.loc[null_mask, "TIPO_DOCUMENTO"] = recovered

print(f"Null left: {df2['TIPO_DOCUMENTO'].isnull().sum()}")
print(df2["TIPO_DOCUMENTO"].value_counts(dropna=False).to_string())

Null left: 1659
TIPO_DOCUMENTO
NaN                      1659
visto                     876
permesso di soggiorno     859
passaporto                831
carta d'identità          809

### GENERE

In [148]:
print(f"Unique values: {df2['GENERE'].nunique()}")
print(f"Null values: {df2['GENERE'].isnull().sum()}")
print()
print(df2['GENERE'].value_counts(dropna=False).to_string())

Unique values: 18
Null values: 44

GENERE
f          2116
m          2114
n.d.        491
female       54
NaN          44
male         32
femmina      29
maschio      24
2            22
//           18
?            17
             16
1            15
-            14
nd           14
unknown       7
x             3
unkn          2
n/b           2

In [149]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none"}

genere_map = {
    "f": "f", "female": "f", "femmina": "f", "2": "f",
    "m": "m", "male": "m",   "maschio": "m", "1": "m",
}

df2["GENERE"] = df2["GENERE"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
    else genere_map.get(str(x).strip(), np.nan)
)

print(f"Null left: {df2['GENERE'].isnull().sum()}")
print(df2["GENERE"].value_counts(dropna=False).to_string())

Null left: 628
GENERE
f      2221
m      2185
NaN     628

### FASCIA_ETA

In [150]:
print(f"Unique values: {df2['FASCIA_ETA'].nunique()}")
print(f"Null values: {df2['FASCIA_ETA'].isnull().sum()}")
print()
print(df2['FASCIA_ETA'].value_counts(dropna=False).to_string())

Unique values: 11
Null values: 0

FASCIA_ETA
46-60     931
31-45     910
18-30     903
0-17      894
61+       872
n.d.      516
-5          3
n/c         2
minore      1
adulto      1
101+        1

In [151]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none", "n/c", "adulto"}

fascia_map = {
    "minore": "0-17",   # minore = under 18
}

df2["FASCIA_ETA"] = df2["FASCIA_ETA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
    else fascia_map.get(str(x).strip(), str(x).strip())
)

# Null out clearly invalid values (negative ages)
df2.loc[df2["FASCIA_ETA"].str.startswith("-", na=False), "FASCIA_ETA"] = np.nan

print(f"Null left: {df2['FASCIA_ETA'].isnull().sum()}")
print(df2["FASCIA_ETA"].value_counts(dropna=False).to_string())

Null left: 522
FASCIA_ETA
46-60    931
31-45    910
18-30    903
0-17     895
61+      872
NaN      522
101+       1

### FLAG_TRANSITO

In [152]:
print(f"Unique values: {df2['FLAG_TRANSITO'].nunique()}")
print(f"Null values: {df2['FLAG_TRANSITO'].isnull().sum()}")
print()
print(df2['FLAG_TRANSITO'].value_counts(dropna=False).to_string())

# Replace n/c with NaN
df2["FLAG_TRANSITO"] = df2["FLAG_TRANSITO"].replace("n/c", np.nan)
print(f"\nNull after n/c cleanup: {df2['FLAG_TRANSITO'].isnull().sum()}")

Unique values: 5
Null values: 0

FLAG_TRANSITO
singola tratta    5020
multitratta          6
transito             4
tripla tratta        3
n/c                  1

Null after n/c cleanup: 1

### COMPAGNIA_AEREA

In [153]:
print(f"Unique values: {df2['COMPAGNIA_AEREA'].nunique()}")
print(f"Null values: {df2['COMPAGNIA_AEREA'].isnull().sum()}")
print()
print(df2['COMPAGNIA_AEREA'].value_counts(dropna=False).to_string())

Unique values: 79
Null values: 86

COMPAGNIA_AEREA
wizz air malta             1707
ryanair dac                1064
turkish airlines            260
ita airways                 248
pegasus airlines            153
easyjet                     133
emirates                    126
british airways             106
fly dubai                    89
NaN                          86
air albania                  84
easyjet europe               81
qatar airways                73
neos s.p.a.                  72
etihad airways               55
albawings                    41
wizz air hungary             38
delta air lines              36
united airlines              33
ethiopian airlines           30
air serbia                   29
-                            29
                             29
american airlines            28
?                            23
//                           22
iran air                     22
nd                           22
unknown                      22
air arabia                   20
n.d.                         20
vueling airlines             20
air canada                   19
jet2.com                     16
air china                    14
saudi arabian airlines       12
china eastern airlines       12
wizz air abu dhabi           12
royal air maroc              10
air cairo                     9
oman air                      9
flyone                        9
hisky europe                  8
egyptair                      7
singapore airlines            6
kuwait airways                5
latam airlines brasil         5
air arabia egypt              5
air arabia maroc              5
china southern airlines       5
gulf air                      5
cathay pacific airways        5
air montenegro                4
aeromexico                    4
sichuan airlines              4
ryanair uk                    3
sunexpress                    3
nouvelair tunisie             3
eva air                       3
el al israel airlines         3
compagnia x                   3
??                            2
flyone armenia                2
albastar                      2
tunisair                      2
korean airlines               2
air algerie                   2
freebird airlines             1
tuifly belgium                1
medsky airways                1
air india                     1
null                          1
georgian airways              1
air emeralds                  1
tui airways                   1
china airlines                1
dreamjet                      1
aerolineas argentinas         1
charter                       1
hainan airlines               1

In [154]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null",
                    "none", "??", "compagnia x", "charter"}

df2["COMPAGNIA_AEREA"] = df2["COMPAGNIA_AEREA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

# Recover nulls from duplicate column "compagnia%aerea"
null_mask = df2["COMPAGNIA_AEREA"].isnull()
df2.loc[null_mask, "COMPAGNIA_AEREA"] = (
    df2.loc[null_mask, "compagnia%aerea"]
    .apply(lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
           else str(x).strip().lower())
)

print(f"Null left: {df2['COMPAGNIA_AEREA'].isnull().sum()}")
print(df2["COMPAGNIA_AEREA"].value_counts(dropna=False).head(15).to_string())

Null left: 0
COMPAGNIA_AEREA
wizz air malta      1800
ryanair dac         1129
turkish airlines     271
ita airways          260
pegasus airlines     160
easyjet              140
emirates             135
british airways      111
fly dubai             93
air albania           86
easyjet europe        86
qatar airways         80
neos s.p.a.           75
etihad airways        56
albawings             43

### NUMERO_VOLO

In [155]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none"}

df2["NUMERO_VOLO"] = df2["NUMERO_VOLO"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

# Recover nulls from duplicate column "num volo"
null_mask = df2["NUMERO_VOLO"].isnull()
df2.loc[null_mask, "NUMERO_VOLO"] = (
    df2.loc[null_mask, "num volo"]
    .apply(lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
           else str(x).strip().lower())
)

print(f"Null left: {df2['NUMERO_VOLO'].isnull().sum()}")

# Flag flight numbers with inconsistent routes (data quality check)
consistency = (
    df2[df2["NUMERO_VOLO"].notna()]
    .groupby("NUMERO_VOLO")
    .agg(arr_unique=("AREOPORTO_ARRIVO", "nunique"),
         part_unique=("AREOPORTO_PARTENZA", "nunique"))
)
inconsistent = consistency[(consistency["arr_unique"] > 1) | (consistency["part_unique"] > 1)]
print(f"\nFlight numbers with inconsistent routes: {len(inconsistent)} (flagged, not modified)")
print(inconsistent.head(10).to_string())

Null left: 0

Flight numbers with inconsistent routes: 121 (flagged, not modified)
             arr_unique  part_unique
NUMERO_VOLO
3u3895                1            3
5f0295                1            2
aa0198                1            7
aa0240                1            2
aa0718                1            2
ac0890                1            4
ac0892                1            4
ac0894                1            4
ah2026                1            2
am0070                2            1

### ESITO_CONTROLLO

In [156]:
print(f"Unique values: {df2['ESITO_CONTROLLO'].nunique()}")
print(f"Null values: {df2['ESITO_CONTROLLO'].isnull().sum()}  ({df2['ESITO_CONTROLLO'].isnull().mean()*100:.1f}%)")
print()
print(df2['ESITO_CONTROLLO'].value_counts(dropna=False).to_string())

Unique values: 5
Null values: 1277  (25.4%)

ESITO_CONTROLLO
NaN          1277
segnalato     797
in attesa     777
respinto      763
fermato       713
ok            707

### note_operatore and codice_rischio

In [157]:
print(f"note_operatore:  {df2['note_operatore'].isnull().sum()} nulls  ({df2['note_operatore'].isnull().mean()*100:.1f}%)")
print(df2['note_operatore'].value_counts(dropna=False).head(10).to_string())
print()
print(f"codice_rischio:  {df2['codice_rischio'].isnull().sum()} nulls  ({df2['codice_rischio'].isnull().mean()*100:.1f}%)")
print(df2['codice_rischio'].value_counts(dropna=False).head(10).to_string())

note_operatore:  4974 nulls  (98.8%)
note_operatore
NaN                     4974
verifica richiesta        18
alert manuale             16
segnalazione esterna      16
passeggero noto           10

codice_rischio:  4993 nulls  (99.2%)
codice_rischio
NaN    4993
r3       18
r2       14
r1        9

### Cross-check duplicate columns

In [158]:
def norm_str(s):
    if pd.isna(s): return ""
    s = str(s).strip().lower().rstrip(".")
    return "" if s in {"nan", "none", "n/a", "nd", "n.d.", "<na>"} else s

dup_checks = [
    ("Tipo Documento",  "TIPO_DOCUMENTO"),
    ("FASCIA ETA",      "FASCIA_ETA"),
    ("3nazionalita",    "NAZIONALITA"),
    ("compagnia%aerea", "COMPAGNIA_AEREA"),
    ("num volo",        "NUMERO_VOLO"),
]

for dup, orig in dup_checks:
    nd = df2[dup].map(norm_str)
    no = df2[orig].map(norm_str)
    n_mismatch = (nd != no).sum()
    print(f"'{dup}' ~= '{orig}':  {n_mismatch} mismatches out of {len(df2)}")
    if 0 < n_mismatch <= 10:
        print(df2.loc[nd != no, [dup, orig]].to_string())
    elif n_mismatch > 10:
        print("  sample differences:")
        print(df2.loc[nd != no, [dup, orig]].head(5).to_string())

'Tipo Documento' ~= 'TIPO_DOCUMENTO':  1659 mismatches out of 5034
  sample differences:
   Tipo Documento TIPO_DOCUMENTO
2            n.d.            NaN
3            n.d.            NaN
8            n.d.            NaN
11           n.d.            NaN
13           n.d.            NaN
'FASCIA ETA' ~= 'FASCIA_ETA':  523 mismatches out of 5034
  sample differences:
   FASCIA ETA FASCIA_ETA
0        n.d.        NaN
8        n.d.        NaN
11       n.d.        NaN
14       n.d.        NaN
20       n.d.        NaN
'3nazionalita' ~= 'NAZIONALITA':  316 mismatches out of 5034
  sample differences:
   3nazionalita NAZIONALITA
1           alb         NaN
14          alb         NaN
32          alb         NaN
33          afg         NaN
39          alb         NaN
'compagnia%aerea' ~= 'COMPAGNIA_AEREA':  0 mismatches out of 5034
'num volo' ~= 'NUMERO_VOLO':  0 mismatches out of 5034

In [159]:
cols_to_drop = [
    # Duplicate columns
    "Tipo Documento", "FASCIA ETA", "3nazionalita", "compagnia%aerea", "num volo",
    # Airport descriptions: redundant with IATA codes
    "DESCR_AEREOPORTO_ARR", "DESCR_AEREOPORTO_PART",
    # Arrival country: always "italia"/"ita" — zero variance
    "CODICE_PAESE_ARR", "PAESE_ARR",
    # Departure country: keep PAESE_PART, drop ISO-3 code
    "CODICE_PAESE_PART",
    # Date: subsumed by DATA_PARTENZA (NaT rows already recovered above)
    "ANNO_PARTENZA", "MESE_PARTENZA", "GIORNO_PARTENZA",
]
df2.drop(columns=cols_to_drop, inplace=True)

print(f"Remaining columns ({df2.shape[1]}):")
print(df2.columns.tolist())

Remaining columns (20):
['NAZIONALITA', 'AREOPORTO_ARRIVO', 'AREOPORTO_PARTENZA', 'DATA_PARTENZA', 'CITTA_ARR', 'CITTA_PARTENZA', 'PAESE_PART', 'ZONA', 'ENTRATI', 'INVESTIGATI', 'ALLARMATI', 'TIPO_DOCUMENTO', 'GENERE', 'FASCIA_ETA', 'FLAG_TRANSITO', 'COMPAGNIA_AEREA', 'NUMERO_VOLO', 'ESITO_CONTROLLO', 'note_operatore', 'codice_rischio']

In [160]:
df2

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,DATA_PARTENZA,CITTA_ARR,CITTA_PARTENZA,PAESE_PART,ZONA,ENTRATI,INVESTIGATI,ALLARMATI,TIPO_DOCUMENTO,GENERE,FASCIA_ETA,FLAG_TRANSITO,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio
0,alb,nap,dur,2024-02-13 07:30:00,napoli,durban,sudafrica,6,1,1,0,passaporto,f,NaN,singola tratta,fly dubai,fz1681,respinto,NaN,NaN
1,NaN,fco,jfk,2024-01-22 16:35:00,roma,new york,stati uniti,5,1,0,1,carta d'identità,f,18-30,singola tratta,ita airways,az0609,NaN,NaN,NaN
2,alb,tsf,tia,2024-02-04 20:10:00,treviso,tirana,albania,4,58,58,13,NaN,f,31-45,singola tratta,ryanair dac,fr8400,segnalato,NaN,NaN
3,afg,fco,ist,2024-01-25 13:05:00,roma,istanbul,turchia,5,1,1,0,NaN,m,61+,singola tratta,turkish airlines,tk1865,NaN,NaN,NaN
4,alb,bgy,mle,2024-02-13 00:00:00,bergamo,male,maldive,2,2,2,1,permesso di soggiorno,f,46-60,singola tratta,fly dubai,fz1571,segnalato,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5090,alb,blq,tia,2024-02-18 09:10:00,bologna,tirana,albania,8,87,87,13,NaN,f,0-17,singola tratta,ryanair dac,fr8399,NaN,NaN,NaN
5091,alb,fco,tia,2024-01-10 06:10:00,roma,tirana,albania,5,100,100,11,passaporto,m,46-60,singola tratta,wizz air malta,w43857,NaN,NaN,NaN
5092,alb,fco,jed,2024-01-31 22:15:00,roma,jeddah,arabia saudita,5,4,0,0,NaN,m,31-45,singola tratta,wizz air malta,w48350,fermato,NaN,NaN
5093,alb,bgy,tia,2024-01-01 08:25:00,bergamo,tirana,albania,2,118,120,17,carta d'identità,f,18-30,singola tratta,ryanair dac,fr8350,in attesa,NaN,NaN
5094,alb,fco,mia,2024-01-12 19:50:00,roma,miami,stati uniti,5,1,1,1,carta d'identità,f,61+,singola tratta,ita airways,az0631,fermato,NaN,NaN

# FEATURE ENGINEERING DATASET TIPOLOGIA VIAGGIATORE

In [170]:
df2 = pd.read_csv('data/TIPOLOGIA_VIAGGIATORE_corretto.csv')

df2['ENTRATI']     = pd.to_numeric(df2['ENTRATI'],     errors='coerce')
df2['INVESTIGATI'] = pd.to_numeric(df2['INVESTIGATI'], errors='coerce')
df2['ALLARMATI']   = pd.to_numeric(df2['ALLARMATI'],   errors='coerce')

print(f"Righe iniziali: {len(df2)}")

# Elimina valori estremi assurdi
df2 = df2[df2['ENTRATI'] <= 1000]

# INVESTIGATI > ENTRATI: correggi se differenza <= 5, elimina se > 5
mask = (df2['INVESTIGATI'] > df2['ENTRATI']) & ((df2['INVESTIGATI'] - df2['ENTRATI']) <= 5)
df2.loc[mask, 'INVESTIGATI'] = df2.loc[mask, 'ENTRATI']
df2 = df2[~(df2['INVESTIGATI'] > df2['ENTRATI'])]

# ALLARMATI > INVESTIGATI: correggi se differenza <= 5, elimina se > 5
mask = (df2['ALLARMATI'] > df2['INVESTIGATI']) & ((df2['ALLARMATI'] - df2['INVESTIGATI']) <= 5)
df2.loc[mask, 'ALLARMATI'] = df2.loc[mask, 'INVESTIGATI']
df2 = df2[~(df2['ALLARMATI'] > df2['INVESTIGATI'])]

print(f"Righe finali:   {len(df2)}")
print(f"Dati mantenuti: {100 * len(df2) / 5034:.1f}%")

Righe iniziali: 5034
Righe finali:   4821
Dati mantenuti: 95.8%

#INVESTIGATI > ENTRATI è matematicamente impossibile nella realtà

#ALLARMATI > INVESTIGATI è matematicamente impossibile nella realtà

#ENTRATI = 9999 o 10000 è chiaramente un codice di errore

In [173]:
# Tasso di allarme aggregato per rotta
tasso_allarme = df2.groupby(['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO']).agg(
    totale_investigati = ('INVESTIGATI', 'sum'),
    totale_allarmati   = ('ALLARMATI',   'sum')
).reset_index()

# Calcola il tasso (se INVESTIGATI = 0 → tasso = 0 per evitare divisione per zero)
tasso_allarme['tasso_allarme'] = tasso_allarme.apply(
    lambda row: row['totale_allarmati'] / row['totale_investigati'] 
    if row['totale_investigati'] > 0 else 0,
    axis=1
)

print("=== ANTEPRIMA ===")
print(tasso_allarme.head(10).to_string())
print()
print("=== STATISTICHE ===")
print(tasso_allarme['tasso_allarme'].describe())
print()
print(f"Rotte totali:            {len(tasso_allarme)}")
print(f"Rotte con tasso = 0:     {(tasso_allarme['tasso_allarme'] == 0).sum()}")
print(f"Rotte con tasso > 0:     {(tasso_allarme['tasso_allarme'] > 0).sum()}")
print(f"Rotte con tasso > 0.5:   {(tasso_allarme['tasso_allarme'] > 0.5).sum()}")

=== ANTEPRIMA ===
  AREOPORTO_PARTENZA AREOPORTO_ARRIVO  totale_investigati  totale_allarmati  tasso_allarme
0                abj              cag                 1.0               0.0            0.0
1                adb              bgy                 1.0               0.0            0.0
2                adb              fco                 1.0               1.0            1.0
3                adb              mxp                 5.0               2.0            0.4
4                adb              nap                 2.0               0.0            0.0
5                add              fco                 1.0               0.0            0.0
6                adl              mxp                 1.0               0.0            0.0
7                aer              mxp                 1.0               1.0            1.0
8                akl              fco                 1.0               0.0            0.0
9                ala              mxp                 1.0               0.0            0.0

=== STATISTICHE ===
count    458.000000
mean       0.245465
std        0.316671
min        0.000000
25%        0.000000
50%        0.141551
75%        0.337486
max        1.000000
Name: tasso_allarme, dtype: float64

Rotte totali:            458
Rotte con tasso = 0:     193
Rotte con tasso > 0:     265
Rotte con tasso > 0.5:   65

In [179]:

# TRANSIT VOLUMES — Volume di transito per rotta 
# misura la quantità del traffico (quante persone passano)
# soglia minima 5 voli 

transit_volumes = df2.groupby(['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO']).agg(
    totale_entrati = ('ENTRATI', 'sum'),
    media_entrati  = ('ENTRATI', 'mean'),
    n_voli         = ('ENTRATI', 'count')
).reset_index()

# Applica soglia: tieni solo rotte con almeno 5 voli
transit_volumes = transit_volumes[transit_volumes['n_voli'] >= 5]

print("=== TRANSIT VOLUMES PER ROTTA (soglia >= 5 voli) ===")
print(transit_volumes.describe())
print()
print(f"Rotte totali dopo soglia: {len(transit_volumes)}")
print(f"Rotte scartate:           {458 - len(transit_volumes)}")
print()
print("=== TOP 10 ROTTE PIÙ TRAFFICATE ===")
print(transit_volumes.sort_values('totale_entrati', ascending=False).head(10).to_string())

#Rotte: 458 → 150 (perdiamo il 67%) — sembra tanto
#Ma righe coperte: 4468 su 5034 → 88.8%

=== TRANSIT VOLUMES PER ROTTA (soglia >= 5 voli) ===
       totale_entrati  media_entrati      n_voli
count      150.000000     150.000000  150.000000
mean      1165.860000      12.956432   28.546667
std       3925.594038      28.670223   44.652662
min          5.000000       1.000000    5.000000
25%         11.250000       1.338235    7.000000
50%         22.000000       1.699095   13.000000
75%         76.250000       2.252101   28.000000
max      24931.000000     122.200000  284.000000

Rotte totali dopo soglia: 150
Rotte scartate:           308

=== TOP 10 ROTTE PIÙ TRAFFICATE ===
    AREOPORTO_PARTENZA AREOPORTO_ARRIVO  totale_entrati  media_entrati  n_voli
407                tia              bgy         24931.0      87.785211     284
422                tia              psa         20806.0     110.084656     189
408                tia              blq         20128.0      91.076923     221
418                tia              mxp         18302.0      87.990385     208
414                tia              fco         14232.0      65.888889     216
429                tia              tsf         12421.0      74.377246     167
431                tia              vrn         10050.0     115.517241      87
427                tia              trn          8401.0     107.705128      78
411                tia              cia          6433.0      82.474359      78
409                tia              bri          5674.0      48.084746     118

In pratica il modello usa il volume per pesare quanto fidarsi del tasso di allarme. 

Una deviazione su una rotta ad alto volume è molto più significativa della stessa deviazione su una rotta quasi vuota.

# FEATURE ENGINEERING DATASET ALLARMI

In [182]:
df1 = pd.read_csv('data/ALLARMI_corretto.csv')
df1 = df1.map(lambda x: x.strip().lower() if isinstance(x, str) else x)
df1['TOT'] = pd.to_numeric(df1['TOT'], errors='coerce')
df1['ZONA'] = pd.to_numeric(df1['ZONA'], errors='coerce')

# Pulizia: rimuovi ZONA anomale e TOT null
df1 = df1[~df1['ZONA'].isin([99, 10])]
df1 = df1[df1['TOT'].notna()]

# Volume allarmi per rotta: solo righe "allarmi generati"
allarmi_rotta = df1[df1['OCCORRENZE'] == 'allarmi generati'].groupby(
    ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO']
).agg(
    volume_allarmi = ('TOT', 'sum'),
    n_occorrenze   = ('TOT', 'count')
).reset_index()

print(f"Rotte con allarmi: {len(allarmi_rotta)}")
print()
print("STATISTICHE")
print(allarmi_rotta['volume_allarmi'].describe())
print()
print("TOP 10 ROTTE CON PIÙ ALLARMI")
print(allarmi_rotta.sort_values('volume_allarmi', ascending=False).head(10).to_string())

Rotte con allarmi: 177

STATISTICHE
count    177.000000
mean      35.378531
std       44.907331
min        1.000000
25%        7.000000
50%       18.000000
75%       47.000000
max      261.000000
Name: volume_allarmi, dtype: float64

TOP 10 ROTTE CON PIÙ ALLARMI
    AREOPORTO_PARTENZA AREOPORTO_ARRIVO  volume_allarmi  n_occorrenze
152                tia              bgy           261.0            11
153                tia              blq           217.0             7
162                tia              psa           212.0             8
2                  add              mxp           197.0             3
23                 cai              bgy           169.0             4
166                tia              tsf           158.0             8
29                 cmn              vce           147.0             4
25                 cai              mxp           146.0             5
59                 ist              blq           126.0             8
133                ssh              mxp           115.0            10

In [183]:
dist_motivo = df1[df1['OCCORRENZE'] == 'allarmi generati'].groupby(
    ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO', 'MOTIVO_ALLARME']
).agg(
    volume_per_motivo = ('TOT', 'sum'),
    n_occorrenze      = ('TOT', 'count')
).reset_index()

dist_motivo = dist_motivo[dist_motivo['MOTIVO_ALLARME'].notna()]

totale_per_rotta = dist_motivo.groupby(
    ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO']
)['volume_per_motivo'].transform('sum')

dist_motivo['pct_motivo'] = dist_motivo['volume_per_motivo'] / totale_per_rotta

print(f"Combinazioni rotta + motivo: {len(dist_motivo)}")
print()
print("DISTRIBUZIONE GLOBALE PER MOTIVO")
print(dist_motivo.groupby('MOTIVO_ALLARME')['volume_per_motivo'].sum().sort_values(ascending=False).to_string())
print()
print("TOP 10 COMBINAZIONI PIÙ FREQUENTI")
print(dist_motivo.sort_values('volume_per_motivo', ascending=False).head(10).to_string())

Combinazioni rotta + motivo: 296

DISTRIBUZIONE GLOBALE PER MOTIVO
MOTIVO_ALLARME
sdi         1075.0
interpol     919.0
nsis         888.0
tsc          879.0
manuale      858.0

TOP 10 COMBINAZIONI PIÙ FREQUENTI
    AREOPORTO_PARTENZA AREOPORTO_ARRIVO MOTIVO_ALLARME  volume_per_motivo  n_occorrenze  pct_motivo
271                tia              psa            sdi               95.0             4    0.519126
32                 cai              mxp        manuale               85.0             2    0.620438
245                tia              bgy            tsc               82.0             3    0.561644
248                tia              blq            sdi               77.0             2    0.356481
246                tia              blq       interpol               76.0             2    0.351852
8                  auh              mxp       interpol               65.0             2    1.000000
87                 ist              blq            sdi               61.0             4    0.635417
52                 dxb              blq            sdi               59.0             2    0.572816
55                 dxb              fco           nsis               59.0             2    0.517544
160                lrm              mxp       interpol               54.0             2    1.000000

In [184]:
rischio_zona = df1[df1['OCCORRENZE'] == 'allarmi generati'].groupby('ZONA').agg(
    volume_allarmi_zona = ('TOT', 'sum'),
    n_occorrenze_zona   = ('TOT', 'count')
).reset_index()

rischio_zona['media_allarmi_zona'] = rischio_zona['volume_allarmi_zona'] / rischio_zona['n_occorrenze_zona']

print("BASELINE RISCHIO PER ZONA")
print(rischio_zona.sort_values('volume_allarmi_zona', ascending=False).to_string())

BASELINE RISCHIO PER ZONA
   ZONA  volume_allarmi_zona  n_occorrenze_zona  media_allarmi_zona
1   2.0               2623.0                200           13.115000
6   8.0               1099.0                 67           16.402985
3   5.0               1031.0                125            8.248000
2   4.0                765.0                 67           11.417910
4   6.0                241.0                 21           11.476190
0   1.0                237.0                 16           14.812500
5   7.0                137.0                 18            7.611111
7   9.0                129.0                 10           12.900000

# MERGE THE TWO DATASETS

In [186]:
import pandas as pd
import numpy as np

df1 = pd.read_csv('data/ALLARMI_corretto.csv')
df2 = pd.read_csv('data/TIPOLOGIA_VIAGGIATORE_corretto.csv')
df1 = df1.map(lambda x: x.strip().lower() if isinstance(x, str) else x)
df2 = df2.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

df1['TOT']  = pd.to_numeric(df1['TOT'],  errors='coerce')
df1['ZONA'] = pd.to_numeric(df1['ZONA'], errors='coerce')
df2['ENTRATI']     = pd.to_numeric(df2['ENTRATI'],     errors='coerce')
df2['INVESTIGATI'] = pd.to_numeric(df2['INVESTIGATI'], errors='coerce')
df2['ALLARMATI']   = pd.to_numeric(df2['ALLARMATI'],   errors='coerce')

df1.loc[df1['ZONA'].isin([99, 10]), 'ZONA'] = np.nan

df2 = df2[df2['ENTRATI'] <= 1000]
mask = (df2['INVESTIGATI'] > df2['ENTRATI']) & ((df2['INVESTIGATI'] - df2['ENTRATI']) <= 5)
df2.loc[mask, 'INVESTIGATI'] = df2.loc[mask, 'ENTRATI']
df2 = df2[~(df2['INVESTIGATI'] > df2['ENTRATI'])]
mask = (df2['ALLARMATI'] > df2['INVESTIGATI']) & ((df2['ALLARMATI'] - df2['INVESTIGATI']) <= 5)
df2.loc[mask, 'ALLARMATI'] = df2.loc[mask, 'INVESTIGATI']
df2 = df2[~(df2['ALLARMATI'] > df2['INVESTIGATI'])]

# Feature 1 + 2 con nuova soglia
tasso_allarme = df2.groupby(['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO']).agg(
    totale_investigati = ('INVESTIGATI', 'sum'),
    totale_allarmati   = ('ALLARMATI',   'sum'),
    totale_entrati     = ('ENTRATI',     'sum'),
    n_voli_tip         = ('ENTRATI',     'count')
).reset_index()

# NUOVA SOGLIA: >= 3 voli e >= 10 passeggeri
tasso_allarme = tasso_allarme[
    (tasso_allarme['n_voli_tip'] >= 3) &
    (tasso_allarme['totale_entrati'] >= 10)
]

tasso_allarme['tasso_allarme'] = tasso_allarme.apply(
    lambda row: row['totale_allarmati'] / row['totale_investigati']
    if row['totale_investigati'] > 0 else 0, axis=1
)

print(f"Feature 1+2: {len(tasso_allarme)} rotte")

# Feature 3
volume_allarmi = df1[df1['OCCORRENZE'] == 'allarmi generati'].groupby(
    ['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO']
).agg(volume_allarmi=('TOT','sum'), n_occorrenze=('TOT','count')).reset_index()

# Feature 4
dist_motivo = df1[
    (df1['OCCORRENZE'] == 'allarmi generati') &
    (df1['MOTIVO_ALLARME'].notna())
].groupby(['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO','MOTIVO_ALLARME']).agg(
    volume_per_motivo=('TOT','sum')).reset_index()
tot_rotta = dist_motivo.groupby(['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO'])['volume_per_motivo'].transform('sum')
dist_motivo['pct_motivo'] = dist_motivo['volume_per_motivo'] / tot_rotta
dist_motivo_pivot = dist_motivo.pivot_table(
    index=['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO'],
    columns='MOTIVO_ALLARME', values='pct_motivo', fill_value=0
).reset_index()
dist_motivo_pivot.columns = [
    f'pct_{c}' if c not in ['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO'] else c
    for c in dist_motivo_pivot.columns
]

# Feature 5
zona_per_rotta = df1.groupby(['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO'])['ZONA'].agg(
    lambda x: x.mode()[0] if x.notna().sum() > 0 else np.nan
).reset_index()
zona_per_rotta.columns = ['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO','zona_frequente']
rischio_zona = df1[df1['OCCORRENZE'] == 'allarmi generati'].groupby('ZONA').agg(
    media_allarmi_zona=('TOT','mean')).reset_index()
rischio_zona.columns = ['zona_frequente','media_allarmi_zona']
zona_per_rotta = zona_per_rotta.merge(rischio_zona, on='zona_frequente', how='left')

# MERGE FINALE
df_finale = tasso_allarme.copy()
df_finale = df_finale.merge(volume_allarmi,    on=['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO'], how='left')
df_finale = df_finale.merge(dist_motivo_pivot, on=['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO'], how='left')
df_finale = df_finale.merge(zona_per_rotta,    on=['AREOPORTO_PARTENZA','AREOPORTO_ARRIVO'], how='left')

print(f"DF FINALE: {len(df_finale)} rotte x {len(df_finale.columns)} colonne")
print()
print("NULL PER COLONNA")
print(df_finale.isnull().sum().to_string())
print()
print("ANTEPRIMA")
print(df_finale.head(5).to_string())

df_finale.to_csv('data/df_finale_feature_engineering.csv', index=False)
print()
print("File salvato: data/df_finale_feature_engineering.csv")

Feature 1+2: 121 rotte
DF FINALE: 121 rotte x 16 colonne

NULL PER COLONNA
AREOPORTO_PARTENZA     0
AREOPORTO_ARRIVO       0
totale_investigati     0
totale_allarmati       0
totale_entrati         0
n_voli_tip             0
tasso_allarme          0
volume_allarmi        38
n_occorrenze          38
pct_interpol          45
pct_manuale           45
pct_nsis              45
pct_sdi               45
pct_tsc               45
zona_frequente        13
media_allarmi_zona    13

ANTEPRIMA
  AREOPORTO_PARTENZA AREOPORTO_ARRIVO  totale_investigati  totale_allarmati  totale_entrati  n_voli_tip  tasso_allarme  volume_allarmi  n_occorrenze  pct_interpol  pct_manuale  pct_nsis  pct_sdi  pct_tsc  zona_frequente  media_allarmi_zona
0                amm              bgy                16.0               1.0            16.0           6       0.062500             9.0           1.0           0.0          1.0       0.0      0.0      0.0             2.0              13.115
1                amm              fco                 0.0               0.0            10.0           4       0.000000             1.0           1.0           0.0          0.0       0.0      0.0      1.0             5.0               8.248
2                auh              fco                37.0               6.0            56.0          26       0.162162            63.0           5.0           0.0          0.5       0.0      0.0      0.5             5.0               8.248
3                bfs              bgy                10.0               2.0            10.0           6       0.200000             1.0           1.0           NaN          NaN       NaN      NaN      NaN             2.0              13.115
4                bhx              bgy                15.0               1.0            15.0           9       0.066667             0.0           0.0           NaN          NaN       NaN      NaN      NaN             2.0              13.115

File salvato: data/df_finale_feature_engineering.csv